### ISSUE TITLE
Auto Close

### ISSUE THREAD

**Issue by skworden** [craftpip/jquery-confirm#100]
Auto close will not work without using whole numbers i.e. 1000ms or 2000ms and cant use 1500ms.
Also, if the options showConfirmButton and showCancelButton are set to false it won't autoclose.

**Comment by craftpip** [comment]
This is fixed in v3. please check and reopen the issue

**Comment by zeing** [comment]
can i set time 500ms ?

**Comment by craftpip** [comment]
Yes you can, 
```
autoClose: 'buttonName|500',
```

**Comment by zeing** [comment]
I try 500 ms but it show me 0.5 -1.0 -1.5 bra bra bra



Sent from my iPhone

On 13 Dec 2016, at 18:47, Boniface Pereira <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes you can,

autoClose: 'buttonName|500',


-

**Comment by craftpip** [comment]
That was expected, how else should it be done ?
can u please give me some test cases

**Comment by zeing** [comment]
it don't close and show time 0.5 -1.0 -1.5 bra bra  it's closed when you click button 

this is my code $.alert({
                                    title: 'Account Profile',
                                    content: 'Send Ticket Success !!!',
                                    autoClose: 'ok|500'
                                })


![image](https://cloud.githubusercontent.com/assets/20161393/21144126/1d2a4e6c-c17c-11e6-92fc-7749e629de64.png)

![image](https://cloud.githubusercontent.com/assets/20161393/21144138/231ba744-c17c-11e6-957e-8eb5ed65dc29.png)

**Comment by craftpip** [comment]
Sorry @zeing for the late reply,
fixing this asap.
this got buried in the issues, as it was closed. 
apologies.

**Comment by craftpip** [comment]
miliseconds is not possbile, the view will display it in decimals, not a good UX, so the number of rounded (ceil)

**Comment by zeing** [comment]
okay thank you
