### ISSUE TITLE
Close action

### ISSUE THREAD

**Issue by skworden** [craftpip/jquery-confirm#101]
There are three actions you can call in the onAction setting and they are close, cancel, and confirm.  There are only 2 options in the settings cancel and confirm.  I think we should be able to hook into all three actions including the close action. i.e.

```
confirm: function() {
            return false;
        },
        cancel: function() {
            return false;
        },
        close:function(){
             return false;
        },
```

I'm trying to stop the closing using the close icon and the hook into the close event in the onAction function.  However setting the close to false just breaks it.

**Comment by rickydeez** [comment]
+1

**Comment by craftpip** [comment]
This is added in v3, :)
