### ISSUE TITLE
Confirm form

### ISSUE THREAD

**Issue by nikitapoga** [craftpip/jquery-confirm#102]
Hi, I tried to confirm form request, when I click OKAY it doesn't redirect me to the url, can you help me with this issue. Thank in advance.
Html: 
 <form id="check" action="http://google.ru">
         <input type="submit" value="text 1" />
    </form>
JS:
  $('#check').confirm();

**Comment by craftpip** [comment]
$('#check').confirm(); this makes a event listener for click, 
form dispatches the submit event.
