### ISSUE TITLE
how to process selected submit button in form with multiple submit buttons

### ISSUE THREAD

**Issue by sondang86** [craftpip/jquery-confirm#104]
Hi, 

I have 2 delete submit buttons in single form and integrated with jquery-confirm. When I click on specific delete button (18), it submit the whole form, what I wanted is only the clicked button allowed to submit, below is my code:

```
<form action="" method="POST" id="messages">
<button type="submit" name="message_id" value="18" class="btn btn-danger confirmation" >Delete</button>

<button type="submit" name="message_id" value="17" class="btn btn-danger confirmation" >Delete</button>
</form>
```

Jquery code:

```
$('.confirmation').confirm({
        content: 'Delete this message?',
        title: 'Please confirm',
        confirm: function(){
            $('#messages :submit').submit();
        }
    });
```

Please tell me is there any way to achieve such action. If i add `onclick="return confirm('Delete this message?');"` in button, it will trigger alert box and submit the selected button only, not the whole form submission.

**Comment by dvmobley** [comment]
Lookup prevent default.

Dale

Sent from my iPhone

On May 20, 2016, at 2:13 AM, sondang86 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I have 2 delete submit buttons in single form and integrated with jquery-confirm. When I click on specific delete button (18), it submit the whole form, what I wanted is only the clicked button allowed to submit, below is my code:

<form action="" method="POST" id="messages">
<button type="submit" name="message_id" value="18" class="btn btn-danger confirmation" >Delete</button>

<button type="submit" name="message_id" value="17" class="btn btn-danger confirmation" >Delete</button>
</form>


Jquery code:

$('.confirmation').confirm({
        content: 'Delete this message?',
        title: 'Please confirm',
        confirm: function(){
            $('#messages :submit').submit();
        }
    });


Please tell me is there any way to achieve such action. If i add onclick="return confirm('Delete this message?');" in button, it will trigger alert box and submit the selected button only, not the whole form submission.
