### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by Deliator** [craftpip/jquery-confirm#105]
Hello,

Is it possible to customize the loader while loading ajax content ?
For example, i need to display a text while loading (or displaying another img)

Thanks

**Comment by dvmobley** [comment]
Can't you add a listener to the window that watches for Ajax loading?

Dale

Sent from my iPhone

On May 20, 2016, at 6:51 AM, Deliator <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Is it possible to customize the loader while loading ajax content ?
For example, i need to display a text while loading (or displaying another img)

Thanks

**Comment by craftpip** [comment]
@Deliator you can do this using a custom theme now in v3.
