### ISSUE TITLE
nested and looped confirms.

### ISSUE THREAD

**Issue by ghost** [craftpip/jquery-confirm#106]
it can be good to loop confirms.
suppose we have confirm, if clicked no, nothing; but if clicked yes, show another confirm(now it can be by 2 nested confirm), but very more important:
now after check answer, we must show first confirm, or each one we need.

[also i appreciate for use FARSI as RTL example, thank you,
Farsi is sugar but:
خوش تر آن باشد که سر دلبران، گفته آید در حدیث دیگران]

**Comment by craftpip** [comment]
So far i understand you want to open a closed confirm box, this can be done in v3.
