### ISSUE TITLE
it  is not support on IE7

### ISSUE THREAD

**Issue by onexuan** [craftpip/jquery-confirm#108]
It work well on Chrome, Opera, but it  is not support on IE7, Could you fix it?

**Comment by dvmobley** [comment]
JQuery version 2 and higher, Bootstrap, CSS3 and HTML5 do not support IE7. Besides IE7 was EoL over a decade ago.

What possible scenario do you have to use this plugin on that platform?

Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…

**Comment by onexuan** [comment]
OK. Thank you
