### ISSUE TITLE
jconfirm shows at top of the document when focus is on textarea

### ISSUE THREAD

**Issue by junbonglee** [craftpip/jquery-confirm#109]
I have a button that calls jconfrim to open.(It is a button to input emoji in comment area) It works fine but when the focus is on textarea, jconfirm show at top of the document(scrolls all the way up where the post title shows). And It seems this happen only on mobile phones.(Iphone tested, Android not yet)

I found many people had same issues when they are dealing with bootstrap modal, and tried to find the answer. But I couldn't.

how can I fix this? Is there anyone having similar problem like me?

**Comment by junbonglee** [comment]
UPDATED:

I have tested on Android devices, but it works fine. I think this problem only happens on iOS.
I think this problem happens when keyboard is open.

I tried to check if focus is causing the problem, but it wasn't.

**Comment by junbonglee** [comment]
SOLVED?

I couldn't find the solution, but i found a workaround to solve this. Before making a call for query-confirm I gave a little timeout(50ms) to make sure iOS keyboard gets closed, and then make a call to open query-confirm. I think this is not the perfect solution, but it works.

**Comment by craftpip** [comment]
IOS has reported a lot of issues, i will update asap.
