### ISSUE TITLE
Adding space as an "KEYBOARD ACTIONS" that calls confirm() just like Enter

### ISSUE THREAD

**Issue by Pecka40** [craftpip/jquery-confirm#11]
I guess the title says it, would be really nice that space would do the same as enter for keyboard actions. :)

**Comment by craftpip** [comment]
@Pecka40 
Oh yeah, Adding SPACE will be nice :)
i will add it soon.
Thanks for pointing that out.

**Comment by craftpip** [comment]
Feature is added
