### ISSUE TITLE
report in IOS, chrome , content height is error

### ISSUE THREAD

**Issue by sbmzhcn** [craftpip/jquery-confirm#111]
when i run script on chrome in IOS 9

use ajax load html,  popup confirm height is error.

code in desktop

```
<div class="content-pane" style="transition-duration: 0.5s; transition-timing-function: cubic-bezier(0.36, 1.1, 0.2, 1); height: 565px;"><div class="content" style="clip: rect(0px 828px 565px -100px);">
```

in ios chrome 

```
<div class="content-pane" style="transition-duration: 0.5s; transition-timing-function: cubic-bezier(0.36, 1.1, 0.2, 1); height: 40px;"><div class="content" style="clip: rect(0px 828px 40px -100px);">
```

**Comment by dvmobley** [comment]
There is known problem with iOS and the height. Please see the bug “Issue with iOS dialog height on open”.

Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…
