### ISSUE TITLE
Need help triggering a <input type="submit"> button if a confirm box is confirmed.

### ISSUE THREAD

**Issue by dud3sweet** [craftpip/jquery-confirm#112]
Hello,

This code works perfectly with a regular confirm box:
jQuery( "input.submitbutton" ).click(function () {
  if (confirm("text") == true) {
        return true;
    } else {
        return false;
    }
});

The problem is I need to use a large .txt file in the content of the confirm box which isn't possible with the regular confirm method, so I wanted to try to achieve that with this jquery-confirm plugin. But I'm having trouble figuring out how to code the jquery-confirm plugin box to do the same thing that my original code is already doing. Any suggestions or code snippets would be very much appreciated.

Thank you!

**Comment by craftpip** [comment]
You can find a solution to this here.  #35
