### ISSUE TITLE
Switch order of cancel and confirm buttons

### ISSUE THREAD

**Issue by hoermannklaus** [craftpip/jquery-confirm#113]
I would suggest to switch the order of the cancel and confirm buttons. IMHO is this more intuitive.

I fixed your plugin for my needs, by just switching the lines when you add the buttons to the .buttons div. Maybe an option would be nice to set the flow of the buttons.

**Comment by craftpip** [comment]
hello @hoermannklaus 
in the latest update v3, you can define multiple buttons. so the order is not a problem now.
