### ISSUE TITLE
iOS issues : when focus is on input(inside jquery-confirm), text blurs

### ISSUE THREAD

**Issue by junbonglee** [craftpip/jquery-confirm#114]
Does anyone had experience this issue?

I have a query-confirm that contains input.
When I touch the input area, screen blurs. I mean not blur(), it really blurs and make hard to read the text. (Check the screenshot on iPhone)
I tried on Android devices but it's ok on them. This is issue only happens on iOS.

![img_1254](https://cloud.githubusercontent.com/assets/10484267/15694371/0c7668a0-27d8-11e6-8ab0-36f86d0caad0.jpg)

I tried to solve the issue, but I couldn't even find out what's making the issue happen.

**Comment by craftpip** [comment]
Not sure about this, will consider checking it
