### ISSUE TITLE
Not possible to hide confirm button, or cancel button 

### ISSUE THREAD

**Issue by tommwenda** [craftpip/jquery-confirm#118]
``` javascript
$.confirm({
        title: false, // hides the title.
        cancelButton: false ,// hides the cancel button.
        confirmButton: false, // hides the confirm button.
        closeIcon: false, // hides the close icon.
        content: false, // hides content block.
    });
```

This displays as below:

![screen shot 2016-06-09 at 22 18 41](https://cloud.githubusercontent.com/assets/2370737/15942958/6cabe94e-2e8f-11e6-9f6c-fe1040bacf74.png)

**Comment by tommwenda** [comment]
i am using jQuery v2.1.1

**Comment by gags88** [comment]
This is actually can be done:

- Create a class named 'hide' in css if not in framework that you ate using.

   .hide{
     display: none
   }

- Now in jQuery

  ` $(".confirm").confirm({confirmButtonClass: 'hide'});`

this will do the trick

**Comment by tommwenda** [comment]
it works now. thanks.

**Comment by mhavid** [comment]
`buttons: {
        ok: {
       isHidden: true, // hide the button
      }
}`

**Comment by diogenesjup** [comment]
The solution apresented for @mhavid works for me
