### ISSUE TITLE
Optional function usage

### ISSUE THREAD

**Issue by atayahmet** [craftpip/jquery-confirm#120]
hi

Using optional function will be very useful.

``` javascript
$.confirm({         
    title: 'Say Hello',
    content: function() {
        return 'Hello from Istanbul!';
    }
});
```

Thanks.

**Comment by atayahmet** [comment]
Hi again,

function had to use but it's returns the ajax promise. If that will be usefull optionally run the callback function and get only return.

**Comment by craftpip** [comment]
This is added in v3, u can use function in content now, and return a string, too.
