### ISSUE TITLE
misplaced alert

### ISSUE THREAD

**Issue by jonaygalvan** [craftpip/jquery-confirm#121]
Hi guys!

When I launch the alert appears scrolling down the page…

Any idea?

Thanks in advance.

Regards

**Comment by dvmobley** [comment]
Sounds like Bootstrap, CSS or JQuery dependency issue.

Dale

Sent from my iPhone

On Jun 22, 2016, at 4:47 PM, jonaygalvan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi guys!

When I launch the alert appears scrolling down the page…

Any idea?

Thanks in advance.

Regards

**Comment by jonaygalvan** [comment]
Yeah! I am using bootstrap.

It id a common issue?



Regards

On Wednesday, 22 June 2016, dvmobley <notifications@github.com> wrote:

> Sounds like Bootstrap, CSS or JQuery dependency issue.
>
> Dale
>
> Sent from my iPhone
>
> On Jun 22, 2016, at 4:47 PM, jonaygalvan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
>
>
> Hi guys!
>
> When I launch the alert appears scrolling down the page…
>
> Any idea?
>
> Thanks in advance.
>
> Regards
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<
> https://github.com/craftpip/jquery-confirm/issues/121>, or mute the
> thread<
> https://github.com/notifications/unsubscribe/AQw9yHSEvm1XqqcE9rbztAdjmjifAiw4ks5qOZ93gaJpZM4I8NGx
> >.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/craftpip/jquery-confirm/issues/121#issuecomment-227899484>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATKsbyLbybVe2Kp7FazzIGaMbIkXrIW1ks5qObpQgaJpZM4I8NGx>
> .
>


-- 



--
Jonay Galván

about me:
http://about.me/jonaygs

**Comment by dvmobley** [comment]
Check version dependencies.

Dale

Sent from my iPhone

On Jun 22, 2016, at 7:14 PM, jonaygalvan <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah! I am using bootstrap.

It id a common issue?



Regards

On Wednesday, 22 June 2016, dvmobley <notifications@github.com<mailto:notifications@github.com>> wrote:

> Sounds like Bootstrap, CSS or JQuery dependency issue.
>
> Dale
>
> Sent from my iPhone
>
> On Jun 22, 2016, at 4:47 PM, jonaygalvan <notifications@github.com<mailto:notifications@github.com>
> <javascript:_e(%7B%7D,'cvml','notifications@github.com<mailto:notifications@github.com>');><mailto:
> notifications@github.com<mailto:notifications@github.com>
> <javascript:_e(%7B%7D,'cvml','notifications@github.com<mailto:notifications@github.com>');>>> wrote:
>
>
> Hi guys!
>
> When I launch the alert appears scrolling down the page…
>
> Any idea?
>
> Thanks in advance.
>
> Regards
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<
> https://github.com/craftpip/jquery-confirm/issues/121>, or mute the
> thread<
> https://github.com/notifications/unsubscribe/AQw9yHSEvm1XqqcE9rbztAdjmjifAiw4ks5qOZ93gaJpZM4I8NGx
> >.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/craftpip/jquery-confirm/issues/121#issuecomment-227899484>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATKsbyLbybVe2Kp7FazzIGaMbIkXrIW1ks5qObpQgaJpZM4I8NGx>
> .
>


--



--
Jonay Galván

about me:
http://about.me/jonaygs
