### ISSUE TITLE
Issues with the container option

### ISSUE THREAD

**Issue by mdearaujo** [craftpip/jquery-confirm#123]
Hello,

This question could really be broken down to two issues:

I have a form with some required fields. I originally had a submit button that would show a dialog box with a prompt whether they were sure they wanted to confirm or not. The problem was, when I clicked the submit button, it ignored that I had required attributes and didn't mind that there were no values entered in the required fields. It would be nice to only show the confirm prompt if all required fields have values.

I changed tactics to have popups for each input to show if they didn't have values and only confirm the form when all fields have values. I thought by using the container option I could force them to appear near the appropriate input. However, it always shows in the center of the page. I might be writing the code wrong but would really appreciate any help!

Thank you.

**Comment by craftpip** [comment]
I'm real late to reply on this,

for the first issue, you should not bind to the button click, but for the form's submit event. 

for the second issue, jquery-confirm was ment to be a dialog so, it will center itself on the screen. 
if you're using the container option, then the container div should be `position:relative`
