### ISSUE TITLE
Unable to create Confirm dialogue with in Confirm Dialogue

### ISSUE THREAD

**Issue by vrkumar** [craftpip/jquery-confirm#125]
Confirm Dialogue is working fine. But I want to Create ask confirm dialogue after the 1st Confirm Dialogue.
Example:  $.confirm({
                title: 'Test',
                text: 'Are you sure, you want to delete this record?',
                confirm: function () {
                    fnCheckExistance();
                },
                cancel: function () {
                }
            });
function fnCheckExistance()
{
//Here i want to get Confirmation Request... which is not firing....
  $.confirm({
                title: 'Test',
                text: 'Final Check, you really want to delete this record?',
                confirm: function () {
                    fnDelete();
                },
                cancel: function () {
                }
            });
}

**Comment by craftpip** [comment]
This should have worked, try declaring the fnCheckExistance as global variable 
`window.fnCheckExistance = function(){ ..`
