### ISSUE TITLE
Confirmation windows appearing then suddenly dissapearing

### ISSUE THREAD

**Issue by bfriebe** [craftpip/jquery-confirm#126]
So when I have an anchor tag <a class="delete" href="example.com">Clicky</a> and even the most simple confirm $('.delete').on('click',function () {
$.confirm('stuff','stuffhere');
});

the box will appear, but before even a second goes by, the box disappears and the webpage proceeded to the link (in this case, example.com). Why is it that it doesn't wait for the response like on the example page

**Comment by dvmobley** [comment]
Prevent default?


Sent from my iPhone

On Jul 8, 2016, at 3:47 PM, Brad Friebe <notifications@github.com<mailto:notifications@github.com>> wrote:


So when I have an anchor tag Clicky<example.com> and even the most simple confirm $('.delete').on('click',function () {
$.confirm('stuff','stuffhere');
});

the box will appear, but before even a second goes by, the box disappears and the webpage proceeded to the link (in this case, example.com<http://example.com>). Why is it that it doesn't wait for the response like on the example page
