### ISSUE TITLE
Multiple Alerts/Dialog/Confirm

### ISSUE THREAD

**Issue by abjac** [craftpip/jquery-confirm#127]
If I want to show multiple Alerts/Dialog/Confirm one after another, the one initiated at the last is shown on the top

$.alert('Content 1', 'Title 1');
$.alert('Content 2', 'Title 2');

Here first alert 'Content 1' is shown and immediately 'Content 2' on top of the first.

In short, each alert is not waiting for an OK/Cancel from user to show the next alert

**Comment by craftpip** [comment]
Hello @abjac , you have to call the second alert in the first alert, 
are you expecting the modals to queue? so that when one is open second will wait ?

**Comment by medinsky** [comment]
Hello @craftpip, can you explain me how can I fix the same bug?
I have a table, on each row I have a confirm 
$("tr.confirm").confirm({
            title: 'Encountered an error!',
            content: 'Something went downhill, this may be serious',
            type: 'red',
            typeAnimated: true,
            animation: 'zoom',
            animationSpeed: 300, 
            closeAnimation: 'zoom',
            backgroundDismiss: false,
            backgroundDismissAnimation: 'glow',
            onDestroy: function(){
            	$(".jconfirm").remove();
            },
            buttons: {
                tryAgain: {
                    text: 'Try again',
                    btnClass: 'btn-red',
                    action: function(){
                    }
                },
                close: function () {
                }
            }
        });

modals shows on mouseclick
after I close the upper windows, I need to close every previously loaded modal window
first click opens 1 window and I normally can close it without problems
next, (without reload page)
second click gives me my modal window, but after closing it I need to close first-click-loaded window that is under second,
the third click gives me a new modal and two previous, and I need to close them all, every new click returns +1 windows and all of previously loaded. How to fix it?

**Comment by craftpip** [comment]
hello @medinsky so far i understood you have a queue of modals,
So you need to close all the modals, if the latest one was closed?

create an array of instances, and then loop through them to close them.
```js
var instances = [];
var a = $.confirm('hey');
instances.push(a);
$.each(a, function(i, b){
    if(b.isOpen())
        b.close();
})
```
