### ISSUE TITLE
how to  code registration success with jquery confirm

### ISSUE THREAD

**Issue by vsjegadeesh** [craftpip/jquery-confirm#128]
i am a newbie and am confused to use jquery confirm

**Comment by craftpip** [comment]
I need more information for what you're trying to do.

**Comment by dvmobley** [comment]
Maybe try starting here http://craftpip.github.io/jquery-confirm/


Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…
