### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by Sarfroz** [craftpip/jquery-confirm#129]
hello sir how can i add an iframe

**Comment by dvmobley** [comment]
Content: "<iframe src='url'></iframe >"



Sent from my iPhone

On Jul 20, 2016, at 12:02 AM, Sarfroz <notifications@github.com<mailto:notifications@github.com>> wrote:


hello sir how can i add an iframe

**Comment by Sarfroz** [comment]
thanks sir its working fine only it lacks a loadig image as when content
method loads any local file

**Comment by craftpip** [comment]
For loading, you can use jconfirm's showLoading and hideLoading and listen to iframe onLoad event
