### ISSUE TITLE
Overflow content choice

### ISSUE THREAD

**Issue by usb248** [craftpip/jquery-confirm#13]
Why the scrollbar to manage the overflow content is put in the modal/alert rather than on the windows (with overflow:auto ) ? On Tablet or mobile device, when the scrollbar is attach to the device screen, i think that it's better and simply to scroll content (in the case where the content overflow the height of the screen) ?

Actually : 
![demo](https://cloud.githubusercontent.com/assets/7659927/7356543/200ca40a-ed29-11e4-996d-b5c5483ff2bb.jpg)

Can be maybe better ? :
![good](https://cloud.githubusercontent.com/assets/7659927/7356653/f2911668-ed29-11e4-941b-da1c3a9bf751.jpg)

**Comment by usb248** [comment]
Moreover, i noticed that you have added a new theme. If we want put many text it's not very pretty...
![capture](https://cloud.githubusercontent.com/assets/7659927/8425614/cf247b9c-1f07-11e5-94d0-bd53fcf8ed4b.PNG)

when you think to do this ?

**Comment by craftpip** [comment]
Hello @usb248 Thanks for the suggestion,
I will implement this in the next release.

:)

**Comment by usb248** [comment]
Ok nice, Why we can't choice the width of alert/confirm/dialog other than by modifying CSS ?

**Comment by craftpip** [comment]
Yes i will be adding choice of width, 
https://github.com/craftpip/jquery-confirm/issues/27 
bootstrap columns will be provided to set the widths.

**Comment by usb248** [comment]
So, cool ! I wait your release ;).
An other improvement which can be very nice. Adding hash tracking by manupulating browser history (by adding #hash... ) like this similar plugin http://vodkabears.github.io/remodal/.

**Comment by craftpip** [comment]
Hello @usb248 The overflow feature you said is added in the new release,
Other feature about tracking with #hash, what is a practical usage with this?

Thanks

**Comment by usb248** [comment]
1. When we press back/next button (on some the mouse, or browser windows to navigate in the browser history), the alert/confirm/dialog come back
2. When we refresh the page, the alert/confirm/dialog don't disappear, it remains displayed.
