### ISSUE TITLE
Safari dialog height with dynamic content

### ISSUE THREAD

**Issue by drumichael611** [craftpip/jquery-confirm#133]
Even on the https://craftpip.github.io/jquery-confirm/ page, in safari the dialog with dynamic content doesn't increase the height in Safari.  

Is there a quick fix for this while waiting for a new release?

**Comment by Tallon1252** [comment]
I have the exact same problem. The dialog is getting the right height when resizing the window.

**Comment by craftpip** [comment]
Please see #78

**Comment by dvmobley** [comment]
I think this is related  #133
