### ISSUE TITLE
Change visibility ConfirmButton dynamiqually

### ISSUE THREAD

**Issue by sergefabre** [craftpip/jquery-confirm#134]
Hello, Sorry for my english, I am french....
 I want change the visibility of confirmButton when I cliqued on button in confirmbox 

thank

**Comment by dvmobley** [comment]
Won’t the confirm button disappear with the dialog when clicked?

Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…

**Comment by craftpip** [comment]
This is added in v3. 
```
var a = $.confirm({
    buttons: {
        ok: function(){}
    }
})
a.buttons.ok.disable();
```
