### ISSUE TITLE
Not able to attach the confirm event to un-rendered buttons in data table

### ISSUE THREAD

**Issue by mandarbt** [craftpip/jquery-confirm#135]
Hi,

I am using data table to show records and which can be deleted. I have used jquery.confirm for confirmation dialog. I am showing 10 rows in table for which confirmation works perfectly. But when pagination or sorting is done then for rest of the records confirmation is not working. I tried '.on' but it didn't work. After using '.on' i need to click delete button twice, which i want to avoid.

Can somebody help me on this? Below is my code.

Html code:

```
<thead>
    <tr>
        <th>Name</th>
        <th>FileType</th>
    </tr>
</thead>

<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.FileTypeName</td>
           <td>
                <button type="button" title="Update" class="glyphicon glyphicon-pencil" onclick="EditClick(this)"></button>
                <button type="button" value=@item.Id  title="Delete" class="confirm glyphicon glyphicon-trash" ></button>
                                    </td>
            <td style="display:none">@item.DriverId</td>
        </tr>
    }
</tbody>
```

</table>
Javascript code:
$(document).ready(function () {

```
$("#tableD").DataTable({
    ordering: false,
    sort: false,
    columnDefs: [{
        "defaultContent": "-",
        "targets": "_all"
    }]
});
```

})

$('.confirm').confirm({
        title: "Delete Confirmation",
        text: "Do you want to delete row?",
        confirm: function (button) {

```
         button.fadeOut(2000).fadeIn(2000);
        deleteItem(button.val(), "DeleteData") // Call delete method on confirmation
    },
    cancel: function (button) {
        button.fadeOut(2000).fadeIn(2000);

    },

    confirmButton: "Yes",
    cancelButton: "No",
    confirmButtonClass: "btn-default",
    cancelButtonClass: "btn-default"

});
```

Thanks in advance.

**Comment by dvmobley** [comment]
Using $document.on("click", ".button",function(){}); should do the trick.

Dale

Sent from my iPhone

On Aug 5, 2016, at 1:34 AM, mandarbt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am using data table to show records and which can be deleted. I have used jquery.confirm for confirmation dialog. I am showing 10 rows in table for which confirmation works perfectly. But when pagination or sorting is done then for rest of the records confirmation is not working. I tried '.on' but it didn't work. After using '.on' i need to click delete button twice, which i want to avoid.

Can somebody help me on this? Below is my code.

Html code:

<thead>
    <tr>
        <th>Name</th>
        <th>FileType</th>
    </tr>
</thead>

<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.FileTypeName</td>
           <td>
                <button type="button" title="Update" class="glyphicon glyphicon-pencil" onclick="EditClick(this)"></button>
                <button type="button" value=@item.Id<mailto:value=@item.id>  title="Delete" class="confirm glyphicon glyphicon-trash" ></button>
                                    </td>
            <td style="display:none">@item.DriverId</td>
        </tr>
    }
</tbody>


Javascript code:
$(document).ready(function () {

$("#tableD").DataTable({
    ordering: false,
    sort: false,
    columnDefs: [{
        "defaultContent": "-",
        "targets": "_all"
    }]
});


})

$('.confirm').confirm({
title: "Delete Confirmation",
text: "Do you want to delete row?",
confirm: function (button) {

         button.fadeOut(2000).fadeIn(2000);
        deleteItem(button.val(), "DeleteData") // Call delete method on confirmation
    },
    cancel: function (button) {
        button.fadeOut(2000).fadeIn(2000);

    },

    confirmButton: "Yes",
    cancelButton: "No",
    confirmButtonClass: "btn-default",
    cancelButtonClass: "btn-default"

});


Thanks in advance.
