### ISSUE TITLE
"The content function must return jquery promise." bug

### ISSUE THREAD

**Issue by caneroncel** [craftpip/jquery-confirm#136]
**Example 1:** 

```
 content: function(){
   return $.ajax({
       url : '/service/manager/smartermail/user/delete'
```

**Example 2:** 

```
content: function(){
   $.ajax({
       url : '/service/manager/smartermail/user/delete'
```

In a dynamic called tab content: 

When I use "**return**" (_Example 1_) ajax call runs **twice**:
[http://prntscr.com/c1wzul](http://prntscr.com/c1wzul)

Ajax works normally without "**return**" (_Example 2_), but with "**The content function must return jquery promise.**" error message. 

I think something wrong here.

**Comment by craftpip** [comment]
Can you please check with the latest version,
you need to return the ajax promise so that jconfirm knows when the event is done. 

I tried this the call was done once.
