### ISSUE TITLE
Any plan to handle iframe loading?

### ISSUE THREAD

**Issue by ahmadazimi** [craftpip/jquery-confirm#137]
Hi there,

Is there any plan to handle content loading via an iframe in future?

**Comment by dvmobley** [comment]
Yea that works now.

content: "<iframe src='url'></iframe>"

Sent from my iPhone

On Aug 9, 2016, at 11:23 PM, Ahmad Azimi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

Is there any plan to handle content loading via an iframe in future?
