### ISSUE TITLE
Loading div into dialog

### ISSUE THREAD

**Issue by quatsch** [craftpip/jquery-confirm#141]
Hi,

I've found many lightboxes allowing me to load an existing div into a lightbox, however I haven't found anything like yours capable of using bootstrap grid system to make the dialog box width responsive...

How would you advise over getting an existing div from my page (hidden by a parent div) into a dialog?

Cheers,

Yann

**Comment by craftpip** [comment]
you can do it like so,
```
var existingDivContent = $('.div').html();
$.confirm({
    content: existingDivContent
});
```
i hope this helps. 👍
