### ISSUE TITLE
got error "btoa is not defined" below IE10

### ISSUE THREAD

**Issue by coocier** [craftpip/jquery-confirm#143]
when I use the IE browser below IE10,I got an error 

> "btoa is not defined"

, I finaly found the reseaon in [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/WindowBase64/btoa), the **btoa** function is only support IE10+
![image](https://cloud.githubusercontent.com/assets/6789408/18118730/45ded912-6f89-11e6-92c1-2bff0c95277a.png)

well, then I replaced the **btoa** function by [base64-js's](https://github.com/beatgammit/base64-js) method (fromByteArray), it works fine in IE7~IE12  immediately!

but there is still one problem, when I set the **autoClose** option, it not closed automatically below IE8, and not show the count down seconds either, I can't find any reason because there's no error report

**Comment by coocier** [comment]
well, I find the reason!
there left an end tag in
`this.$cd = $('<span class="countdown">').appendTo(this['$' + opt[0] + 'Button']);`
should be 
`this.$cd = $('<span class="countdown"></span>').appendTo(this['$' + opt[0] + 'Button']);`

it works!!

**Comment by craftpip** [comment]
@coocier  this is fixed now. in v3. 
https://github.com/craftpip/jquery-confirm/blob/32fe2585bbdaf2ef47a5e0b450cf606d11acf3e9/js/jquery-confirm.js#L767
