### ISSUE TITLE
Close or destroy dialog box with remote button

### ISSUE THREAD

**Issue by DigItalWarrior69** [craftpip/jquery-confirm#144]
I want to know if is possible, and how, closing a dialog box by clicking a button in content called via eg.  content: 'url:page.php'.
page.php is in a subfolder inside same domain.
Is possible? How?
Thank you in advance

**Comment by craftpip** [comment]
It is possible, use the callback `onContentReady` and bind to click event of the your buttons.
later call this.close() and its done.
