### ISSUE TITLE
Uncaught ReferenceError: jc is not defined

### ISSUE THREAD

**Issue by gumpon** [craftpip/jquery-confirm#145]
i use jquery.confirm with facebok javascript sdk but it's error  "Uncaught ReferenceError: jc is not defined"

my code
$(function() {      

```
 var jc = $.dialog({
      title: ' login facebook',
      content: '<fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>'
      //autoClose: 'cancel|6000',
  });


});
```

  });
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      jc.close();
      profileAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

**Comment by craftpip** [comment]
This is caused when u access jc when it was not defined.
