### ISSUE TITLE
Using jquery-confirm as a standard Confirm dialog within script

### ISSUE THREAD

**Issue by TCardinal** [craftpip/jquery-confirm#146]
I've tried a few approaches but I can't get $.confirm to work as a replacement for Confirm. The code I am looking to use it in is:

if (confirm('do this?') == true) { do some shizzle here };

Replacing the confirm with $.confirm it doesn't work as I'd expect. If I place it within a $("#MyDiv").Click({...}) it doesn't fire until the process ends.

I think I must have missed something obvious here, so any pointers gratefully received.

**Comment by craftpip** [comment]
confirm is blocking, the execution of code is paused for it, unfortunately this cant be done via $.confirm
Have a look at #60 #79
