### ISSUE TITLE
onOpen callback is called before modal is rendered/inserted into DOM

### ISSUE THREAD

**Issue by rafistrauss** [craftpip/jquery-confirm#147]
Wanted to focus on an element inside the confirm dialog using the onOpen callback, but it would fail since the callback is called before the element is on the page

**Comment by inuyaksa** [comment]
I need too.
Because I have to init an input field with a jquery lib.
Please add "contentReady" callback.

**Comment by rafistrauss** [comment]
@inuyaksa It does look like this issue will be fixed in v3: https://github.com/craftpip/jquery-confirm/compare/v3

**Comment by craftpip** [comment]
a new callback is added `onContentReady` has suggested by @inuyaksa 
onContentReady is called after ajax is completed and rendered in DOM.
