### ISSUE TITLE
Event when content loads from a file

### ISSUE THREAD

**Issue by dkurlow** [craftpip/jquery-confirm#15]
I'd like to fill in controls that load from a file which contains the body html for the confirm dialog, but I'm not sure how to go about that. I tried var obj = $.confirm(...) and then used obj.$b.find("#chkUser").prop("checked", true); outside the definition of the dialog, but the checkbox was not checked . I know the buttons are disabled until the file loads. Is there an event (like 'confirm' and 'cancel') that fires when the content is loaded so I could set the values in that event?

David

**Comment by dkurlow** [comment]
I modified the jquery-confirm.js file I'd downloaded by adding a callback function "bodyLoaded" in the jconfirm.pluginDefaults section and calling it from the _buildHTML section right after the buttons are enabled after receiving body content from the $.get method. If this is worth adding to the project, I'd be glad to submit it, but I'm so new to gitHub that I'd probably need directions on how to do that!

David

**Comment by craftpip** [comment]
Hello David, Sorry for the late response, Glad you figured it out.
please commit your changes and create a pull request, much appreciated.

Thanks for pointing it out. :)
