### ISSUE TITLE
"Enter" for prompt

### ISSUE THREAD

**Issue by caneroncel** [craftpip/jquery-confirm#150]
Hello,

You can add "enter" key support for prompt dialogs:

![prompt](https://cloud.githubusercontent.com/assets/874310/18974116/d63b5efe-86a9-11e6-8399-e35baaf0d815.png)

Regards.

**Comment by ShashankRama** [comment]
Yes, you are right @caneroncel i am also trying to get this feature.
Every time i have to use mouse for this.

**Comment by dvmobley** [comment]
Why can't you attach a handler to the document on keydown/keyup events? I use similar functionality to monitor checkboxes.

**Comment by caneroncel** [comment]
@dvmobley I am already doing that but this must be a core feature for my mind.

**Comment by craftpip** [comment]
@caneroncel 
hello, you say to add event listener to the textbox? so when the user presses enter, a button should be triggered.

Currently please follow on what @dvmobley suggested, 

I've implemented the feature you need in v3, in which you can define keys for buttons like so,
```
{
    buttons: {
        aButton: {
            key: ['enter'],
            action: function(){
                // this will trigger when enter is pressed in the dialog.
            }
        }
    }
}
```

**Comment by craftpip** [comment]
This is now added in v3,
