### ISSUE TITLE
autofocus for input

### ISSUE THREAD

**Issue by ShashankRama** [craftpip/jquery-confirm#153]
Need input?, i have to use mouse to get focus inside confirm textbox
    content: '<input autofocus type="text" id="input-name" placeholder="Folder Name" class="form-control">'

autofocus not working...

**Comment by dvmobley** [comment]
Use the contentLoaded function. Add a timeout if your content loads slowly.


  1.  $.confirm({
  2.      content: 'url:text.txt',
  3.      title: 'Title',
  4.      contentLoaded: function(data, status, xhr){
  5.          var self = this;
  6.          setTimeout(function(){
  7.              self.input.focus();
  8.          }, 1000);
  9.      }
  10. });


Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…
