### ISSUE TITLE
Is there way to disable buttons?

### ISSUE THREAD

**Issue by ontelo** [craftpip/jquery-confirm#155]
In my use case, confirm button needs to be disabled until changes are made in the modal content.

contentLoaded: function() {
    this.$confirmButton.prop('disabled',true);
}

This didn't work. I think it has something to do with the fact that confirm / cancel buttons are disabled until the Ajax call is complete and contentLoaded is fired before that.

**Comment by craftpip** [comment]
> This didn't work. I think it has something to do with the fact that confirm / cancel buttons are disabled until the Ajax call is complete and contentLoaded is fired before that

That is right, gotta work around this to get control for the buttons.
I will add this.

**Comment by craftpip** [comment]
This feature is added now, as of v3, buttons are not disabled when ajax calls are made, 

you can disable the buttons like so,
`
$.confirm({
    buttons: {ok: function(){}},
    onContentReady: function(){
        this.buttons.ok.disable();
    }
})
`
