### ISSUE TITLE
How to change icon once content is loaded?

### ISSUE THREAD

**Issue by NachDDa** [craftpip/jquery-confirm#156]
I'm new to this plugin.

I'm trying to change the title's icon one the content is loaded (i'm working with the example for the "contentLoaded" option).
The thing is that the icon is not changed with the "setIcon" method. What should be inside that?
I currently have icon:"" but I'm just trying to make it work. Thanks!

![image](https://cloud.githubusercontent.com/assets/22352172/19356340/c7be08d0-916d-11e6-8007-a1ccb4b9e093.png)

**Comment by craftpip** [comment]
use the jquery reference for icon, do 
`self.$closeIcon.html('<i class="fa fa-check"></i>');`

I hope this helps
