### ISSUE TITLE
Prevent Close on Icon click not working

### ISSUE THREAD

**Issue by skworden** [craftpip/jquery-confirm#159]
if you return false on cancel 

`cancel: function () {          
    return false;
},`

to prevent the dialog from closing the close icon will still execute the close

starting at line 256 

`if (this.$closeButton) {
                this.$closeButton.click(function (e) {
                    e.preventDefault();
                    that._stopCountDown();
                    that.cancel();
                    that.onAction('close');
                    that.close();
                });
 }`

should remove the final that.close(); (line 262) to work as intended

`if (this.$closeButton) {
                this.$closeButton.click(function (e) {
                    e.preventDefault();
                    that._stopCountDown();
                    that.cancel();
                    that.onAction('close');
                });
            }`

**Comment by craftpip** [comment]
This is fixed in v3, it will be live in a few days now,
in the new version, closeIcon has its own function, and u can attach it to a button too. 
request you to be patient, Thanks!

**Comment by craftpip** [comment]
Fixed in v3.
