### ISSUE TITLE
contentLoaded documentation example

### ISSUE THREAD

**Issue by heckjp** [craftpip/jquery-confirm#160]
I need know how the contentLoaded callback works. At moment it's just saying if you load content by url in content option the callback should be by the option contentLoaded. But i found no example how to get this in callback session

**Comment by craftpip** [comment]
This is the code 
```js
 $.get(url).done(function (html) {
    that.content = html;
}).always(function (data, status, xhr) {
    if (typeof that.contentLoaded === 'function')
        that.contentLoaded(data, status, xhr);
});
```
get method is used to fetch the url, and then contentLoaded is called on always callback of $.ajax
the parameters are data, status, xhr object.
