### ISSUE TITLE
Position center screen

### ISSUE THREAD

**Issue by premhameed** [craftpip/jquery-confirm#162]
Hi,
My page height is around 2000px , every time when the dialog appearing on the screen it is not in the middle of screen. I need to scroll up to see the dialog content.

I am using a columnClass:'lightbox'  
.lightbox{
margin: 0 auto;
    width: 40%;
}

Please help me.

**Comment by craftpip** [comment]
columnClass has to be a bootstrap layout, i have not tested this with custom classes.
Is your page 2000px in width ?

**Comment by craftpip** [comment]
I tried this out, it seems to be working fine.

**Comment by premhameed** [comment]
Thanks For the help.
It was actually an issue with sharepoint.
