### ISSUE TITLE
Confirm buttons not working

### ISSUE THREAD

**Issue by jofftiquez** [craftpip/jquery-confirm#164]
I followed this sample from yout documentations [link](https://craftpip.github.io/jquery-confirm/#defining-buttons), which has two buttons `something` and `somethingElse` 

    $.confirm({
    buttons: {
        something: function(){
            // here the key 'something' will be used as the text.
            $.alert('You clicked on something.');
        },
        somethingElse: {
            text: 'Something else &*', // Some Non-Alphanumeric characters
            action: function(){
                $.alert('You clicked on something else');
            }
        }
    }
    });

but the event is not being triggered for `something` button neither on the `somethingElse` button.

**Comment by Lengchuan** [comment]
@jofftiquez  I cloned this project, and  used the project 's js and css ,there is no problem，i used js/jquery-confirm.js and css/jquery-confirm.css.

**Comment by craftpip** [comment]
@jofftiquez this is strange, because the dist files are the same but minified, 
can u please give me errors that pop up in the console ?

**Comment by jofftiquez** [comment]
@craftpip actually the weird part is there are no errors on the console. :-/ Even the demo itself on the documentation does not work. Ill look at it again.

**Comment by jofftiquez** [comment]
@craftpip I just tested now this link [here](http://craftpip.github.io/jquery-confirm/#buttons) under the 'Text' part when I click the `something` or `something else` button, both events were not fired at all.

**Comment by craftpip** [comment]
Im sorry, the demo code for for 'Text' part is missing the callbacks. the js code doesn't have any problem

you can see it here.
https://github.com/craftpip/jquery-confirm/blob/b45696f7e71b66e9e5b4eea1205f16145460aaf2/index.html#L1091

**Comment by jofftiquez** [comment]
Oh my... @craftpip thanks
