### ISSUE TITLE
Action outcomes changed to ok?

### ISSUE THREAD

**Issue by dvmobley** [craftpip/jquery-confirm#165]
It appears that new version has different outcomes for the onAction callback. Not sure if this was intentional or not.

**Comment by craftpip** [comment]
this was intentional, the default button name for okay is changed to ok.

this can be set the default buttons in options.
```
jconfirm.defaults = {
defaultButtons: {
            okay: { 
                action: function () {
                }
            },
            close: {
                action: function () {
                }
            },
        },
}
```
There are a ton of changes in v3,
