### ISSUE TITLE
This plugin is not working in older browser for chrome and mozilla

### ISSUE THREAD

**Issue by sampathambidi** [craftpip/jquery-confirm#166]
Try to tell what the problem and send me documentation for browser version compatability.

**Comment by craftpip** [comment]
Which browser versions have you tried ?

**Comment by sampathambidi** [comment]
Chrome 28 version

**Comment by craftpip** [comment]
I've tested it in chrome 28, it works in it, jquery defer doesn't seem to work properly in it.
