### ISSUE TITLE
Halt script until confirm/alert is closed

### ISSUE THREAD

**Issue by pheroh** [craftpip/jquery-confirm#167]
I have a vague idea that not being able to do it directly because only the native js alert and confirm can do that. Nonetheless, is there anyway to emulate something similar to their behavior?

I have an onclick event attached to a `<a>` that does various checks and confirms (native for now that I want to change to $.confirm) before submitting a form.  These checks will return a false if they fail preventing the submission of the form.

If I put `return false` in my cancel button action, it doesn't close the dialog and does nothing obviously, which is undesirable.

Example:

```
$('#save_return').on('click', function() {
        if (date_val.length == 0 || time_val.length == 0) {
           var conf = false;
            $.confirm({
                title: 'Warning',
                content: "Text",
                buttons: {
                    confirm: function () {
                        conf = true;
                    },
                    cancel: function () {
                        conf = false;
                    }
                }
            });

            //var conf = confirm("Text?");

            if (!conf)
                return false;
        }

        // MORE CHECKS

        $('#trip_return').submit();
    });
```

The above obviously doesn't work.

**Comment by craftpip** [comment]
There is no way to emulate the working of a native confirm, $.confirm cannot halt execution.
instead you should use callbacks. If you have a lot of callbacks, i would recommend to use [promises](https://api.jquery.com/jquery.deferred/), 

So the above example becomes , 
```
$('#save_return').on('click', function() {
        if (date_val.length == 0 || time_val.length == 0) {
            $.confirm({
                title: 'Warning',
                content: "Text",
                buttons: {
                    confirm: function () {
                        moreChecks();
                    },
                    cancel: function () {
                        // do nothing. close the modal.
                    }
                }
            }
        });
    }
});

var moreChecks = function(){
    // more checks
    $('#trip_return').submit();
}
```

check other related issues:  #79 #60 #36

**Comment by pheroh** [comment]
Thanks
