### ISSUE TITLE
Not center in Bootstrap v4 

### ISSUE THREAD

**Issue by GeniusWiki** [craftpip/jquery-confirm#168]
Although Bootstrap v4 not formal released, its offset class change to  offset-md-3 format, without that "col-" prefix.  This cause jquery-confirm not align in the center of window.

**Comment by GeniusWiki** [comment]
Put customised columnClass option, fixed my issue. But guess my report is still worth a penny:). Thanks for your great library!

{
columnClass: 'col-md-4 offset-md-4',
}

**Comment by craftpip** [comment]
Thanks for the report @GeniusWiki , 
Its worth adding docs about supporting bootstrap v4.
