### ISSUE TITLE
settings using the data attributs

### ISSUE THREAD

**Issue by dalios** [craftpip/jquery-confirm#171]
I have 3 demandes :

1. remove the "console.log(that._lastFocused);" on line 961 : this poluate the console log.
2. add settings using the data attributs (for all options and not only for title and content).
3. add settings using a global data with json options :
exp : `<button data-jquery-confirm="{'title': 'alert', 'content': 'Lorem upsum', 'type': 'red'}>"`

nice work 👍

**Comment by dvmobley** [comment]
Demands?!? You’re paying for this product?!?

Dale Mobley
IT Administrator
UTC Housing
O – 423.425.5908

Solving Problems One at A Time…

**Comment by dalios** [comment]
It's a suggestions...  It was a wish to have more flexibility for your plugin and not really demand.

**Comment by Robys915** [comment]
This is how I did it with data attributes 

My Element 
----------------
`<a href="#my-modal" class="btn-dialog" data-column="col-md-6 col-md-offset-3" data-title="I'm the Modal" data-dismis="false" data-theme="material"> Launch Modal </a>`

Modal Container
-------------------
`< div class="hidden" id="my-modal" title="My alt title" data-column="col-md-5 col-md-offset-2">
I'm the modal 
</ div>`

My Script 
-------------
`$(".btn-dialog").on("click", function (e) {
            e.preventDefault();
            $(this).ajaxGet(this);  });`

`
       
           $.fn.ajaxGet = function (elm) {

            var url = $(elm).attr('href') || $(elm).data('url'); // use url or data-url attribute

            var title = $(elm).attr('title') || $(elm).data('title'); // use data-title or title attribute

            var content;

            var columns = $(elm).data('column'); // Modal width

            if (elm.hash && elm.hash.length > 0) {

                if (!title) {

                    title = $(elm.hash).attr('title') || ''; // You can set title to the modal container itself
                }

                if($(elm.hash).data('column')) {

                    columns = $(elm.hash).data('column'); // Columns can go to the container to
                }

                content = $(elm.hash).html();

            } else {

                content = function () {
                    var self = this;
                    return $.ajax({
                        url: url,
                        dataType: 'json',
                        method: 'get'

                    }).done(function (response) {

                        self.setContent(response.view); // View content from the server 

                        self.setTitle(response.title, true); // Title of my modal

                    }).fail(function (xhr, textStatus, error) {

                        if (xhr.status == 404) {

                            return self.setContent('<h5> Page not Found .</h5> <p>  Sorry! The page could not be found </p>');
                        }
                    });
                };
            }


            var js = $.dialog({
                theme: $(elm).data('theme'),
                title: title || false,
                animationBounce: $(elm).data('bounce') || 1.2,
                animationSpeed: $(elm).data('speed') || 300,
                confirmKeys: [13], // ENTER key
                cancelKeys: [27], // ESC key
                animation: $(elm).data('animation') || 'scale',
                container: $(elm).data('container') || '.wrapper',
                closeAnimation: $(elm).data('animation-close') || 'scale',
                columnClass: columns || 'col-md-4 col-md-offset-4',
                backgroundDismiss: $(elm).data('dismiss') ? false : true,
                content: content,
                onContentReady: function () {

                    self.$content.find('.ms-close').click(function (e) {

                        self.close();
                    });


                },

                contentLoaded: function (data, status, xhr) {

                },

                onOpenBefore: function () {


                },
                onOpen: function () {


                },
                onClose: function () {

                },
                onDestroy: function () {

                },
            });
        };
`

**Comment by craftpip** [comment]
For the data attributes, i will suggest to write a wrapper like @Robys915 suggested.
