### ISSUE TITLE
contentLoaded can not use ul tag ?

### ISSUE THREAD

**Issue by h819** [craftpip/jquery-confirm#173]
Ajax complete callback contentLoaded
https://craftpip.github.io/jquery-confirm/#content-loaded

$.confirm({
    content: 'url:text.txt',
    contentLoaded: function(data, status, xhr){
        // data is already set in content
        this.setContentAppend('<br>Status: ' + status);
    }
});

When my text.txt file has ul tag :
```
<ul class="list-unstyled spaced2">
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> ace admin </li>
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> <code> menu-icon fa fa-sitemap </code></li>
</ul>
```

the a append content can not appear.
'<br>Status: ' + status

**Comment by craftpip** [comment]
Your html data will be in the `data` variable, you're trying to append the status of the call

**Comment by h819** [comment]
```
<ul class="list-unstyled spaced2">
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> ace admin </li>
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> <code> menu-icon fa fa-sitemap </code></li></ul>

or

<div>
<ul class="list-unstyled spaced2">
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> ace admin </li>
    <li> <i class="ace-icon fa fa-check bigger-110 green"></i> <code> menu-icon fa fa-sitemap </code></li></ul>
</div?
```
can not append
```
<div class="form-group">
    <label>input : </label>
    <input autofocus type="text" id="input-css" placeholder="CSS" class="form-control">
</div>
```
can append.

**Comment by craftpip** [comment]
There is no different logic for treating the `ul` element, 
can you please create a fiddle for this?
