### ISSUE TITLE
How to set top position?

### ISSUE THREAD

**Issue by waiantarai** [craftpip/jquery-confirm#174]
How to set top position?

**Comment by waiantarai** [comment]
I want set position dialog display not center of page. I like set position same as modal fade of bootstrap. I can do it?

**Comment by craftpip** [comment]
This option is currently not available. 
last resort will be to edit this line 
https://github.com/craftpip/jquery-confirm/blob/master/js/jquery-confirm.js#L926
Enter your margin-top and it'll be good.
