### ISSUE TITLE
Jquery UI dialog help

### ISSUE THREAD

**Issue by tesc0** [craftpip/jquery-confirm#175]
Hello!
I'm using your plugin in a system that is built on/around the dialog widget of jQuery UI. If I click on the X icon to close dialog, I want to get an confirm popup. 

By clicking "totally", both "test" and "close" get printed to console, but the dialog doesn't close. Could you shed some light why this doesn't work? Thank you!

````
$("#buyerDetailsWin").prev().find("a.ui-dialog-titlebar-close").on("click",function(e) {
        if($('#buyerDetailsWin #new_alert_open').val() == 1) {

            e.preventDefault();
            e.stopPropagation();
            console.log("test");

            $.confirm({
                title: 'Are you sure?',
                content: 'Do you want to close the window?',
                boxWidth: '30%',
                useBootstrap: false,
                type: 'orange',
                buttons: {
                    Totally: function () {
                        console.log("close");
                        $("#buyerDetailsWin").dialog("close");
                    },
                    Cancel: function () {

                    }
                }
            });
        }
    });`

//dialog is initiated on pageload.)

**Comment by dvmobley** [comment]
Seems that you would just return false in the onClose event.

Dale

Sent from my iPhone

On Dec 1, 2016, at 5:21 PM, tesc0 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!
I'm using your plugin in a system that is built on/around the dialog widget of jQuery UI. If I click on the X icon to close dialog, I want to get an confirm popup.

$("#buyerDetailsWin").prev().find("a.ui-dialog-titlebar-close").on("click",function(e) {
        if($('#buyerDetailsWin #new_alert_open').val() == 1) {

            e.preventDefault();
            e.stopPropagation();
            console.log("test");

            $.confirm({
                title: 'Are you sure?',
                content: 'Do you want to close the window?',
                boxWidth: '30%',
                useBootstrap: false,
                type: 'orange',
                buttons: {
                    Totally: function () {
                        console.log("close");
                        $("#buyerDetailsWin").dialog("close");
                    },
                    Cancel: function () {

                    }
                }
            });
        }
    });`

(The dialog is initiated on pageload.)

By clicking "totally", both "test" and "close" get printed to console, but the dialog doesn't close. Could you shed some light why this doesn't work? Thank you!

**Comment by craftpip** [comment]
to prevent close in jquery-confirm just do a `return false`

**Comment by tesc0** [comment]
Okay, I think I have figured it out, I have put some extra preventdefault and return false in the close event of jqueryui dialog. It is working now. Thank you anyway!
