### ISSUE TITLE
Confirm "window" is rendered at bottom of the page

### ISSUE THREAD

**Issue by InsanelyOne** [craftpip/jquery-confirm#176]
I'm trying to display a confirmation dialog but it ends up just getting appended to the end of the page instead of rendering as a modal window.  This is an ASP.NET MVC project using bootstrap 3.3.7 and jquery 1.10.2.  Thoughts anyone? 

The code is super simple.  I just discovered this plugin and was attempting to test it out:
```
$.confirm({
    title: "Confirm!",
    content: "Are you sure you want to delete this note?",
    confirm: function () {
        alert("confirm");
    },
    cancel: function () {
        alert("cancel");
    }
});
```

I'm not seeing any errors in the browser console.

![screen shot 2016-12-03 at 10 38 28 am](https://cloud.githubusercontent.com/assets/24356668/20860379/b48991a4-b944-11e6-97be-d9d625084e2c.png)

**Comment by craftpip** [comment]
This may happen if the height of the body is huge, check for the parents of the jcomfirm popup's div
can you please make a fiddle of this ?

**Comment by craftpip** [comment]
also, the width seems off considering that you're using bootstrap.
i highly doubt that the styles are overwritten for the confirm box, please check that
