### ISSUE TITLE
Scroll bar issue 

### ISSUE THREAD

**Issue by abdulwahabplus** [craftpip/jquery-confirm#178]
While closing confirm popup its scrolling up the window.

`$.confirm({
                            title: "Invalid",
                            content: "Parameter already exist",
                            autoClose: "Close|5000",
                            columnClass: "small",
                            type: "red",
                            closeIcon: true,
                            buttons: {
                                Close: function () {
                                }
                            }
                        });`

**Comment by abdulwahabplus** [comment]
I commented the below code from **close** function and it did it.

`scrollTop: (ot - Math.round((wh / 3)))`

**Comment by craftpip** [comment]
On which browser did this happen?

**Comment by abdulwahabplus** [comment]
Google chrome  (latest version)
