### ISSUE TITLE
opening confirm from within iframe

### ISSUE THREAD

**Issue by eytanchen** [craftpip/jquery-confirm#179]
Hi - I am using confirm with the supervan theme, which is wonderful and covers the entire screen. However, I am wondering if there is any way to trigger it from a iframe (within a modal) on the parent main screen, so it will still cover the whole screen instead of only the iframe.

Thanks in advance

**Comment by craftpip** [comment]
Hello @eytanchen 
You want to open the model in the parent window, and trigger it from the iframe,
here is a quick search http://stackoverflow.com/questions/32328679/how-to-pass-a-value-from-iframe-to-the-parent

you have to post a message to the parent window, and the parent window should listen to it, and open the jconfirm model
