### ISSUE TITLE
How to handle when enter key is pressed?

### ISSUE THREAD

**Issue by josh401** [craftpip/jquery-confirm#180]
Hi, 

First, amazing!!  Simple, lightweight, flexible and well documented.  Thank you for the very hard work in creating this awesome plugin.

Question:  How to handle the user pressing "Enter" on the keyboard?  My use-case is the user will input data into a single form field inside the dialog; and upon pressing "Enter", it will submit the "Okay" button.

Thank you.

**Comment by craftpip** [comment]
@josh401 I'm glad you liked the work,

This is the documentation for keys,
http://craftpip.github.io/jquery-confirm/#button_keys
You have to define set of keys in array, 

```
buttons: {
        specialKey: {
            text: 'Enter',
            keys: ['enter'], // this button will be trigged when enter is pressed.
            action: function(){
                $.alert('Enter was pressed');
            }
        },
```

In your use-case, you're using a input elements,
The default behavior for pressing enter when focused in an input element is to submit the form, 
This is why, to prevent unexpected stuff, "space and enter" keys are disabled when inputs are focused.

**Comment by josh401** [comment]
AHHH... don't know how I missed that.  Wow; this plugin simply has it all.  I love the new alert styles too (success, error, etc).  Makes my life easier; thank you!

I have used this in  quite a few projects (perhaps 20).  From handling simple button click messages; to full-fledged ajax responses from the server.  This plugin just WORKS; no matter what I throw it's way.

You deserve a donation!  If you prefer not to add it here; please use my contact form on http://joshlobe.com to send me the link.

Lastly, I have one small question/suggestion.  I have had a few clients who wanted fixed height overlays.  Imagine a long overlay (such as a privacy policy or terms and conditions) that may be 2000px in height.  They want it fixed to perhaps 300px tall with a scrollbar; BUT, with the action buttons fixed to the bottom of the overlay.  So as they scroll the "long" content; the action buttons are always visible.

I have accomplished it with some custom css; but I imagine I am not the only one who would find this additional option VERY useful.

Man; I wish you the best.  A great developer, making great community software, that is fully documented, AND you are very responsive to your support forum... a rare find these days!!

- Josh

**Comment by craftpip** [comment]
Hello josh
I'm super glad you liked my work, a big thanks for using it. 👍 
The fixed height thing was in my list, will be working on it soon.

Thanks a ton !

**Comment by spmsupun** [comment]
hello @craftpip,  is there anyway to enable 'enter' button when a input box is focus ?
