### ISSUE TITLE
Could a detailed example of a prompt be added to the docs?

### ISSUE THREAD

**Issue by ewardjr** [craftpip/jquery-confirm#184]
I am really interested in seeing how the prompt with some input works and was wondering if a more detailed example could be added to the docs.

**Comment by craftpip** [comment]
alright, this can be done, how exactly do you want the docs to be arranged, 
can you please give me some ideas.

**Comment by ewardjr** [comment]
I am really interested in exploring the use of the prompt to replace a pop window technique we are currently using.  This would ensure that all of our alerts, confirms and prompts would have a similar appear appearance.  So if the docs could show me how to create a prompt and what options I may use with it. Say for example I need to request an information for an address change or email, we could use a prompt for that and validate that an email was entered.

Does this help in anyway?

Thank you,

Elliott Ward | Software Engineer | Primary Solutions
elliott.ward@primarysolutions.net<mailto:elliott.ward@primarysolutions.net> | P: 614.430.0355 ext. 221
Web: www.primarysolutions.net<http://www.primarysolutions.net/>
[cid:image001.jpg@01D1CC65.2407CFF0][http://www.gilfordhouseofpizza.com/images/fb-like-button.png]<https://www.facebook.com/PrimarySolutionsInc/>

**Comment by craftpip** [comment]
yes, this is helpful,
I will be implementing this in the docs in later days, 
but here is how its done

```
$.confirm({
    content: '-your form html goes here-',
    onContentReady: function(){
        // this will be called once the popup is ready, so you can bind events to your forms
        this.$content.find('.element').on('click', fn) // bind to element
        this.$content.find('.form').on('submit', fn) // bind to form
    },
    buttons: {
        buttonName: function(){
            var thisModel = this;
            // stuff to do with the form, submit to ajax maybe
            // if u submit to ajax, do return false, that will prevent the model from closing
            // later when the ajax is complete, call `thisModel.close()` to close the model
        }
    }
})
```
Prompt is just form in the model,
