### ISSUE TITLE
Iframe in dialog

### ISSUE THREAD

**Issue by eytanchen** [craftpip/jquery-confirm#186]
Is there a way to load the ajax into an iframe inside the dialog?

**Comment by dvmobley** [comment]
Yes, just surround content with iframe tag. If you do Ajax call first and in contentLoaded callback call confirm with content as return data, it works a little smoother.

Dale

Sent from my iPhone

On Dec 17, 2016, at 12:14 PM, Eytan Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a way to load the ajax into an iframe inside the dialog?

**Comment by craftpip** [comment]
I must add a iframe example in the docs,
