### ISSUE TITLE
custom dialogue type

### ISSUE THREAD

**Issue by whimsicaldreamer** [craftpip/jquery-confirm#187]
How can we have custom dialogue type?

**Comment by dvmobley** [comment]
You make your own? 😂

Dale

Sent from my iPhone

On Dec 20, 2016, at 3:18 PM, Ayan Dey <notifications@github.com<mailto:notifications@github.com>> wrote:


How can we have custom dialogue type?

**Comment by craftpip** [comment]
You can now create custom types

CSS  
```CSS
.jconfirm-type-myCustomType{
 // fancy styles
}
```
JS  
```JS
$.confirm({
    type: 'myCustomType'
})
```

👍
