### ISSUE TITLE
jconfirm.defaults not working on 3.0.1

### ISSUE THREAD

**Issue by padin33** [craftpip/jquery-confirm#189]
Hi everyone!

First of all my congrats to de creators of this fabulous library!

I have an application wich has a lot of j.confirms an j.alert boxes, loading jconfirm 2.5
On a new update i want to show a confirm box with 3 button, so i have downloaded the 3.0.1 version that implements that  upgrade.

My problem is that in 2.5 version i had a jconfirm.defaults for all jconfirm boxes, but in 3.0.1 version this feature is not working. 

How can i resolve this issue?

Thanks a lot

**Comment by craftpip** [comment]
the way you define buttons has changed in v2 and v3, you will have to
change the jconfirm.defaults
please post your jconfirm.defaults here so i can look into it better.


Regards,
Boniface Pereira
+91 7798-388-599
hey@craftpip.com

**Comment by HackedBeat** [comment]
I reaffirm that jconfirm.defaults not working in version 3.0.1. 

Temporary solution: 

- Use **jconfirm.pluginDefaults** instead _jconfirm.defaults_

OR

- Add a line to the top of the code: 
**jconfirm.defaults = jconfirm.pluginDefaults;**

**Comment by craftpip** [comment]
Thanks for noting this issue, 
I've fixed this in 3.0.3
