### ISSUE TITLE
Trobles with jquery confirm and php.

### ISSUE THREAD

**Issue by jagrival** [craftpip/jquery-confirm#192]
When I include a confirm dialog in my script produced an error in server side but in a php call produce a "500 Internal Server Error " with a follows insues:
﻿
00jquery.js:10254 POST http://administrar.webcindario.com/00ConexionPhp/09VerificaCedula.php 500 (Internal Server Error)
send	@	00jquery.js:10254
ajax	@	00jquery.js:9738
jQuery.(anonymous function)	@	00jquery.js:9890
(anonymous)	@	01Functions.js:686
dispatch	@	00jquery.js:5226
elemData.handle	@	00jquery.js:4878
21jquery-confirm.js:961 
jQuery.fn.init[0]
context
:
document
length
:
0
prevObject
:
jQuery.fn.init[1]
selector
:
"body :focus"
__proto__
:
Object[0]

I hope had any solutios for this...

**Comment by craftpip** [comment]
jquery confirm is a client side script, which has nothing to do with your php code. 
please check your php code on how are you rendering the script.

**Comment by jagrival** [comment]
You right! I discovered that the problem is jQuery plug in Its last realease.

I'll try to change jQuery to another version, older one even if it is... I'll see if it works.

Thanks for your answer.

Obtener Outlook para Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 3:44 AM -0500, "Boniface Pereira" <notifications@github.com<mailto:notifications@github.com>> wrote:


jquery confirm is a client side script, which has nothing to do with your php code.
please check your php code on how are you rendering the script.

**Comment by jagrival** [comment]
Finally the problem was php (just a letter in the last statement line) as you said... I last a lot of time to find it.

May be try again later with confirm plug...

Thanks again for your comments.

Obtener Outlook para Android<https://aka.ms/ghei36>



On Sat, Jan 14, 2017 at 10:27 AM -0500, "Boniface Pereira" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #192<https://github.com/craftpip/jquery-confirm/issues/192>.

**Comment by craftpip** [comment]
You're welcome 👍
