### ISSUE TITLE
jc 3.0.1 - Api jc.setTitle doesn't work using Ajax promise

### ISSUE THREAD

**Issue by amlette** [craftpip/jquery-confirm#196]
Hello,

In your exemple for "[Using Ajax promise](https://craftpip.github.io/jquery-confirm/#ajaxloading)", the jc.setTitle do not works.

Here my tests ($.confirm) :
- in the content function .setTitle() works correctly.
- in the .done function .setTitle doesn't work (title still "Hello")
- if the title is set in params, it still

Thank you for your help.

**Comment by craftpip** [comment]
Thanks for noting this, 
its confirmed setTitle does not work when using ajax content loading.
i will work on this soon
