### ISSUE TITLE
jquery.confirm.min.js has console messages

### ISSUE THREAD

**Issue by ozziest** [craftpip/jquery-confirm#197]
I have installed the library with using bower. But there are log messages on console when I open a dialog. Is it normal? Can I disable it?

![image](https://cloud.githubusercontent.com/assets/2325140/21954441/51410326-da59-11e6-9c2d-c01276e91e60.png)

This is the line which shows message;

```js
console.log(that._lastFocused);
```

**Comment by craftpip** [comment]
This is to be removed in the next version, this was a debug message.

**Comment by craftpip** [comment]
I've removed the console message in the v3.0.3 now.

**Comment by ozziest** [comment]
Thank you very much. I appreciate. 👍
