### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by HamedFathi** [craftpip/jquery-confirm#198]
Thanks for your awesome library

Can you provide typescript definition file for latest version ? (jquery-confirm-3.0.x.d.ts)

**Comment by craftpip** [comment]
Hello @HamedFathi 

can you please give me some references to definitions files,
as an example.
PS i've not worked with typescript definition files

**Comment by HamedFathi** [comment]
@craftpip 

Hi

**Some References** 

[https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)
[https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html)
[http://mudbath.com.au/blog/create-typescript-definitions-from-existing-javascript-libraries](http://mudbath.com.au/blog/create-typescript-definitions-from-existing-javascript-libraries)
[https://www.stevefenton.co.uk/2013/01/complex-typescript-definitions-made-easy/](https://www.stevefenton.co.uk/2013/01/complex-typescript-definitions-made-easy/)
[http://blog.wolksoftware.com/contributing-to-definitelytyped](http://blog.wolksoftware.com/contributing-to-definitelytyped)
[http://peter.grman.at/how-to-write-typescript-definition-files/](http://peter.grman.at/how-to-write-typescript-definition-files/)

Thanks

**Comment by harley5303** [comment]
Is a typescript definition file available now?
