### ISSUE TITLE
Change colours of default buttons

### ISSUE THREAD

**Issue by heastost** [craftpip/jquery-confirm#199]
First of all, great plugin! It's a real life saver. 👍 
I have read the docs, but haven't found any answers there, neither have I found anyone else asking the following questions:
Is there any way to change the colours of the confirm and cancel buttons of the built-in buttons? (snippet below):
        buttons: {
        	confirm: function () {
        	},
        	cancel: function () {
                }
        }
I've attempted to change the classes of the buttons (using bootstrap classes), but applying button classes on the default confirm and cancel buttons do not seem to work. Also, setting classes to the default buttons "ok" and "close" in the jconfirm.defaults would be nice to be able to do too.
I've tried to do it with the following snippet, but it wont work:
defaultButtons: {
  ok: {
      btnClass: 'btn-success',
      action: function () {
      }
  },
  close: {
      btnClass: 'btn-info',
      action: function () {
      }
  },
},

I apologize in advance in case I've missed out on something really obvious.

**Comment by craftpip** [comment]
The 'defaultButtons' is used only when buttons are not defined.
If you want to change the colors of the buttons, please define a new class, or change the CSS of the existing classes, 
for example 
```css
.btn-success{
background: red !important;
}
```

**Comment by heastost** [comment]
You misunderstood my question.
What I want to do is to change the color of the default buttons "Confirm" and "Cancel", as well as "ok" and "close". Not all at once, but lets say I want the "Confirm"-button to be green and the "Cancel"-button to be red (same thing with "ok" and "close").

**Comment by craftpip** [comment]
okay i get it now.
sorry, setting default button classes is not available. and is not possible, because the buttons are dynamic.
you'll have to manually set each button's class for colors.

**Comment by heastost** [comment]
Ok, thank you for taking your time to answer my question. Great job so far anyway. :)

**Comment by mt11i** [comment]
is there any way to set focus in specific button,
Ex :  i have 2 button one is ok and another one is cancel i want to set focus on ok by default 
thanks for awesome work
