### ISSUE TITLE
Title's icon must be re-style in RTL mode

### ISSUE THREAD

**Issue by dehghani-mehdi** [craftpip/jquery-confirm#201]
Hi man,

Thanks again for plugin, just updated my codes to using v3.x, really nice!

In `rtl` mode, you need to change `margin-right` to `margin-left`, also `margin-right` set to `0`, as I shown below:

    .jconfirm.jconfirm-rtl .jconfirm-box div.jconfirm-title-c .jconfirm-icon-c {
	    margin-left: 8px;
	    margin-right: 0;
    }

Thank you !
Mehdi

**Comment by craftpip** [comment]
hello @dehghani-mehdi 
Fixing this asap. Sorry for being this late at this issue.

**Comment by dehghani-mehdi** [comment]
@craftpip don't worry, will be great, looking fwd to fixed version.

**Comment by craftpip** [comment]
Released the fixed version 👍
