### ISSUE TITLE
jConfirm triggered from bootstrap modal cannot get focus

### ISSUE THREAD

**Issue by pda-code** [craftpip/jquery-confirm#202]
- When i open a jconfirm dialog with content=<textarea/> triggered  from a button in a bootstrap modal
textarea cannot get focus or click in it.

Also when i press TAB to move focus, focus is moving around controls of the bootstrap modal and never reaches jconfirm dialog textarea or buttons

![image](https://cloud.githubusercontent.com/assets/10973438/22163666/6bb6bb8a-df5c-11e6-8a66-b7971febf6e7.png)

**Comment by craftpip** [comment]
This happens because of the tabindex attribute in the bootstrap model, 
please try removing the tabindex attr to see if it solves the problem

**Comment by zhbzhbzhbz** [comment]
“removing the tabindex attr” is the right answer!!! I have wasted hours on this.
