### ISSUE TITLE
Close all dialog

### ISSUE THREAD

**Issue by nozreh** [craftpip/jquery-confirm#203]
Hi, I want to know if there is an option or an api to close all open dialog?
I have a scenario that i need to close everything else regardless the user click on any button.
Thanks for the help

**Comment by craftpip** [comment]
all instances that are opened are stored in `jconfirm.instances` array.
you can for loop this array to find open models and close them.

**Comment by nozreh** [comment]
Thanks for the info craftpip

**Comment by craftpip** [comment]
Hello @nozreh in the new update, the instances array will only have jconfirm objects that are open.
once closed will be removed from the array.
