### ISSUE TITLE
Trouble with If/Else statement

### ISSUE THREAD

**Issue by mdearaujo** [craftpip/jquery-confirm#206]
I am currently working on a project where I am using the confirm box on a form. I'm using required attributes for several input and textarea elements. Ideally, I would like the workflow to go like this:

User can't submit form unless all fields have values.
If all fields have values, and user clicks submit, a confirmation box is displayed.
Hitting yes in confirmation box will submit the form / hitting no will return to the form

The issue I keep running into is that when all fields have values and I hit submit, I can see that it does show the confirmation box but only for a split second as the form submits too fast.

Any help would be greatly appreciated. Here is my code:

var isValid = false;
	
	if (( $.trim( $('.monthlyamount').val() ) !== '' ) && ( $.trim( $('.monthlyterms1').val() ) !== '' ) && ( $.trim( $('.monthlyterms2').val() ) !== '' ) && ( $.trim( $('.enddate').val() ) !== '' ) && ( $.trim( $('.apr').val() ) !== '' )){
		isValid = true;
	}
	else {
		isValid = false;
	}
	
	$('.editConfirm').on('click', function () {
		if (!isValid){
			//do nothing
		}
		else {
			$.confirm({
    			        title: 'Edit Confirmation',
    			        content: 'Are you sure you wish to submit these edits?',
				bgOpacity: 0.4,
    			        buttons: {
        			        confirm: {
						btnClass: 'confirmSubmit',
						action: function () {
            				               $("#editForm")[0].submit();
        				        },
					},
        			        cancel: {
						btnClass: 'confirmOk',
						action: function () {
            				                //close
        				        },
    				       },
				},
			});
			return false;
		}
	});

**Comment by craftpip** [comment]
First of all, apologies for the late answer, 
once the form is submitted, check for if the form is invalid and `e.preventDefault` so that the form is not submitted further
