### ISSUE TITLE
ajax call not working after button click

### ISSUE THREAD

**Issue by auset1881** [craftpip/jquery-confirm#209]
My confirmation has yes and no buttons.  I want to execute an ajax response for Yes and do nothing on No.  Currently nothing happens with the Yes button.  I've confirmed that it's executing the code in the Yes function through alerts.  I also tried using onAction with no success.
My jquery code is in a separate .js file and I'm using MVC.  The url calls an action in the controller.

```
function Audit() {
    event.preventDefault();

    $.confirm({
        title: 'Audit',
        content: 'Do you want to give all items the same note?',
        buttons: {
            Yes: function () {
               return $.ajax({
                    url: '/Application/Audit',
                    data: {
                        'envId': environment,
                        'servTypeId': serverType,
                        'servId': server
                    }
                });
            },
            No: function () {
                return false;}
        },
        onAction: function (Yes) {
            $.ajax({
                url: '/Application/Audit',
                data: {
                    'envId': environment,
                    'servTypeId': serverType,
                    'servId': server
                }
            });
        }
    })
}
```
How can I get the confirm to execute the ajax call?

**Comment by craftpip** [comment]
You're firing the ajax call twice here, 
The first one inside the button object should work,
please create a jsfiddle for the issue
