### ISSUE TITLE
Jconfirm with datepicker

### ISSUE THREAD

**Issue by nizarhdt** [craftpip/jquery-confirm#212]
I have been using jconfirm for my web application, i have problem when i used datepicker to the content of jconfirm. the datepicker showing behind it. i've been use z-index but it is not working.
is there a bug or something? Here is my code and preview. Thanks

`$.confirm({`
`					title: 'Resign ABK '+doc,`
`					  type: 'red',`
`					 content: '' +`
`					 '<form action="../resignabk" class="formresign" method="post">' +`
`					 '<div class="form-group">' +`
`					 '<input type="hidden" name="idabk" value="'+doc+'">' +`
`					 '<label>Tanggal Resign</label>' +`
`					 '<input type="text" class="form-control" name="tglresign" id="tglresign">' +`
`					 '</div>' +`
`					 '<div class="form-group">' +`
`					 '<label>Isikan alasan Resign ABK tersebut</label>' +`
`					 '<textarea class="alasanresign form-control" name="alasan"></textarea>' +`
`					 '</div>' +`
`					 '</form>',`
`					 buttons: {`
`						 formSubmit: {`
`							 text: 'Resign',`
`							 btnClass: 'btn-red',`
`							 action: function () {`
`								 var name = this.$content.find('.alasanresign').val();`
`								 if(!name){`
`									 $.alert('Alasan wajib diisi !');`
`									 return false;`
`								 }`
`								 this.$content.find('.formresign').submit();`
`							 }`
`						 },`
`						 cancel: function () {`
`							 //close`
`						 },`
`					 },`
`					     onContentReady: function () {`
`						   // bind to events`
`						   $( "#tglresign" ).datepicker({`
`						   beforeShow: function() {`
`							  setTimeout(function(){`
`								  $('.ui-datepicker').css('z-index', 99999999999999999999999);`
`							  }, 0);`
`						  }`
`						   });`
`						`   
`					   }`
`			});`

![untitled](https://cloud.githubusercontent.com/assets/887938/22851649/f5572754-f063-11e6-99e9-025585996ab1.jpg)

**Comment by craftpip** [comment]
you'll have to increase the z-index of the datepicker. that will solve the problem

**Comment by craftpip** [comment]
Can you please make a jsfiddle of this issue

**Comment by nizarhdt** [comment]
on this case, i can't increase the z-index of the datepicker. i used have to decrease the jconfirm to 99 once the content ready. here is my code to solved the issue:
`onContentReady: function () {`
`$('.jconfirm').css('z-index', 99);`
`}`

**Comment by craftpip** [comment]
Yes, that will do, i will make it compatible with the z-indexs of bootstraps elements, thats a good idea
