### ISSUE TITLE
Alert size is large in IE

### ISSUE THREAD

**Issue by Sucka27** [craftpip/jquery-confirm#213]
Is it supposed to be this big? I haven't done any customization. 

![image](https://cloud.githubusercontent.com/assets/8881302/22950667/48e86410-f2bb-11e6-93bd-47befd12431c.png)

**Comment by craftpip** [comment]
Please check if you have bootstrap installed.
if not u can turn the bootstrap dependency off, by setting useBootstrap:false

**Comment by Sucka27** [comment]
Yes, thank you! That was indeed the problem.
