### ISSUE TITLE
Promise not resolving when wrapping $.confirm({ ... }) in the promise.

### ISSUE THREAD

**Issue by tommathewXC** [craftpip/jquery-confirm#215]
I am currently building a "pop-up" module in my application, which is just a wrapper around jquery-confirm. I will be wrapping a confirmation in the promise definition, and if the user clicks "OK", the promise is resolved, and the promise is rejected if the person clicks cancel. 

When I use the a .then on this promise, the resolve or reject is never reached. instead it prints out the jquery context of the overall dialog box. On digging a little deeper, i found that it is getting stuck in the "setTimeout" protion in the close function. 

setTimeout(function() {
                that.$el.remove();
                console.log(that._lastFocused);
                if (that._lastFocused.length && $.contains(document, that._lastFocused[0])) {
                    var st = $(window).scrollTop();
                    var ot = that._lastFocused.offset().top;
                    var wh = $(window).height();
                    if (!(ot > st && ot < (st + wh))) {
                        $("html, body").animate({
                            scrollTop: (ot - Math.round((wh / 3))),
                        }, that.animationSpeed, "swing", function() {
                            that._lastFocused.focus();
                        });
                    } else {
                        that._lastFocused.focus();
                    }
                }
                if (typeof that.onDestroy == "function") {
                    that.onDestroy();
                }
            }, closeTimer * 0.4);
            return true;

Can anyone show my why this is happening?

**Comment by tommathewXC** [comment]
<b> Update: </b>

The more precise problem here is that in $.confirm({ .. }), my cancel and confirm callbacks arent being called. Anyone have similar issues?

**Comment by tommathewXC** [comment]
<b> RESOLVED: </b> I basically had to wrap the resolve/reject within the buttons: { .. } object's functors. looks the outer "close" and "confirm" call backs are deprecated?

**Comment by craftpip** [comment]
Please check what version of jquery-confirm are you using, because from v3, the button defining scheme has changed.

**Comment by craftpip** [comment]
Glad you found that out 👍
