### ISSUE TITLE
Reload or refresh content

### ISSUE THREAD

**Issue by balazmibit** [craftpip/jquery-confirm#216]
Hello , can you help me?
I want to reload or refresh content of confirm windows whan I use AJAX ?

Thank you.

**Comment by craftpip** [comment]
You can set the new content using the this.setContent method
or else if u want to edit the elements u can directly use the jquery dom element this.$content

**Comment by craftpip** [comment]
That is if your content has a div class name as .example
```html
<div class="example"></div>
```

You can put in content like so.
```js
this.$content.find('.example').html('hey there');
```
