### ISSUE TITLE
[feature] setWidth after initialization

### ISSUE THREAD

**Issue by jonasgroendahl** [craftpip/jquery-confirm#218]
Hi,

it would be awesome if you could change the width of the jQuery confirm window as a button is pressed in case you want to show some content in the window. For example my dialog windows have 30% width by default but say i want to show an iframe then it would be cool to be able to change the width of the window to 90% (pretty sure this isn't possible with the current model?)

**Comment by craftpip** [comment]
This can be added, thanks for the suggestion.
i will make this for both columnClass and boxWidth

**Comment by jonasgroendahl** [comment]
sweet!

**Comment by lexurio** [comment]
Do you know when we can expect this feature?
