### ISSUE TITLE
Close dialog

### ISSUE THREAD

**Issue by ssmweb** [craftpip/jquery-confirm#219]
how can i close an opened dialog box from another button, not the ones used in the dialog box setup.
I have used the following with no success:
jconfirm.close();

Thank you,
Andreas.

**Comment by craftpip** [comment]
you can define a global variables and assign the jc instance into it, 
and later use the .close() method to close the model.

**Comment by codigoart** [comment]
it does not work for example look my code bellow javascript from the page loaded variables are not acessible i get error undefined when i try use jc.close(); in my old modal pluggin i coult do it like: $.pgwModal('close'); 

` var jc = $.dialog({
                            useBootstrap: false,
                            boxWidth: '90%',
                            draggable : true,
                            maxboxWidth: '600px',
                            animation : 'zoom',
                            animationSpeed: 1000,
                            //closeIcon : false,
                            //closeIconClass : true,
                            title: '',
                            content: 'url:index.php?page=live&at=' + data.t,
                            onClose: function () {
                                clearInterval(refreshId); 
                                refreshId = setInterval(rotate, 5000);
                            }
                    });`

**Comment by cleybertandre** [comment]
You can access all jquery-confirm instances with `jconfirm.instances` (at least on v3.3.2).

So, if you have only one instance, it's enough to do:
`jconfirm.instances[0].close();`

On the other hand, If you want to close all instances: 
`for(const instance of jconfirm.instances){ instance.close(); }`.
