### ISSUE TITLE
Vertical Alignment

### ISSUE THREAD

**Issue by VoltX** [craftpip/jquery-confirm#221]
Hi, 

thanks for your awesome work. Very useful !

It could be nice to have a special option for vertical alignment. 
We can imagine predefined options like: top, middle, bottom
and with an offset.

Maybe that already exists but I found nothing.

Thanks.

**Comment by craftpip** [comment]
Vertical alignment will be hard to implement on the current approach, as the modal tries to constantly adjust its height with the content height,

currently if you set the 'alignMiddle' property to false, it will stick the model on the top. unfortunately, bottom option is not available.
