### ISSUE TITLE
Hide button

### ISSUE THREAD

**Issue by DigItalWarrior69** [craftpip/jquery-confirm#222]
Hello, thank you for this great script.
How I can add a condition for show or not a button based in input content?
In old version I've solved with this line:
"if (document.getElementById('items').value > 0){var btn = 'Show';}else{var btn = ""}; "
and after:
"confirmButton: btn,"
In latest version I cant because I cant add condition between buttons instructions.
Thank you

**Comment by craftpip** [comment]
yes you can do this,
you can refer to [button functions doc](http://craftpip.github.io/jquery-confirm/#button-functions)


```
var jc = $.confirm({
    buttons: {
       buttonA: {
            text: 'button a',
            action: function () {
                this.buttons.buttonB.hide(); // hide buttonB
                this.buttons.buttonB.show(); // show buttonB
            }
        },
        buttonB: {
            text: 'button b',
            action: function () {

            }
        }
    }
});
// or 
jc.buttons.buttonB.hide(); // outside the modal.
```

**Comment by stillnoname** [comment]
Hello, thank you for this great script.
When I was using the way you said to hide the button, I ran into a problem:
jc.buttons.buttonB.hide is not a function.
And  my jquery-confirm version is 3.0.1, jquery version is 1.10.2.
How to solve the problem?
Thank you!

**Comment by craftpip** [comment]
@stillnoname 
Please try updating to the latest version. 

also 
https://github.com/craftpip/jquery-confirm/blob/9e5845190e2316b5ef0b89b12579b8810981141f/js/jquery-confirm.js#L567
please check if you have the hide function at line 567 of v3.0.1

**Comment by stillnoname** [comment]
Thank you for your help.
And I slove the problem by this way:
var jc = $.confirm({
        buttons: {
            buttonA: {
                text: 'button a',
                action: function () {

                    this.buttons.buttonB.hide(); // hide buttonB
                }
            },
            buttonB: {
                text: 'button b',
                action: function () {

                }
            }
        },
        onOpenBefore: function () {
            jc.buttons.buttonB.hide();
        }
    });

jquery-confirm may could not hide the button immediately when it is initialized, am i right?
Thanks again for your help!

**Comment by craftpip** [comment]
@stillnoname Right, the dom is not ready right away.

But, if you want to hide the button from modal start, 
you can use
```js
buttonB: {
    hide: true,
    text: 'button b',
    action: function () {
    }
}
```

**Comment by stillnoname** [comment]
Thank you!
Expect the new version.
: )

**Comment by craftpip** [comment]
Added in https://github.com/craftpip/jquery-confirm/commit/74e756d9bb6aa329804a05cd34398b304efb5659

**Comment by setoba1192** [comment]
for jquery-confirm v3

button: {
            isHidden: true, // hide the button
           action: function () {
           }

**Comment by KmarAkrout** [comment]
@setoba1192  this is working like a charm ;) thank you
