### ISSUE TITLE
Remove x icon from close icon in top right

### ISSUE THREAD

**Issue by mousanajafi** [craftpip/jquery-confirm#223]
hi

how i can remove x from close icon in top right?

best regards

**Comment by mousanajafi** [comment]
thank you for your answer

but i mean is remove content of close icon (x)

in other words remove content of jconfirm-closeIcon tag

`<div class="jconfirm-closeIcon">x</div>`

**Comment by craftpip** [comment]
Why would you like to remove it's content, it's the same as removing the tag itself right?

**Comment by craftpip** [comment]
If you want to keep the tag but remove it's content then use this, 

`this.$closeIcon.html('')` // set an empty string.

**Comment by craftpip** [comment]
Please reopen the issue if any updates
