### ISSUE TITLE
发现一个关于confirm提交的问题

### ISSUE THREAD

**Issue by XiyangZhang** [craftpip/jquery-confirm#225]
你们提供的2.5.1的版本的confirm中我发现一个bug，弹出的confirm框如果用tab键将确定按钮选中再点击enter按键来提交的话，会被提交两次！这个问题有解决方法吗？

**Comment by XiyangZhang** [comment]
代码是这样子的：
<div class="main-contenl"></div>
<a href="javascript:;" onclick="test()">测试confirm的bug</a>
function test(){
	$.confirm({
		keyboardEnabled: true,
		title: 'confirm bug 测试',
		content: '请先使用Tab键将submit选中，然后点击键盘enter键：<br />',
		//confirmKeys: [13],//return
		cancelKeys: [27],//escape
		confirmButton: 'submit',
		cancelButton: 'cancel',
		confirm: function(){
			$(".main-content").append("dkfsadfjsdh---");
		}
	});
}

**Comment by craftpip** [comment]
v2.5.1 is really old, current is 3.1.0, i would suggest you to please update.

The problem here is, the button is getting triggered twice, once from the button click, and other from the keys event.

turn off the keys event, remove the enter button key for confirm `confirmKeys: []` 
this will solve the problem for you.

**Comment by XiyangZhang** [comment]
Yes,you really got it rightly.But in fact,you could not really correct it just turn off the the enter button key for confirm confirmKeys: [].Why?I really like the keys event,at least the cancle key event:cancelKeys:[]. Whether cna I correct this problem by reserve the cancel key event but not totally turn off the key event at v2.5.1

**Comment by craftpip** [comment]
I can't think of a workaround this, you'll have to prevent adding 'enter' and 'space' keys event, as those click buttons too.

**Comment by craftpip** [comment]
The bug exists in the latest version too, 
http://jsfiddle.net/craftpip/k7sxL4dv/
not with enter button, but with space button.

**Comment by craftpip** [comment]
If upgrading to v3 is not feasible for you, i would recommend you to build a wrapper function for the newer version, which will take in v2 arguments, alter them and pass it on to the v3 function

**Comment by XiyangZhang** [comment]
yeah, i also think i need to upgrade to the latest version,thanks for your answer. if any other problem i meet in the future，i will come here to look for help. thanks a lot anyway!
