### ISSUE TITLE
How to disable console logs

### ISSUE THREAD

**Issue by patelnwd** [craftpip/jquery-confirm#227]
Hello when i am clicking OK then its logging on console with click object. please suggest me how can i stop to log these.
![image](https://cloud.githubusercontent.com/assets/10633999/23700254/46b44a88-0418-11e7-9055-939db725d522.png)

![image](https://cloud.githubusercontent.com/assets/10633999/23700338/7ec27080-0418-11e7-9c84-897f66bf3663.png)

Email: mukesh_gam_m@yahoo.com
Mob: 7382707348

**Comment by craftpip** [comment]
It looks that your version is not the latest, that console.log was removed,
please update to v3.1.0

as a last resort you can remove the console.log lines from the file.
