### ISSUE TITLE
dialog not positioning correctly in .net aspx

### ISSUE THREAD

**Issue by cscarlsson** [craftpip/jquery-confirm#228]
Versions:
jquery 1.8.3 (tried with both local and from google cdn)
.net 3.5 (c#) (Visual Studio 2015 Community Edition)
chrome Version 56.0.2924.87 (64-bit)

Using a .html file the dialog works perfectly, however if I use an aspx file with or without master page the dialog always positions vertically centered and horizontally to the left as per attached screenshots.  I have tried this on a blank project as well as an existing project that I am supporting.  Screenshots attached at bottom.

Javascript used is:

function testAlert() {
    $.alert({
        title: 'Alert!',
        content: 'Simple alert!',
        boxWidth: '30%',
        theme: 'material',
        useBootstrap: false,
    });
    return false;
}

function testConfirm() {
    $.confirm({
        title: 'Confirm!',
        content: 'Simple confirm!',
        boxWidth: '30%',
        theme: 'material',
        buttons: {
            confirm: function () {
                $.alert('Confirmed!');
            },
            cancel: function () {
                $.alert('Canceled!');
            },
            somethingElse: {
                text: 'Something else',
                btnClass: 'btn-blue',
                keys: ['enter', 'shift'],
                action: function () {
                    $.alert('Something else?');
                }
            }
        },
        useBootstrap: false
    });
    return false;
}

Basic alert:
![image](https://cloud.githubusercontent.com/assets/6892332/23718111/46bb330a-042e-11e7-8833-8e4e6e4e1272.png)

Modal:
![image](https://cloud.githubusercontent.com/assets/6892332/23718154/61283f1c-042e-11e7-94cc-85c0db273cb0.png)

**Comment by cscarlsson** [comment]
Update:
Removing the theme allows the box to appear in the centre.  Not sure this is intended but will be a workaround for me.

**Comment by craftpip** [comment]
These seems to be a problem, can you please create a jsfiddle for this.
There must be some problem with the existing stylesheet that overwrites with the jconfirm styles.

**Comment by craftpip** [comment]
I confirmed this is a bug. fixing it asap

**Comment by cscarlsson** [comment]
Have tested using material and supervan themes, both are now working as expected.  Thanks so much for your prompt help with this.
