### ISSUE TITLE
Form submit confirmation doesn't work

### ISSUE THREAD

**Issue by Sinister87** [craftpip/jquery-confirm#229]
Hi,
please help me! It doesn't work to confirm a submit delete.
When I press "Elimina(delete)", the button close the dialog box but nothing happens.
My code is:

file.php
I have
form id="deletekit"
button id="delete_kitid" type="submit"

file.js
$("#delete_kitid").confirm({
title: "Eliminazione Kit",
content: "Sei sicuro di voler eliminare il kit?",
buttons: {
confirm: {
text: "Elimina",
btnClass: 'btn-danger',
action: function(){
$('#deletekit').submit();
}
},
cancel: {
text: "Annulla",
btnClass: 'btn-default'
}
}
});

Thanks

**Comment by craftpip** [comment]
try this

```js
var askConfirmation = true;
$("#deletekit").submit(function(e){
    if(askConfirmation){
        e.preventDefault(); // dont submit the form, ask for confirmation first.
        $.confirm({
            title: "Eliminazione Kit",
            content: "Sei sicuro di voler eliminare il kit?",
            buttons: {
                confirm: {
                    text: "Elimina",
                    btnClass: 'btn-danger',
                    action: function(){
                        askConfirmation = false; // done asking confirmation, now submit the form
                        $('#deletekit').submit();
                    }
                },
                cancel: {
                    text: "Annulla",
                    btnClass: 'btn-default'
                }
            }
        });
    }
});
```

you used 
```js
$("#delete_kitid").confirm({
```
which is only for <a> elements to redirect to their href.

**Comment by Sinister87** [comment]
Hello Craft,
Thanks for the answer.
I tried, but nothing :(

![image](https://cloud.githubusercontent.com/assets/26331747/23851758/e5ff339e-07e4-11e7-8cd1-4e00c0552605.png)

![image](https://cloud.githubusercontent.com/assets/26331747/23851809/182c7ebc-07e5-11e7-9bff-f9c97b385023.png)

When I confirm "Elimina", the page reload itself but nothing..

**Comment by craftpip** [comment]
The code is right, 
is the browser just reloading or getting submitted to your action URL ?

**Comment by Sinister87** [comment]
The browser just reloading

**Comment by craftpip** [comment]
https://jsfiddle.net/craftpip/fj7kLhmv/
i made this fiddle , i hope it helps,

**Comment by maxence33** [comment]
@craftpip This works great though I have many form on the same page, would there be a quick change to make it work with classes ?
