### ISSUE TITLE
Content with scroll prevents body from scrolling even after modal close

### ISSUE THREAD

**Issue by thinkdj** [craftpip/jquery-confirm#230]
.jconfirm-no-scroll-{id} keeps on appending on the body and it is not going away after closing. After closing the modal, the body is left with overflow:hidden!important; and becomes un-scrollable

**Comment by thinkdj** [comment]
Weirdly, the class disappears momentarily, and then reappears on modal close.

**Comment by craftpip** [comment]
.jconfirm-no-scroll is added when the model height is more than the window height.
and removed when it exists on body.

can you give me steps to reproduce this output?
or create a jsfiddle. that will help.

**Comment by thinkdj** [comment]
@craftpip Tried on fiddle. Non-reproducible. Apologies. 
It's got to be some specific to my app code then. I will find out.
