### ISSUE TITLE
Toastr/like alert

### ISSUE THREAD

**Issue by nam-co** [craftpip/jquery-confirm#232]
Hello, thanks for the work, I was wondering if there a way to use this script as a toastr/like alert, where the automatically close (with no button) after a few seconds and you can position them for example top right, and if you click outside it disappears, or even an option to not show it as a modal.

2. for some reason in safari the text sometimes blurs when you click outside the dialog box

Thanks for your time

**Comment by craftpip** [comment]
hello @nam-co 
A toaster like alert is not possible with the current structure. 
and a toasters options will be too confusing to use with the modal.

safari has a lot problems rendering stuff, can you please make a jsfiddle and give the version of your safari,  will check it out.
