### ISSUE TITLE
popup css print problem

### ISSUE THREAD

**Issue by ahmetozalp** [craftpip/jquery-confirm#233]
step1 http://prnt.sc/ek9xsa
step2 http://prnt.sc/ek9y2w

step3 problem page: http://prnt.sc/ek9ya2

**Comment by craftpip** [comment]
This plugin doesn't have print support, 
What should be the correct output for print ?

**Comment by ahmetozalp** [comment]
@media print {
.jconfirm {
  	display:none;
  }
}

**Comment by craftpip** [comment]
that will totally hide the confirm modal, that can be unexpected right ?
people might want to print with the modal

**Comment by ahmetozalp** [comment]
Hide popup on page from printer

**Comment by ahmetozalp** [comment]
Write to myself

**Comment by craftpip** [comment]
okay i'll add this in the options,
by default the modal will be printable 👍
