### ISSUE TITLE
Confirm routines falls through when it's assigned to a click event.

### ISSUE THREAD

**Issue by markrlondon** [craftpip/jquery-confirm#234]
Hi - If I have an onclick event, and it calls .confirm (or a click event is assigned a function, which calls .confirm).  Clicking does cause reate the confirm box.   But at the same time, the code falls through past the .confirm call, to the end of the function, even before someone clicks on the confirm box buttons.   I tried stopping event propagation, but that doesn't help.   Any suggestions?  Thanks. - Mark .

**Comment by craftpip** [comment]
This is expected as the $.confirm function wont block the js execution. blocking the JS execution is not possible. You'll have to use the button click callbacks to handle further actions

reference:
http://stackoverflow.com/questions/6807799/stop-page-execution-like-the-alert-function

**Comment by markrlondon** [comment]
My bad.  I thought it was blocking because I first used the alerts, which did appear to be blocking. :)  Thanks.
