### ISSUE TITLE
About the hash comparison in _watchContent

### ISSUE THREAD

**Issue by yuweichen** [craftpip/jquery-confirm#236]
When the contents of the pop-up too much, '_watchContent' can be removed 'content' hash comparison, if not removed, will lead to the browser is slow, if you remove whether there will be other problems?

PS:

> _watchContent: function () {
            var that = this;
            if (this._timer) clearInterval(this._timer);
            this._timer = setInterval(function () {
               // var now = that._hash(that.$content.html());
                var nowHeight = that.$content.height();
                //if (that._contentHash != now || that._contentHeight != nowHeight) {
                if (that._contentHeight != nowHeight) {
                    //that._contentHash = now;
                    that._contentHeight = nowHeight;
                    that.setDialogCenter();
                    that._imagesLoaded();
                }
            }, this.watchInterval);
        }

**Comment by craftpip** [comment]
It is to check for changes in the dom, and resizes the modal to your content.
if you remove it, and change the content at run time, the modal wont resize.

You can decrease the `watchInterval` to slow down the checks.

I'm going to change the way the content is watched and hopefully it will be faster.

**Comment by yuweichen** [comment]
Thanks! 
If you increase the 'watchInterval' will affect the user experience. At present, only the back of a judgment can also be achieved modal adjustment, such as I dynamically add some elements. Can also achieve the effect. Can tell me Under what circumstances hash comparison to play its due role?

**Comment by craftpip** [comment]
> If you increase the 'watchInterval' will affect the user experience
Yes, the modal will be updated in that interval, (this only affects when the modal's content is changed and modal has to center itself.)

>  I dynamically add some elements.
Yes, if you dynamically add elements, you know when the content is changing, 
you can call `setDialogCenter` manually after editing the content. that will work fine.

**Comment by yuweichen** [comment]
thanks very much!
