### ISSUE TITLE
Focus issue when capturing keydown of tab button

### ISSUE THREAD

**Issue by cscarlsson** [craftpip/jquery-confirm#237]
jQuery 1.8.3

I'm trying to set the focus to another textbox after displaying a jquery-confirm dialog and executing some code.  I have set up a basic jsfiddle that demonstrates the behaviour I am getting.

https://jsfiddle.net/8uap36fp/16/

Upon tabbing out the dialog displays, as expected, all good so far.  When I confirm the dialog, the focus is set to the target textbox but immediately moves back to the original textbox (the caller).  

Is this something I am doing wrong?  I'm not the most proficient javascript/jQuery coder so I am asking for help here please.

**Comment by craftpip** [comment]
jquery-confirm remembers the last focused element, and sets the focus back when its closed.
Currently there's no option to turn this feature off.

As a hack you can set the lastFocused an element thats not found.
https://jsfiddle.net/craftpip/8uap36fp/18/

**Comment by cscarlsson** [comment]
Thanks so much for the prompt reply on this, I've spent way too much time trying to sort this out thinking it was my own issue.
I do appreciate all your help.
