### ISSUE TITLE
autoclose Property Bugs

### ISSUE THREAD

**Issue by zuukaer** [craftpip/jquery-confirm#24]
Hi,
   I am a common user of your jquery-confirm plugin,however,when recently I  m using its autoclose function,I found it doesn't work well.This is your sample codes in your Website,
###[code]
$.confirm({
    title: 'Delete user?',
    content: 'This dialog will automatically trigger \'cancel\' in 6 seconds if you don\'t respond.',
    autoClose: 'cancel|6000',
    confirm: function(){
        alert('confirmed');
    },
    cancel:function(){
        alert('canceled');
    }
});
###[/code],
while in latest firefox, error occured,this is the error log:
###
Error: Syntax error, unrecognized expression: &lt;span class="countdown"&gt;&lt;/span&gt;
###
Then I test it on Chrome, the logs is however more detailed:
###
Uncaught Error: Syntax error, unrecognized expression: &lt;span class="countdown"&gt;&lt;/span&gt;
    at Error (native)
    at Function.st.error (.../demo/js/jquery-1.9.1.min.js:4:10973)
    at ft (.../demo/js/jquery-1.9.1.min.js:4:17138)
    at wt (.../demo/js/jquery-1.9.1.min.js:4:19823)
    at Function.st (.../demo/js/jquery-1.9.1.min.js:4:6140)
    at b.fn.extend.find (.../demo/js/jquery-1.9.1.min.js:4:20941)
    at b.fn.b.init (.../demo/js/jquery-1.9.1.min.js:3:1126)
    at b (file:///C:/Users/kzu/Projects/ODC/021SourcesCode/demo/js/jquery-1.9.1.min.js:3:206)
    at Object.Jconfirm._startCountDown (.../demo/js/jquery-confirm.js:159:28)
    at Object.Jconfirm._buildHTML (.../demo/js/jquery-confirm.js:152:22)st.error 
  @ jquery-1.9.1.min.js:4ft 
  @ jquery-1.9.1.min.js:4wt 
  @ jquery-1.9.1.min.js:4st 
  @ jquery-1.9.1.min.js:4b.fn.extend.find 
  @ jquery-1.9.1.min.js:4b.fn.b.init 
  @ jquery-1.9.1.min.js:3b 
  @ jquery-1.9.1.min.js:3Jconfirm._startCountDown 
  @ jquery-confirm.js:159Jconfirm._buildHTML 
  @ jquery-confirm.js:152Jconfirm._init 
  @ jquery-confirm.js:67Jconfirm 
  @ jquery-confirm.js:61jconfirm 
  @ jquery-confirm.js:53$.confirm 
  @ jquery-confirm.js:22(anonymous function) 
  @ VM288:2InjectedScript._evaluateOn 
  @ VM287:895InjectedScript._evaluateAndWrap 
  @ VM287:828InjectedScript.evaluate 
  @ VM287:694
###
After that,I check the source codes,and found this line:
###
this.$cd = $(' &lt;span class="countdown"&gt;&lt;/span&gt;').appendTo(this['$' + opt[0] + 'Button']);
###
I don't know how it happened,but just out of Intuition,I deleted the SPACE before '&lt;span ',however it  functioned.
I don't know why,I just think it's a problem to let you know,and maybe you can update it!
By the way,thank you,that really saves me a lot of time!

**Comment by craftpip** [comment]
Thank you @zuukaer for the interest, 
i will look into this asap and get back to you with the solution.

:)

**Comment by craftpip** [comment]
Hello @zuukaer 

I tried finding the error you mentioned. but didn't find it.
I have tested the current website, craftpip.github.io/jquery-confirm 
with firefox 38.0.5 for errors, i got none,

Can you provide me more details about this.

**Comment by craftpip** [comment]
Hello @zuukaer 

I have recently pushed updates, please confirm if you still are facing the problem,

Thanks
