### ISSUE TITLE
Initial positioning of jquery-confirm window is wrong upon loading chart

### ISSUE THREAD

**Issue by jonasgroendahl** [craftpip/jquery-confirm#240]
Hello,

I'm trying to load a chart + datepicker inside a jquery-confirm dialog but its initial positioning is wrong, seems like the margin-top is calculated wrong. The window looks fine if i close it and open it again. Screenshot when jquery-confirm is opened: http://imgur.com/a/oP4yb. Usually the window would be centered but on the initial load it's positioned below the center.

This is my code:
JavaScript:
```
$('#aDiv').hide();
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
			type: 'bar',
			...});

var aDiv = $("#aDiv");
$.confirm({
	title: '<?php echo _('Sensmax data'); ?>',
	type: 'green',
	content: aDiv,
	boxWidth: '70%',
	useBootstrap: false,
	onContentReady : function() {
	     $("#datepicker").datepicker({dateFormat: 'yy-mm-dd'});
	     $("#myChart").css("display","");
	     aDiv.show();
	},
        onClose : function() {
		$("#datepicker").removeClass('hasDatepicker')
	},
});

```
HTML:
```
<div id="aDiv">
	<canvas id="myChart" width="500" height="400" ></canvas>
</br>
	<input type="text" id="datepicker"> </input>
</div>
```

How come it's calculating the wrong margin-top? Is it because the chart isn't loaded in yet? If so, what can I do in this case? If I was able to get the DOM object, i could manually set the margin-top on the first load since i know the height of the chart+datepicker DIV.

**Comment by jonasgroendahl** [comment]
By adding this.setDialogCenter(); in ` onContentReady` seemed to fix it. Found it in one of the last lines of the API docs. :)

**Comment by craftpip** [comment]
Yes, this happens because the chart wasnt loaded, jconfirm calculated its initial height, and moved along.

jconfirm watches the content regularly to check if there are changes on the DOM, and if yes, it automatically centers itself.
in `<canvas>`'s case, jconfirm can't find if the element changed or not, that's causing the problem.

A watch for canvas elements has to be added.
