### ISSUE TITLE
button keydown problem

### ISSUE THREAD

**Issue by eytanchen** [craftpip/jquery-confirm#241]
When submitting a form using the ENTER key, there is a loop problem when using Jquery Confirm, if set to use ENTER to close the dialog. The button event is set for "keyup". So, you press ENTER, the form is submitted and jquery confirm dialog appears, and then you release the enter key, and the dialog closes.
Should change key event to "keydown" instead, that solves this problem.

**Comment by craftpip** [comment]
okay, i will test it out.
Thanks for bringing it out.

**Comment by overbyteinteractive** [comment]
Have we had any update on this, having the same problem

**Comment by craftpip** [comment]
Fixed in v3.2.0
