### ISSUE TITLE
jc.close() doesn't listen to scrollToPreviousElement parameter

### ISSUE THREAD

**Issue by ballanz89** [craftpip/jquery-confirm#242]
I have this piece of code:

                   jc = $.dialog({                             
                        theme: 'supervan',                                
                        animation: 'top',                        
                        closeAnimation: 'bottom',                                
                        closeIcon: 'false',
                        scrollToPreviousElement: null,
                        scrollToPreviousElementAnimate: null,
                        closeIconClass: 'hidden',
                        title: 'My title',
                        content: 'My content',
                        onOpen: function(){
                            setTimeout(function() {
                                if (myFunction()) {
                                   jc.close();
                                    return false;
                                } 
                            }, 1000); 
                        },
                        onDestroy: function () {
                            $.confirm({                                
                                theme: 'supervan',
                                escapeKey: true,
                                animation: 'top',                        
                                closeAnimation: 'bottom',
                                scrollToPreviousElement: null,
                                scrollToPreviousElementAnimate: null,
                                backgroundDismiss: true,
                                title: 'My title',
                                content: "My content",
                                buttons: {
                                    continua: function () {                                        
                                        return true;
                                    }                                
                                }
                            }); 
                        },
                   }); 

When I call the .close API it still scrolls to the top of the page.

**Comment by craftpip** [comment]
Looks like, it could not find the element, i will look into this

**Comment by craftpip** [comment]
Fixed 👍

**Comment by ballanz89** [comment]
Great! Thank you 👍 May I ask you when the new version will be available?

**Comment by craftpip** [comment]
Really soon, by today itself.

**Comment by craftpip** [comment]
Fixed in v3.2.0
