### ISSUE TITLE
issue and suggestion

### ISSUE THREAD

**Issue by codigoart** [craftpip/jquery-confirm#244]
Frist of all thanks for making this amazing lib <3,

hello im migrating to this modal but how i close modal outside from script of loaded page? is there something like $.pgwModal('close');  can you show me an example of doing this please?

also how do i detect onclose outside? the i used was something like:
$(document).bind('pgwModal::Close', function() {
});

i think this modal need re-initialize callback functions to be perfect for all,
suggestion: you add width to options its cool but people like me who not use Bootstrap also need max-width, im using tempfix:
template.find('.jconfirm-box').css('max-width', this.maxboxWidth);
to use like= 
useBootstrap: false,
boxWidth: '90%',
maxboxWidth: '600px',
i think people need it thank you

**Comment by craftpip** [comment]
@codigoart Sorry for the late reply

Closing the modal.
```js
var jc = $.confirm({
    title: '...',
    content: '....',
    buttons: {
        test: function(){
            this.close(); // this will close the modal.
        }
    }
});
jc.close() // this will close the modal.
jc.onClose = function(){
    // onClose callback outside.
};
```
and, 
The max width option is coming up.

**Comment by codigoart** [comment]
Yes i tryed this but im using ajax loaded page thats maybe the reason it fails i get undefined var error take a look at my code:

var jc = $.dialog({
                            useBootstrap: false,
                            boxWidth: '90%',
                            draggable : true,
                            maxboxWidth: '600px',
                            animation : 'zoom',
                            animationSpeed: 1000,
                            closeIcon : false,
                            closeIconClass : true,
                            title: '',
                            content: 'url:index.php?page=live&at=' + data.t,
 onClose: function () {
                                clearInterval(refreshId);
                                clearInterval(refreshIddd);
                                refreshId = setInterval(rotate, 5000);
                            }
                    });

**Comment by craftpip** [comment]
I dont understand this properly,

You've javascript in the index.php page that you're loading ?
i fear that wont work, the content is simple pulled and put into DOM as string.

If you get it as undefined, try `window.jc = $.dialog()..` make it a global variable.

It would be great if you create a fiddle to demonstrate,

**Comment by codigoart** [comment]
Thanks!, you solved my problem <3, window.jc = $.dialog().. + window.jc.close(); worked once i start earn $ in my upcoming website il make a donation thank you.

**Comment by craftpip** [comment]
Glad i could help.
Thanks a lot.
