### ISSUE TITLE
prompt box not working on bootstrap modal

### ISSUE THREAD

**Issue by sezercoban** [craftpip/jquery-confirm#245]
Hello,
When I try to open input confirm box from a bootstrap modalbox, input(or textarea) becomes not editable. 
I played with z-index but no-result. Interestingly, Option select is working. 

How we can make it work on modal? 
thanks in advance.

**Comment by craftpip** [comment]
Hello @sezercoban 
Remove the tabindex attribute from the bootstrap model, that will fix it.

Also, 
#202

**Comment by craftpip** [comment]
Closing this issue.
