### ISSUE TITLE
Possible misbehavior with keystroke or just a misconfigured example

### ISSUE THREAD

**Issue by wamarante** [craftpip/jquery-confirm#246]
Hi,

Among the examples showed as Features at https://craftpip.github.io/jquery-confirm/ there is one with a button called "Keystrokes".

Sequence of actions:
1. Click the button 
2. Press ENTER as suggested to accept OK
3. Another popup comes saying "Okay button was triggered.".
4. From here, as many ENTER you press, as many popup saying "Okay button was triggered." will appear.

If you press ENTER at step 2, the common and easy way is to press ENTER again to close the dialog, but it will keep opening copies of it. To close them, it's necessary use the mouse as many as the number of copies opened.

Browser: Google Chrome 56.0.2924.87 (Versão oficial) 64 bits

Thanks.

**Comment by craftpip** [comment]
@wamarante Thanks for pointing it out.
This is a bug, 
After the first modal closes, it focuses back to the Keystrokes button. 
Now, when enter is pressed on the Keystrokes button it opens a new modal and **immediately triggers the enter key too.**

The statement in bold is the problem.

**Comment by craftpip** [comment]
#241

**Comment by wamarante** [comment]
Thanks for fast reply. Congratulations for your work.
