### ISSUE TITLE
Not auto open when component initialized

### ISSUE THREAD

**Issue by aswzen** [craftpip/jquery-confirm#247]
How to make the jquery-confirm not automatically open when initialized?

Thank You
Git

**Comment by craftpip** [comment]
Once you hit the function $.confirm() the modal will open,
Call the $.confirm function when you want it to open.

```js
function call_it(){
    $.confirm(...);
}
call_it();
```

**Comment by aswzen** [comment]
i want to reuse the component, so i need to initialized it at first

**Comment by craftpip** [comment]
okay, this feature is not available yet.
but this will be considered for a feature.
