### ISSUE TITLE
How do you make the text on the buttons not all uppercase?

### ISSUE THREAD

**Issue by mbrowncog** [craftpip/jquery-confirm#249]
Is there a way to make the text on the jquery-confirm buttons the same as the other buttons in my bootstrap app - Mixed case letters (not all uppercase) and the same font?

The jquery-confirm buttons appear to have a different font, and they are always uppercase.

**Comment by wamarante** [comment]
Hi, You can edit the .css file (jquery-confirm.min.css).

To solve the uppercase "problem", you can just replace `text-transform:uppercase` for `text-transform:none`.
You can do the same with `font-family`. Just look for the places where the fonts are set in the .css file and replace for those used by Bootstrap.

;)

**Comment by mbrowncog** [comment]
Thank you for your help! Makes perfect sense now that you explained it.Mike

**Comment by aelfannir** [comment]
```css
.text-transform-default { text-transform: none !important; }
```

```js
button: { btnClass: 'text-transform-default' }
```
