### ISSUE TITLE
popups are opened without wait the return of the one before

### ISSUE THREAD

**Issue by wamarante** [craftpip/jquery-confirm#250]
Hi,

If I use:

```
$.alert({    title: 'Alert!',    content: 'Simple alert!' });
$.alert({    title: 'Alert!',    content: 'Simple alert!' });
```

Two alerts will be opened at the same time. I think that the common behaviour should be stop after the first one 'till it has been closed (sequential run). `confirm `and `dialog `also run like described.

Is that by design? If so, is there a way to disable such behaviour?

Thanks.

**Comment by craftpip** [comment]
The code is not blocking. it is impossible to have functionality like the native alert.
You'll have to use callbacks in this case.

have a look at this
http://stackoverflow.com/questions/13635297/emulate-javascript-alert-blocking-nature

**Comment by plasebo** [comment]
You can try using callback or use deferred like this: 
https://codepen.io/plasebo/pen/WmRxzz?editors=1010
