### ISSUE TITLE
Assign the result of confirm to a variable

### ISSUE THREAD

**Issue by wamarante** [craftpip/jquery-confirm#251]
Hi,

It is possible to do something like the following example?

```
function my_alert( msg ) {
    $.confirm({
        title: 'Confirm!',
        content: 'Simple confirm!',
        buttons: {
            confirm: function () {
                return 'y';
            },
            cancel: function () {
                return 'n';
            }
        }
    });
}
```
`var choice = my_alert( 'do you really wanna remove the file?' );
`

This approach would allow to build a generic pre-configured `confirm `as a function to be called everywhere in the code.

Furthermore, using the designed behaviour should request to repeat lot of the code to each confirm I need to do, as the action to each button is inside its own code.

Thanks.

**Comment by craftpip** [comment]
This implementation is not possible, 
only the native alert and confirm is blocking code.
You'll have to use callbacks instead.

have a look at this
http://stackoverflow.com/questions/13635297/emulate-javascript-alert-blocking-nature

**Comment by plasebo** [comment]
You can try using callback or use deferred like this: 
https://codepen.io/plasebo/pen/WmRxzz?editors=1010
