### ISSUE TITLE
Error when using JQuery-Confirm

### ISSUE THREAD

**Issue by chartierpw** [craftpip/jquery-confirm#254]
I get this when I link your js files:

JavaScript critical error at line 195, column 5 in http://localhost:4101/SignIn.aspx\n\nSCRIPT1009: Expected '}'

Code:
        function fConfirm()
        {
            $.confirm({
                title: 'Please Confirm',
                content: 'Have you entered all the data?',
                confirmButton: 'Yes',
                cancelButton: 'No',
                confirm: function(){
                    return true;
                },
                cancel: function(){
                    return false;
                }
            });
    }

Anyone?

**Comment by craftpip** [comment]
This is probably not a fault with the library, but in your code.
can you please inspect the line of error in jquery-confirm script ?

**Comment by craftpip** [comment]
Closing this issue now, please reopen later.
