### ISSUE TITLE
Content without bindings

### ISSUE THREAD

**Issue by tresrrr** [craftpip/jquery-confirm#256]
After load the jquery-confirm alert, the content of the div loaded inside the alert has no bindings.
All bindings are lost.

¿Is there a way to load an alert content with bindings?
Example: jquery-confirm alert with a <select> need an "on change".

Appreciate any help

Thanks

**Comment by craftpip** [comment]
I will have to make some tests with this, 
you can set the content as empty at first,
and in the onContentReady function 
set the content with `this.$content.html(<put the html element clone here>)`

**Comment by tresrrr** [comment]
Thanks for the tip.

After fighting a few hours, i came to the solution.

My content "#MyContentDIV" contains a Bootstrap-Collapse(Accordion) and I had to move the content to avoid duplicated events. If I clone the contents with the clone events flags, it will launch the events of the "#MyContentDIV" and not the jconfirm-content.

The solution was to "appendTo" the contents and  "appendTo" back again after doing the work.

`
onContentReady: function () {
	$("#MyContentDIV").contents().appendTo( this.$content );
}
onClose: function () {
	$('.jconfirm-content').contents().appendTo("#MyContentDIV");
}
`

Thanks for all and congratulations for jconfirm.

**Comment by craftpip** [comment]
That's a great solution @tresrrr 👍
