### ISSUE TITLE
点击第二次，报错

### ISSUE THREAD

**Issue by akreturn** [craftpip/jquery-confirm#258]
```
					<c:forEach items="${page.list}" var="log">
						<tr>
							<td>${log.moduleName}</td>
							<td>${log.action}</td>
							<td>${log.username}</td>
							<td><fmt:formatDate value="${log.createDate}"  type="both"/></td>
							<td>${log.ip}</td>
							<td>
								<shiro:hasPermission name="sys:log:get">
									<a name="getlogBtn" value="${log.id}" onclick="detail('${log.id}')" class="btn  btn-mini btn-primary ">详情</a>
								</shiro:hasPermission>
							</td>
						</tr>
					</c:forEach>
```

	function detail(obj) {
        var url = 'url:${ctx}/sys/log/get/'+obj
        $.dialog({
            title: 'Title',
            content: url,
            backgroundDismiss: true,
        });
    }

list:332 Uncaught TypeError: $.dialog is not a function
    at detail (list:332)
    at HTMLAnchorElement.onclick (list:277)

**Comment by craftpip** [comment]
Can you try `jQuery.dialog` ?
i guess `$` is overwritten in your case.

**Comment by craftpip** [comment]
Closing this issue now, please reopen later.
