### ISSUE TITLE
Showing the message async

### ISSUE THREAD

**Issue by FraGoTe** [craftpip/jquery-confirm#259]
Is there a way to show the message asyncronous, something like this:

` $.confirm({
                    async: false,
                    title: 'Warning!',
                    content: 'Tis that ok?',
                    buttons: {
                        confirm: function () {
                            self.swapAccounts();
                        },
                        cancel: function () {
                            $.alert('Canceled!');
                        }
                    }
                });`

**Comment by craftpip** [comment]
Sorry, im confused.
Can you please tell me the flow?

**Comment by craftpip** [comment]
i guess you are referring to make the function halt the execution until an input is given?
- unfortunately this is not possible. [Please read this](http://stackoverflow.com/questions/13635297/emulate-javascript-alert-blocking-nature)
