### ISSUE TITLE
Question about default action

### ISSUE THREAD

**Issue by kazuo-mu** [craftpip/jquery-confirm#260]
I want to confirm if delete button is clicked.
Then, I want to change only button text (ex. from "OK" to "Delete") not  button action.

I set up like the following.
```
   $(".delete_confirm").confirm(
        {
            content:       "Are you sure to delete?",
            title:         "Delete",
            buttons: {
                confirm: {
                    text: "delete"
                },
                cancel : {
                    text: "cancel"
                }
            }
        }
    );
```

However, If I click and select delete button, no action happened. I wanna continue process for delete.
How do I do?

**Comment by craftpip** [comment]
$(".delete_confirm").confirm(
        {
            content:       "Are you sure to delete?",
            title:         "Delete",
            buttons: {
                confirm: {
                    text: "delete",
                    action: function(button){
                        // this is called when delete is clicked.
                        // if you want to change the text.
                        this.buttons.confirm.setText('something else');
                        // or
                        button.setText('something else');
                    }
                },
                cancel : {
                    text: "cancel"
                }
            }
        }
    );

**Comment by craftpip** [comment]
Closing this issue now, please reopen this when required.
