### ISSUE TITLE
Confirm popup in the center, alerts are not, please help!

### ISSUE THREAD

**Issue by Antmanofgod** [craftpip/jquery-confirm#263]
With this code below, the first confirmation box comes up in the center as I would like it to. But the alert windows for the "Yes" and "No" buttons show up on the left, how can I fix this?
<a href="http://imgur.com/msX02Ug"><img src="http://i.imgur.com/msX02Ug.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/fCPECGI"><img src="http://i.imgur.com/fCPECGI.png" title="source: imgur.com" /></a>
Thank you,
Anthony

$.confirm({
    title: 'Gift Card Information',
    content: 'Did you know we sell gift cards?',
    boxWidth: "75%",
    useBootstrap: false,
    buttons: {
      Yes: function(){
        $.alert("That's great, call today to order!");
    },
      No: {
        text: 'No',
        action: function(){
        $.alert("Well we do, you can call our office to order them!");
      }
    }
  }
});

**Comment by craftpip** [comment]
Hello @Antmanofgod 
This is because you have `useBootstrap: false` set for the $.confirm function and not the alert functions.
Please set `useBootstrap:false` globally using `jconfirm.defaults.useBootstrap = false`

👍 I hope this helps

**Comment by Antmanofgod** [comment]
@craftpip Thank you, I will modify that line and give it a shot!

**Comment by Antmanofgod** [comment]
@craftpip Actually if I may bother you one more time, how would look when I add it to my existing code?
$.jconfirm.defaults = {
  useBootstrap: false,
};

Like this? I have a feeling that's wrong...

**Comment by craftpip** [comment]
Glad to help man
