### ISSUE TITLE
confirmation over bootstrap modal problem

### ISSUE THREAD

**Issue by Kosechok** [craftpip/jquery-confirm#265]
i am trying to use confirmation for radio buttoms in a bootstrap modal window. i'm using 'keyboard: false' for current modal window and can't use "escapeKey: 'no' " for confirmation window. it's doen't work.

for example https://jsfiddle.net/kosechok/c2w91ts0/2/
 
is it possible to create additional option for jquery-confirm
 something like 'confirmation-keyboard: true'?

**Comment by craftpip** [comment]
Hello @Kosechok 
I dont exactly understand what you're trying to achieve. 
can you please elaborate the flow?

**Comment by Kosechok** [comment]
hi @craftpip
ok, take a look
i have a moda window which i open via js 
`$('#myModal').modal({
      show: true,
      keyboard: false
    });`
with **keyboard: false** option

and then i'm using a confirmation
```
$.confirm({
    escapeKey: 'no',
........
    buttons: {
        yes: {
          text: 'Yes',
          btnClass: 'btn-green',
          keys: ['enter'],
          action: function() {
            $.alert('YES');
          }
 .......
```
and in this situation **escapeKey:** and **keys** options doen't work

**Comment by craftpip** [comment]
okay i got it now, its a conflict between the two plugins, 
this is difficult to solve, instead can you try $.dialog to replace modal ?
I've tried this workaround
https://jsfiddle.net/dy4uLvx3/2/

**Comment by Kosechok** [comment]
thx, i will think about it
