### ISSUE TITLE
confirm is duplicate ??

### ISSUE THREAD

**Issue by wahmal** [craftpip/jquery-confirm#266]
`$(document).on('click','a.dt-delete',function(e){
      e.preventDefault();
    	$.confirm({
            container:'main',
            icon: 'help',
            type: 'orange',
            title: 'Konfirmasi !',
            content: 'Anda yakin menghapus menu ini ?',
            buttons: {
              y: {
                  text: 'Ya',
                  btnClass: 'orange',
                  action: function(){
                    $.ajax({
                        url: base_url_admin+'menus/delete',
                        type: "POST",
                        dataType:'JSON',
                        data: {'id':dt_id()},
                        success:function(data){
                            if(data.status){
                              oTable.ajax.reload();
                              Materialize.toast('<i class="material-icons">check_circle</i>&nbsp;'+data.noty, 4000,'green');
                            }else{
                             Materialize.toast('<i class="material-icons">error</i>&nbsp;'+data.noty, 4000,'red');
                            }
                        }
                    });
                  }
              },
              n:{
                text: 'Batal'
                
              }
            }
        });
    });`
iam a`ppend that script on my html and working. But when append to 2nd, confirm dialog is duplicate. how to fix it ?

**Comment by craftpip** [comment]
hello @wahmal 
Its possible you're attaching two click events to the element, check if you have any duplicate definitions.
If thats not the case, please create a jsfiddle. 

Thanks
