### ISSUE TITLE
Alert stretches horizontally across entire window

### ISSUE THREAD

**Issue by galcott** [craftpip/jquery-confirm#268]
I'm testing the plugin  using this code 
`$.alert({
   type: 'red',
   title: 'Error',
   content: 'This is the error message' ,
   buttons: {
   okay: {  text: 'OK', btnClass: 'btn-blue'  }
   }
});
`
I get an alert window that stretches across the entire browser window. Why would this happen? I haven't modified any of the css.
![alert](https://cloud.githubusercontent.com/assets/4509764/26257454/b500af64-3c8e-11e7-939e-fd8e67901614.jpg)

**Comment by craftpip** [comment]
Do you have Bootstrap installed ?
