### ISSUE TITLE
prevent close on submit prompt

### ISSUE THREAD

**Issue by z1haze** [craftpip/jquery-confirm#269]
I am using a prompt dialog to submit a form and make an ajax call, I'd like to wait to close the dialog until i have a successful response, otherwise i want to display an error and keep the dialog shown. I cant seem to figure out how to keep the dialog shown when submit is clicked.

**Comment by craftpip** [comment]
You can return false in the button action. that will prevent the modal from closing.
```js
$.confirm({
    buttons: {
        test: function(){
            return false; // clicking this button will not close the modal.
        }
    }
})
```

**Comment by z1haze** [comment]
right but $.ajax is asyncronous, so how do i tell it to wait for the call to finish?

**Comment by z1haze** [comment]
That doesn't help. I needed to make an Ajax call in the button action and wait for the call to complete before closing

**Comment by craftpip** [comment]
Alright i got you, try this,
The modal will show a loading message when the call is made.

```js
$.confirm({
    buttons: {
        test: function(){
            this.buttons.test.setText('Loading..'); // let the user know 
            this.buttons.test.disable(); // disable more clicks
            var that = this;
            setTimeout(function(){
                that.close(); // Close when the async work is done. or show error messages etc.
            }, 2000);
            return false; // don't close at first.
        }
    }
});
```

**Comment by z1haze** [comment]
Yea I pretty much did that yesterday when i read through the api. something like this for anyone else who has this issue. I like the lib its nice. I think you should include a easy feature to handle that though, it seems pretty common to want to wait for the call to finish before closing.


```
$.ajax({
  url: '/manage/' + $link.data('orderContentId') + '/cancel',
  method: 'post',
})
  .then(function (data) {
    jc.close();
    location.reload();
})
  .catch(function (data) {
});
```

**Comment by z1haze** [comment]
Final question on this.. you have a way to show a spinner during the loading of the modal, anywy to reverse that process to slide up the content of the modal, and show the loading indicator while im making the ajax call? If I have to do it on my own thats fine im just curious.

**Comment by craftpip** [comment]
Okay, there is this private method `jc.showLoading(boolean)` available, passing in true or false will show or hide the loading spinner. It might cause UI problems if used after the modal is loaded.
👍

**Comment by z1haze** [comment]
Yea it looks like showLoading(false) doesnt bring back the old ui. it just keeps the loader.

**Comment by z1haze** [comment]
have you had a chance to look into this yet? showLoading(false) doesnt work.

**Comment by craftpip** [comment]
Sorry @z1haze, You'll have to make your own loading spinner with it. I will surely work on the in built loading spinner when i get time.

**Comment by z1haze** [comment]
hey man I went through your lib and found out that the behavior is already built in, maybe you just forgot. There is a method called hideLoading, so a simple showLoading, hideLoading did the trick. Nice Lib!
