### ISSUE TITLE
Set values in form

### ISSUE THREAD

**Issue by cesarfinal1** [craftpip/jquery-confirm#272]
I load a form via ajax and i set this such as content, i am trying set the values to the inputs of this form, but when the form is showing the form is reset automatically

**Comment by RaedQumsieh** [comment]
you must know that every element in the Content will be destroyed when you Close the jquery-confirm. so when you reopen it, all values will be reset.  If you want to set the values on open event use the "onOpenBefore" or "onContentReady" (see Callbacks in the dokumentation).

**Comment by cesarfinal1** [comment]
I appreciate your attention, I have read the documentation but those calls are not available for the version I use, I am currently working with the version 2.5.1

**Comment by craftpip** [comment]
@cesarfinal1 
I highly suggest to update.
