### ISSUE TITLE
How to stop page redirecting before confirmation of jconfirm ?

### ISSUE THREAD

**Issue by TonyStark001** [craftpip/jquery-confirm#275]
Let's consider my jsfiddle example [https://jsfiddle.net/9m1Lg6mz/1/](https://jsfiddle.net/9m1Lg6mz/1/)
In ordinary jquery confirm, we will simply **return confirm('Are you sure?')** . It will return true or false,then anchor tag action will be depends on that.
Need some help.

**Comment by craftpip** [comment]
Please see #229 ,
you will have to preventDefault the default action, and then programmically redirect the user to the anchors href,

**Comment by gficher** [comment]
Take a look https://jsfiddle.net/gficher/z8b3czmx/
