### ISSUE TITLE
Uncaught TypeError: $.confirm is not a function

### ISSUE THREAD

**Issue by KaapSlap19** [craftpip/jquery-confirm#277]
Hello i can not resolse this bug with my script js. 
I have include the differents script for Jquery and `Jquery-confirm.`

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://rawgit.com/craftpip/jquery-confirm/master/js/jquery-confirm.js"></script>`

My JS code : 

`$(document).ready(function () {

        $('#bouton_add_ligne').on('click', function () {

            var jc = $.confirm({
                title: 'Prompt!',
                content: '' +
                '<form action="" class="formName">' +
                '<div class="form-group">' +
                '<label>Enter something here</label>' +
                '<input type="text" placeholder="Your name" class="name form-control" required />' +
                '</div>' +
                '</form>',
                buttons: {
                    formSubmit: {
                        text: 'Submit',
                        btnClass: 'btn-blue',
                        action: function () {
                            var name = this.$content.find('.name').val();
                            if (!name) {
                                $.alert('provide a valid name');
                                return false;
                            }
                            $.alert('Your name is ' + name);
                        }
                    },

                },
                onContentReady: function () {
                    // bind to events
                    var jc = this;
                    this.$content.find('form').on('submit', function (e) {
                        // if the user submits the form by pressing enter in the field.
                        e.preventDefault();
                        jc.$$formSubmit.trigger('click'); // reference the button and click it
                    });
                }
            });

        });

    });`

My error : Uncaught TypeError: $.confirm is not a function
    at HTMLButtonElement.<anonymous> (casier.js:5)
    at HTMLButtonElement.dispatch (app.js:29)
    at HTMLButtonElement.g.handle (app.js:29)

i have already swap $ to Jquery.

**Comment by KaapSlap19** [comment]
Hello finnaly i found the bug and it's resolved 
Thx

**Comment by craftpip** [comment]
Glad it worked ! 👍

**Comment by mpiontek** [comment]
Would be very helpful - when someone has a problem and solved it on his own - to post the solution, so that other people can participate.
