### ISSUE TITLE
Stacked Confirmation

### ISSUE THREAD

**Issue by gangwarj** [craftpip/jquery-confirm#278]
Please help me with using jquery-confirm V3 for stacked confirmation.
Thanks in advance.

**Comment by craftpip** [comment]
Hello @gangwarj 
You call `$.confirm` one after the other to stack the modals, the one on the topmost will be the active one.

**Comment by gangwarj** [comment]
Thank You , work great now. :)

**Comment by craftpip** [comment]
Glad to help 👍
