### ISSUE TITLE
Set dynamic content

### ISSUE THREAD

**Issue by Thirunav** [craftpip/jquery-confirm#279]
I want to changes the content dynamically. The content will be returned by the service class method.

So how can I set that service class returned data as a content of the confirm dialog.

Thanks in advance.

**Comment by craftpip** [comment]
Hello @Thirunav 
You can use the method `setContent()` method to replace the content when the class returns the data.
example:
http://craftpip.github.io/jquery-confirm/#ajaxpromise

**Comment by Thirunav** [comment]
Thanks for your help it's working fine. but I couldn't able to set any of icons. I tried the below code :+1: 
`										useBootstrap: false,
                                        title: 'News And Announcements',
										icon: 'fa fa-question',
										theme: 'modern',
										closeIcon: true,
										animation: 'scale',
										type: 'orange',
`

and I want to set my custom icon. so could you please suggest me how can I achieve them?

**Comment by craftpip** [comment]
>  I couldn't able to set any of icons. 

Please check if you have the Font awesome package installed, if not download it from here, 
http://fontawesome.io/

> set some content below the buttons

This is not possible, with jconfirm. If you have a requirement of doing this, 
you can disable the jconfirm buttons and add your own buttons in the content area.

**Comment by Thirunav** [comment]
I have a Icon images in my project, is it possible to refer that path for icon?

**Comment by craftpip** [comment]
You can do that with CSS, 
by creating a class that has background-image for that image.
