### ISSUE TITLE
Question performance animation

### ISSUE THREAD

**Issue by usb248** [craftpip/jquery-confirm#28]
Hello,

 In your code, i see :
```javascript
this.$el.find('.jconfirm-bg').animate({
    opacity: 0
}, this.animationSpeed / 3);
```
Why you don't use CSS3 animation ? It's much more optimized, no ?

**Comment by usb248** [comment]
Moreover, i don't want open an other issue for this. I ask me why a method like 'setTitle' doesn't exist ?

**Comment by craftpip** [comment]
Hello @usb248 

Yes CSS3 will be much better, i don't remember why i used jQuery animate here. 
& Yes adding the 'setTitle' method will be useful, i will add more methods to to change attributes, as this goes ahead. 

Thanks for the suggestion ! :+1:
