### ISSUE TITLE
How to show large data in alert box?

### ISSUE THREAD

**Issue by gangwarj** [craftpip/jquery-confirm#280]
I have seen an example where the large data is loaded like this
$.confirm({
    content: 'url:text.txt',
    title: 'Title'
}); 
but i have the value stored in a variable and if i try to use it in the aboce way, it does not show full data.
is it possible to do it without loading it from the url?

**Comment by craftpip** [comment]
Hello @gangwarj 
`url:` is to load any kind of data via ajax, if you have data in a variable you can load it like so,

```js 
var largeContent = "This is the large content here. <br> anything here"
$.confirm({
content: largeContent,
title: 'Title'
});
```

**Comment by gangwarj** [comment]
Thanks a lot for helping @craftpip , actually previously i was trying to preview a large string without spaces and it was not working but if the string has spaces then it is working fine.
If you want you can work on it . 
Thanks again :)

**Comment by craftpip** [comment]
If the string does not have spaces, it will shown in one line, it must have breaks `<br>` or spaces in it.
