### ISSUE TITLE
How to Custome Design in Dialog box?

### ISSUE THREAD

**Issue by ChandrakantDevani** [craftpip/jquery-confirm#283]
how to use krajee file-input plugin in dialog box for document/Image upload..

**Comment by craftpip** [comment]
For example here is how a datepicker plugin is used.
```js
$.confirm({
    content: '<input type="date" id="mydatepicker">',
    onContentReady: function(){
        this.$content.find('#mydatepicker').datepicker():
    }
})
```
this will give you an idea on how to use a plugin inside the modal.

**Comment by ChandrakantDevani** [comment]
Thanks for your help it's working fine

**Comment by craftpip** [comment]
Glad i could help 👍
