### ISSUE TITLE
Calling this jquery-confirm from a PHP IF statement

### ISSUE THREAD

**Issue by daybreak10** [craftpip/jquery-confirm#287]
I would like to be able to echo '<script type="text/javascript">update_confirm();</script>'; inside of an if/else statement that prompts the user to confirm yes or no before I do an update to the database row.   But for some reason, I can only get the windows confirm() to actually popup, not this custom $.confirm() function provided with your toolset.  

Here is my function in the  head tag (disregard the #csid section as that is for something else):
`    <link rel="stylesheet" href="includes/jquery-confirm.min.css">
    <script src="includes/jquery-confirm.min.js"></script>
    <script>
        $(document).ready(function() {
          $('#csid').bind('change', function(event) {
              console.log($("#csid").val());
              var cs_id = $("#csid").val();
              var schema_name = '<?php echo $schema ?>';
              console.log(schema_name);
              console.log(cs_id);
              if(cs_id=="NEW") {
                  var cleartxt = "";
                  $('#new').show();
                  $('#existing').show();
                  $('#newSection').val(cleartxt);
              } else {
                  $('#new').hide();
                  $('#existing').show();
                  $.ajax({
                      type: 'Post',
                      url: 'display_custext.php',
                      data: {
                          csid: cs_id,                  //passes the variable cs_id as the $_POST['csid'] to the designated page
                          schema: schema_name,          //passes the variable schema_name as the $_POST['schema'] to the designated page
                      },
                      success: function (data) {
                          var obj = $.parseJSON(data);
                          var result = "";
                          $.each(obj, function () {
                              result = result + this['PROTOCOL_STEP_CUSTOM_TEXT'];     //create what will be passed to the .html tag in the ID='newSection' tagged section of html
                          });
                          $('#newSection').val(result);        //returns the value to display in the <input> tag
                      }
                      });
              }
          });
          function update_confirm() {
              var confirmyn = "";
              $.confirm({
                  title: 'Confirm!',
                  content: 'Please confirm...',
                  buttons: {
                      yes: function () {
                          $.alert('Confirmed!');
                          confirmyn = 'Y';
                      },
                      no: function () {
                          $.alert('Aborted!');
                          confirmyn = 'N';
                      },
                  }
              });
          }
        });
    </script>`

**Comment by daybreak10** [comment]
Wow, sorry, it didn't save my formatting when I had it encapsulate the code.  Here it is in just text format.

    <link rel="stylesheet" href="includes/jquery-confirm.min.css">
    <script src="includes/jquery-confirm.min.js"></script>
    <script>
        $(document).ready(function() {
          $('#csid').bind('change', function(event) {
              console.log($("#csid").val());
              var cs_id = $("#csid").val();
              var schema_name = '<?php echo $schema ?>';
              console.log(schema_name);
              console.log(cs_id);
              if(cs_id=="NEW") {
                  var cleartxt = "";
                  $('#new').show();
                  $('#existing').show();
                  $('#newSection').val(cleartxt);
              } else {
                  $('#new').hide();
                  $('#existing').show();
                  $.ajax({
                      type: 'Post',
                      url: 'display_custext.php',
                      data: {
                          csid: cs_id,                  //passes the variable cs_id as the $_POST['csid'] to the designated page
                          schema: schema_name,          //passes the variable schema_name as the $_POST['schema'] to the designated page
                      },
                      success: function (data) {
                          var obj = $.parseJSON(data);
                          var result = "";
                          $.each(obj, function () {
                              result = result + this['PROTOCOL_STEP_CUSTOM_TEXT'];     //create what will be passed to the .html tag in the ID='newSection' tagged section of html
                          });
                          $('#newSection').val(result);        //returns the value to display in the <input> tag
                      }
                      });
              }
          });
          function update_confirm() {
              var confirmyn = "";
              $.confirm({
                  title: 'Confirm!',
                  content: 'Please confirm...',
                  buttons: {
                      yes: function () {
                          $.alert('Confirmed!');
                          confirmyn = 'Y';
                      },
                      no: function () {
                          $.alert('Aborted!');
                          confirmyn = 'N';
                      },
                  }
              });
          }
        });
    </script>

**Comment by craftpip** [comment]
hello @daybreak10 
try using `jQuery.confirm`, does it give you any errors in console ?
