### ISSUE TITLE
Bug in theme Modern with use Ajax

### ISSUE THREAD

**Issue by GerardMetal** [craftpip/jquery-confirm#289]
I'm calling some data from the database, using the `return $.ajax ({ ... })` method; But the animation load is lost, not a big problem but it is a simple observation.
I'm sorry for my english.

![captura de pantalla 89](https://user-images.githubusercontent.com/23560749/27841562-2fd240c4-60c8-11e7-92c7-9fc315e70248.png)

**Comment by craftpip** [comment]
Thanks for the heads-up @GerardMetal 
I will have a look on this,
