### ISSUE TITLE
Keyup events should be restricted to current jConfirm instance only

### ISSUE THREAD

**Issue by eytanchen** [craftpip/jquery-confirm#291]
I have  jConfirm used as a modal with an iframe that loads a page that also uses jConfirm for submition.
my problem is that using ESCAPE key to cancel submition also closes the modal. Can't find a way around it.

I think  the correct solution would be to restrict keyup events to current instance of jConfirm, so that it would not be activated in other jConfirm elements currently active (as you have done with the keyup/keydown problem).

**Comment by craftpip** [comment]
Keyup events are restricted for the topmost instance of jconfirm, but in the current window.
but as you're loading a iframe inside a jconfirm, both of them are the topmost instance in their window scope. 

i would recommend not to open a modal in an iframe, instead use the parent window to open jconfirm modal.
