### ISSUE TITLE
Onload confirm popup 

### ISSUE THREAD

**Issue by arun-techmanyata** [craftpip/jquery-confirm#292]
instead of on click i need the popup to appear onload itself.

Here's my code

[index.zip](https://github.com/craftpip/jquery-confirm/files/1145428/index.zip)

<script type="text/javascript">
    $(window).on('load',function(){
        $('#simpleConfirm').modal('show');
    });
</script>

anchor id="simpleConfirm" href="" class="btn btn-primary">Click me<endtag>
(hope yo got my HTML :) , not sure how to display the code. Please find the attachment for the exact file)

**Comment by gficher** [comment]
Here you go

```
$(function() { // This runs when the page finishes loading
	$.confirm({
		title: 'Title',
		content: 'Hello, user!',
		buttons: {
			cancel: {
				keys: ['esc'],
			},
			confirm: {
				text: 'Great!',
				btnClass: 'btn-primary',
				keys: ['enter'],
				action: function () {
					// Maybe do something here
				},
			},
		}
	});
});
```
