### ISSUE TITLE
Using $.confirm in a loop

### ISSUE THREAD

**Issue by atul4drupal** [craftpip/jquery-confirm#293]
Hello,

I have a use case where I have to use the confirm dialogue in .each() function and on every iteration a confirm dialogue is to be shown with some dynamic values from the DOM.

Problem is that the confirm dialogue is appearing in reverse order that is... each() loop executes first doing all its iterations and after each() loop is done confirm dialogue appears in reverse order i.e it shows value from the last iteration in each() loop...

instead of showing confirm dialogue in each iteration it is showing it after the each() loop ends and that too its just showing values from last each() iteration.

does any one has faced this, how can this be worked around/solved

Thanks for any help/suggestion in advance.

**Comment by craftpip** [comment]
You should not create a jconfirm instance for each for loop. instead, store the data in the `div` you're rendering and bind it to an event to open jconfirm modal. 

```html
<div data-something="mydata" class="jconfirm-action"></div>
<div data-something="mydata" class="jconfirm-action"></div>
```
```js
$('.jconfirm-action').click(function(){
    var data = $(this).data('something'); // get your data,
    $.confirm({
        ... // render modal for the data.
    })
})
```
