### ISSUE TITLE
no button auto close 

### ISSUE THREAD

**Issue by cdmin207078** [craftpip/jquery-confirm#294]
Hi, 
this is a great project, thank you before. 
i have a question , When i remove all buttons , how can i setting auto closing ??

![image](https://user-images.githubusercontent.com/1762278/28203659-39771e00-68ad-11e7-871d-1a7abdec84b8.png)

i think we need  some like  **message**  or **info** component. that only show some message, with no button ,no closing icon , and can i setting auto closing. 

tkx, best Regards.

**Comment by craftpip** [comment]
Currently buttons must be there to enable autoClose. Some event must be triggered when the modal closes.
