### ISSUE TITLE
On click body goes to the top of the page

### ISSUE THREAD

**Issue by acristinatorres** [craftpip/jquery-confirm#295]
I'm facing this issue whenever I use jquery confirm with a bootstrap modal, I've realized that this happens when i click in the okay button in the confirm window because when I close the modal it doesn't happend.

It's kind of annoying when the modal window is very down in the scrollbar and i have to continue a process down deep an have to get back to the bottom again every time i have the success confirmation.

**Comment by craftpip** [comment]
Hey, @acristinatorres 
can you please post a jsfiddle of this?
you might consider to replace bootstrap's modal with jconfirm for the whole thing.

**Comment by omidakhavan** [comment]
@craftpip 
Hey 

I have same issue too, let me explain : 
I have text area in bottom of page when i click on text area modal will open up but i scrolled to top of the page and when i confirm or submit my modal then page will be scroll to bottom of page on my text area....

**Comment by acristinatorres** [comment]
@craftpip It's hard to replicate it in a jsfiddle because it doesn't happens all the time
