### ISSUE TITLE
Confirm and any plugins

### ISSUE THREAD

**Issue by ProqMiri** [craftpip/jquery-confirm#296]
Hello. When adding any plugins (for exam select2, datepicker, ...) to confirm, the plugin doesn't display correctly. The plugin is displayed under the confirm. So, we must increase  z-index property of the plugin and decrease z-index property of the confirm. Please, solve this problem. 

Thanks you in advance!

**Comment by craftpip** [comment]
@ProqMiri this is right, i will work over this. 
for a workaround you can do 
```
var jc  = $.confirm();
jc.$el.css('z-index', 9999); // to decrease the z-index.
```

**Comment by ProqMiri** [comment]
Thanks for information...
