### ISSUE TITLE
Loading with the dark theme

### ISSUE THREAD

**Issue by agentphoenix** [craftpip/jquery-confirm#297]
I noticed when using the dark theme that when you load content with Ajax, the background of the loading box is white before the content is finished loading. When everything is ready to go, it transitions to the dark background.

I dug in and found that the `.jconfirm .jconfirm-box.loading:before` rule explicitly sets a background of white. I updated that in my own stylesheet to make the loading box the same color as the dark theme box, but figured that would be a pretty easy fix to throw in to make sure the dark theme has a loading screen with a background color that matches itself for loading Ajax content.

**Comment by craftpip** [comment]
@agentphoenix right, i have been working on this to fix issues with themes. 
Thanks 👍
