### ISSUE TITLE
Wait ajax after the user confirm action

### ISSUE THREAD

**Issue by qwertyuiope** [craftpip/jquery-confirm#299]
On the prompt option, there is anyway to show a loading after the user submit? I was looking for something like this: https://craftpip.github.io/jquery-confirm/#ajaxloading but instead of waiting to load the modal, I would like to wait the ajax after the user confirm action

**Comment by craftpip** [comment]
Yes, you can use the methods, `jc.showLoading(disableButtons: boolean)` and `jc.hideLoading(enableButtons: boolean)` these methods have not been documented yet.

**Comment by dchillman123** [comment]
I saw the showLoading/hideLoading, but it isn't clear to me how to actually incorporate them. for example, in the confirm action I make an ajax call and want to showLoading while it runs, and hide loading when it returns.  Do you have an example?  thanks
