### ISSUE TITLE
Submit Form ( POST ) after confirmation

### ISSUE THREAD

**Issue by marcoczen** [craftpip/jquery-confirm#300]
Hi,

I have a bootstrap form with a submit button as below;

` <button type="submit" class="btn btn-primary" name="button_deluser"  > Delete Selected User </button> `

When the button is clicked - the form is submitted. I would like a confirmation box (Yes - Delete, No ).
I dont understand how to incorporate jquery-confirm into the button above from the documentation provided.

Any ideas ? Alert - Jquery newbie here.

**Comment by marvinkueppers** [comment]
Example form:
<form id="target" action="destination.html">
  <input type="text" value="Hello there">
  <input type="submit" value="Go">
</form>

Your jconfirm handler:
$.confirm({
            title: 'Confirm!',
           content: 'Simple confirm!',
          buttons: {
          confirm: function () {
                    $( "#target" ).submit(); <--- Here's the needed code
            },
              cancel: function () {
              $.alert('Canceled!');
          },
    
       }
});

The new code line selects the form and creates a jquery object ("$('#target') and then calls the function "submit()" on this jquery-object.
Please check the jquery docs (https://api.jquery.com/submit/) for further details.

**Comment by marcoczen** [comment]
@marvinkueppers  - Many many thanks.
Will try and revert.

Next;

``
EDIT: If you want to use a button-click to send the form, you can do it with:
Your button (give it an id!!):
<button type="submit" id="submitXY" class="btn btn-primary" name="button_deluser" > Delete Selected User </button>

Needed jquery inside your confirm-function:
$('#submitXY').click();
``

What is the better practice ? How do you do it ?
A. User gets a popup confirm box to cancel/ approve ? 
B. Or use the button click to send the form right away ?

Once again many thanks for the input. Its very appreciated.

**Comment by zagarskas** [comment]
This is great...
but can not get the form to "close" after the submit
```
confirm: {
			text: 'Confirm',
			btnClass: 'custom-btn',
			action: function(){
				$("#start_long_ajax_loop").submit();
				$.close(); // not working
			}
		},
```

**Comment by jq2034** [comment]
https://jquerys.space/questions/prompt-the-user-to-confirm-before-clicking-on-the-submit-button-using-jquery-dialog
