### ISSUE TITLE
Confirm Box takes up width of screen 

### ISSUE THREAD

**Issue by osumakerspace** [craftpip/jquery-confirm#301]
I've got version 2.3.2, trying to use it in wordpress but the confirm box takes up the whole screen. Adding custom column width doesn't have any affect. 
![capture](https://user-images.githubusercontent.com/25520877/28445289-78efc68e-6d91-11e7-8ea2-d07d01b9a732.PNG)
That's martin luther king's speech in the background, use it as a placeholder for a long user entered description, sorry if the language there offends anyone

**Comment by marvinkueppers** [comment]
Hey osumakerspace, poorly I don't know the version 2.3.2, but I did it in the current one with setting a boxWith like:

$.confirm({
    boxWidth: '30%',
    useBootstrap: false,
});
$.confirm({
    boxWidth: '500px',
    useBootstrap: false,
});

Bootstrap has to be disabled to use this!

Maybe you could create your own theme and set the width of class ',jconfirm_box'.
See https://craftpip.github.io/jquery-confirm/themes.html

**Comment by dezguell** [comment]
I resolved the same problem modifying the CSS (.jconfirm .jconfirm-box). But this is not the best solution i guess. 

```
.jconfirm .jconfirm-box {
        background: white;
        border-radius: 4px;
        position: relative;
        outline: 0;
        padding: 15px 15px 0;
        overflow: hidden;
        margin-left: 38.33%; /*(modification)*/
        margin-right: 35%; /*(modification)*/
    }
```

**Comment by craftpip** [comment]
@dezguell which version of the plugin are you using ?, you could use `margin-left: auto, margin-right: auto` for the time being,

**Comment by yhnedison** [comment]
I have the same problem in chrome and IE. Both alert and confirm boxed takes the width of the browser. I'm using version 3.3.4. jQuery 1.11.1, no Bootstrap/
Customize the css did solve the problem, but need to figure out why.
