### ISSUE TITLE
Issues on box size

### ISSUE THREAD

**Issue by jfaderanga** [craftpip/jquery-confirm#302]
hi guys, 

I am so amazed by the greatness of this plug-in! it was awesome!

There's only one thing I encountered, when I use the plugin in Salesforce on a custom button...
the dialog box consumes the width of the window......

not sure if I can do a fix on my end

![screen shot 2017-07-24 at 3 40 55 pm](https://user-images.githubusercontent.com/15375136/28507387-8883f398-7086-11e7-918f-f3b4f68b0f22.png)

**Comment by jfaderanga** [comment]
sorry please consider this as close, I didn't read the whole article..got this fixed...sorry ;D

**Comment by craftpip** [comment]
Cool, closing..

**Comment by paulocoutinhox** [comment]
I have the same error, what is wrong?

**Comment by paulocoutinhox** [comment]
I found the solution: `useBootstrap: false`.
