### ISSUE TITLE
How do I insert HTML tags into content?

### ISSUE THREAD

**Issue by gficher** [craftpip/jquery-confirm#304]
When I set the content var it only gets the text

`content: '<i>Sample text</i>'`

returns "Sample text" without the HTML markup

**Comment by dezguell** [comment]
I tried it with this html fragment and it worked, maybe you need to put your tags into a  HTML form

function exampleHTMLContent() {
    var HTMLContent = '<form  action="" class="FormClass">' +
        '<i>Sample text</i>' +
        '</form>';
    $.confirm({
        title: titulo,
        content: contenidoHTML
    });
}

**Comment by gficher** [comment]
For some unknown reason I didn't manage to do it. Thanks!
