### ISSUE TITLE
Jconfirm on mobile (responsive design)

### ISSUE THREAD

**Issue by reza-irdev** [craftpip/jquery-confirm#305]
Firstly, i should say thank you for the great plug-in :+1: 
My question is how i can make it more responsive on mobile devices or how i can change the theme to  be full-screen on small screens?

**Comment by craftpip** [comment]
Hey @reza-irdev 
you have bootstrap's columns to make it responsive, 
if you want to change the theme, you will have to set the theme manually.

**Comment by reza-irdev** [comment]
@craftpip tnx.
I don’t using the bootstrap for this project. So i should change it manually with CSS @media :/

**Comment by craftpip** [comment]
@reza-irdev you can do it with javascript too,
listen to the window's resize event. and accordingly change the modal's theme via 'jc.setTheme()' method
