### ISSUE TITLE
How works setBoxWidth method? 

### ISSUE THREAD

**Issue by dezguell** [craftpip/jquery-confirm#306]
First of all nice work with that pulg in
I need to set different values for the dialog-box width. I saw that in the 3.2.3 version where includes the setBoxWidth method, but didn't find documentation about it.

**Comment by gficher** [comment]
First, to use the setBoxWidth method you should get the dialog reference like so:
```
var box =  $.confirm({
    useBootstrap: false,
});
```
Note that you can only use setBoxWidth when not using bootstrap.
Then, you can call the method
```
box.setBoxWidth();
```

It calls the following function:
```
function() {
    if (this.useBootstrap) {
        console.warn("cannot set boxWidth, useBootstrap is set to true");
        return;
    }
    this.$jconfirmBox.css("width",this.boxWidth);
}
```

this function updates the width according to the boxWidth content, so if you want to change de dialog width change this var first
```
box.boxWidth = "1000px";
box.setBoxWidth();
```

**Comment by craftpip** [comment]
This was a bug, i missed the argument in setBoxWidth, 
I've merged correct code from @gficher 
will release it soon.

**Comment by dezguell** [comment]
I resolved the issue setting the _useBootstrap_ as false and setting a _boxWidth_ property with a parameter via javascript
```
  $.confirm({
        title: title,
        content: HTMLContent,
        type: color,
        boxWidth: width_percent + '%',
```
