### ISSUE TITLE
issue with angular 4. "confirm does not exist on type 'jQueryStatic' ".

### ISSUE THREAD

**Issue by TechnicalDiary** [craftpip/jquery-confirm#309]
I am trying to create angular 4 Directive with the help of this directive. but I am getting an error "confirm does not exist on type 'jQueryStatic' " 

```

@Directive({ 
  selector: '[confirm]' 
})
export class ConfirmDirective {
  @Output('confirm-click') click: any = new EventEmitter();
  @HostListener('click', ['$event']) clicked(e) {

    //Error is commig in following code : **confirm does not exist on type 'jQueryStatic'**
    $.confirm({

      buttons: {
        confirm: () => this.click.emit(),
        cancel: () => {}
      }
    });
  }
}
```

please provide the solution asap. Thanks in advance.

**Comment by craftpip** [comment]
on top of the file declare
```js
declare const jQuery: {
    confirm: Function
};
```
and then in your code
```js
jQuery.confirm();
```

I will making a angular4 service soon.

**Comment by rakeshkumarkondle** [comment]
Still getting the same error after adding your code

**Comment by craftpip** [comment]
Can you please make a fiddle ?

**Comment by rakeshkumarkondle** [comment]
Well, i can't create a fiddle as i'm using this code in a ASP.net project.  I can provide you the code block.

confirm.directive.ts ::
---------------------
import { Component, Output, HostListener, EventEmitter, Directive, ElementRef, NgModule, Input   } from '@angular/core'
declare const jQuery: {
    confirm: Function
};

@Directive({
    selector: '[confirm]'
})
export class ConfirmDirective {

    @Output('confirm-click') click: any = new EventEmitter();
    
    @HostListener('click', ['$event']) clicked(e: any) {
        console.log('aaa', jQuery);
       jQuery.confirm({
            buttons: {
                confirm: () => this.click.emit(),
                cancel: () => { }
            }
        });
    }

}


<button class="delete" (confirm-click) ="onDeletRow(row)" confirm>
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
 <span class="glyphicon glyphicon-trash"></span>
                                </button>


My module.ts :: 
----------------


import { ConfirmDirective } from './confirm.directive';

**Comment by rakeshkumarkondle** [comment]
![image](https://user-images.githubusercontent.com/25902932/35512024-feebd1d8-0549-11e8-98c3-6353d0b4aba5.png)

**Comment by rakeshkumarkondle** [comment]
I got it. By adding
 import '/node_modules/jquery-confirm/js/jquery-confirm.js'; to my confirm.directive ts i fixed the issue. thanks anyways
