### ISSUE TITLE
Accept inputs

### ISSUE THREAD

**Issue by lavmo** [craftpip/jquery-confirm#31]
Hi, it is nice jquery plugin. I want to see some input feature, let say for example, a dialog that asks for input of your name, just something like that,.

Hope you consider my suggestion.

God bless

**Comment by craftpip** [comment]
Hey @lavmo 

You can use Jconfirm to get input from the user,
Here is a short example: 

```js
$.confirm({
    title: 'Enter your name',
    content: '<input type="text" class="user_name">',
    confirm: function(){
        var user_name = this.$b.find('.user_name').val();
        alert(user_name); 
        return false; // prevents closing of dialog.
    }
})
```

Thank you for the kind words. :+1:

**Comment by craftpip** [comment]
You can also see this example @ http://craftpip.github.io/jquery-confirm/
User the heading "Practical Uses"  button "Act like Prompt".

**Comment by lavmo** [comment]
thanks, nice one, 
actually what I did is using ajax in content
```javascript
$.confirm({
    content: function($o) {
         $.ajax({
             //ajax call to form here and some callbacks
         });
    }
});
```
I did not think about that, but many thanks

**Comment by craftpip** [comment]
:+1: 
```js
$.confirm({
    content: function($o) {
         return $.ajax({
             //ajax call to form here and some callbacks
         }).done(function(data){
            $o.setContent(data);
         });
    },
    confirm: function(){
         this.$b // you can find the elements u need here.
    }
});
```
