### ISSUE TITLE
Problem with scaling animation

### ISSUE THREAD

**Issue by raffaelecolleo** [craftpip/jquery-confirm#319]
Hi all,
I am having problems centring the confirm box.
Let me explain:
If the page does not have enough content to add the vertical scroll to the browser, it works perfectly.
If the page has an amount of content that it is necessary to add the vertical scroll to the browser, then the confirm box will not be vertically centred to the window.

Any Idea Why?

I am using version 3.2.3

**Comment by craftpip** [comment]
Can you add a jsfiddle for this ?
