### ISSUE TITLE
$.alert is not a function

### ISSUE THREAD

**Issue by cuong-nm** [craftpip/jquery-confirm#32]
Hi !

Can you help me about jquery-confirm? In my project, I use jquery-confirm.js to show alert dialog and then go back to previous page. I call it in code behide and java-script function(alert dialog) was stored in messageBox.js file.

messageBox.js here:

function AlertMsgThenGoBackHistory(message)
   {
   
           $.alert({
            title: 'Alert!',
            icon: 'fa fa-infomation',
            content: message,
            theme: 'white',
            confirmButton: 'Close',
               confirmButtonClass: 'btn-primary',
               cancelButtonClass: 'btn-primary',
            confirm: function(){
                window.history.go(-1);
            }
        });
   };

In my aspx page, I include all libs for jquery-confirm. 
In code behide,I call to AlertMsgThenGoBackHistory:

 string Message = string.Format("<script type='text/javascript'>AlertMsgThenGoBackHistory('{0}');</script>", "Wrong data, back to previous page !");
                    ScriptManager.RegisterClientScriptBlock(this, GetType(), "message", Message, false);

But when I run my project, alert not show and it has an error 
$.alert is not a function

Can you help me, please ???

Thanks !!!!

**Comment by craftpip** [comment]
Hello @cuong-nm, 

This can happen in 2 scenarios,
1. jQuery is not present in your project (enter jQuery in console to confirm it.)
2. $.noConflict() is done, that means  $ is not alias of jQuery.

Try if  this works.
```javascript
jQuery.confirm({}) // is same as $.confirm({})
```
If it still doesn't work, check your browsers console and let me know the output.

**Comment by tommwenda** [comment]
I am experiencing this too, $.confirm() works, but $.alert(). throws an error. this is on the same page.

**Comment by craftpip** [comment]
@tommwenda , i guess u have some other plugin using the $.alert name

**Comment by AlirezaDana** [comment]
I have the same issue.
all other plugins are disabled and still error happens!
every file of plugin & jquery are carefully loaded.

code:
`$.alert('Confirmed!');`

error:
> TypeError: $.alert is not a function

**Comment by ngomyhanh255** [comment]
I tried everything but it didn't work.
help me...

--- code
                        $.noConflict();  
                        $.alert({
			    icon:'fa fa-warning',
			    title: 'Warning',
			    content: 'Not be empty',
			    type: 'orange',
			    useBootstrap: false
		    });
--- error
TypeError: $.alert is not a function

---- But when I use in header(wordpress) it works find.
