### ISSUE TITLE
$.fn.confirm with Dynamically Added Elements

### ISSUE THREAD

**Issue by thekendog** [craftpip/jquery-confirm#321]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[] feature request
[x] support request

**Current behavior:**
Using the $.fn.confirm method, clicking elements that have been dynamically added after the DOM is loaded does not work.

**Expected behavior:**
Clicking those elements works as it normally should.

**Steps to reproduce:**
Add new element to DOM using jQuery and then try and target it.

**Related code:**

insert any relevant code here

**Other information:**
Is there any way to get this to work?

**Comment by craftpip** [comment]
I don't understand the requirement, can you please reopen the issue with a workflow ?
