### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by josesanches1** [craftpip/jquery-confirm#329]
When implement an iframe, the content loads twice.
What is the best way to implement iframe with the plugin.

I'm using

var height = 500;
var width = 800;
car url = ....
var iframe = "<iframe name = 'iFrameBackOffice' frameborder = '0' marginwidth = '0' marginheight = '0' allowfullscreen scrolling = 'no' style = 'border: none; padding: 0px; margin: 0px;' width = '"+ width + ''' height = '"+ height +"' src = '"+ url +"'> </ iframe> ";

$ .confirm ({
title: '',
content: iframe,
alignMiddle: true,
useBootstrap: false,
boxWidth: (height + 30),
buttons: {
Accept: function () {
alert ("OK")
}
}
});

**Comment by craftpip** [comment]
Please create a fiddle to demonstrate. and reopen the issue
