### ISSUE TITLE
Confirm dialog dissapears without even giving time to click

### ISSUE THREAD

**Issue by cursomicroforum2015** [craftpip/jquery-confirm#33]
This is something weird, because it happens in some pages and in others don´t. The confirmation dialog appears briefly in the page without even giving time to click on it, and then (without neither performing the function inside confirm nor cancel), just quickly disappers. Is probably not an issue directly related with the plugin itself, but the truth is that when I try with the standard javascript confirm I never have that problem. If someone could give a hint about what could be the problem I would be very thankful.

**Comment by craftpip** [comment]
This is a weird behavior, 
If  the dialog disappears without animations, then its because the element in DOM is removed,
You should check the DOM for changes and Keep the container as 'body'. 

This is a very odd issue, can you please show me the snippet you're using to init the plugin ?
