### ISSUE TITLE
Set Autofocus on confirm box

### ISSUE THREAD

**Issue by Vraj126** [craftpip/jquery-confirm#331]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request

**Current behavior:**

**Expected behavior:**

Autofocus on "Confirm"/ or any button on opening up alert/confirm box
Capabilities to Add Id to default buttons
**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by craftpip** [comment]
adding ID to a button is not available, alternatively you can set classes to the button you want to focus.
and focus it on the `onOpen` callback
