### ISSUE TITLE
Nextline character is not supported inside confirm content

### ISSUE THREAD

**Issue by ShrutikaAgrawal** [craftpip/jquery-confirm#332]
**jquery-confirm version:**
jquery confirm version 3.3

I'm submitting a support request.
Issue experienced is that the next line character is not working inside the confirm content.

Please help.

**Current behavior:**
Everything is being printed in the same line

**Expected behavior:**
characters after next line should come in next line

**Steps to reproduce:**
create a confirm button with given code,
see the output.

**Related code:**
```
$.confirm({
    title: 'Game Over!',
    content: 'You Won the game' + '\n' + 'Your total score is:' + this.totalcount + '\n' + 'Do you want to continue the game?',
     buttons: {
        ok: function () {
               window.location.reload();
               },
        cancel: function ()           
           { window.location.reload(); 
            },
           }
});

**Comment by webprogramozo** [comment]
Hi,

you need to provide HTML content to the content property. If you want to use newlines you may use <br> tags.

**Comment by ShrutikaAgrawal** [comment]
even <br> tag didn't work for me.

**Comment by ShrutikaAgrawal** [comment]
Even "<br>" tag didn't work for me.

**Comment by ShrutikaAgrawal** [comment]
Even br tag didn't work for me.

**Comment by webprogramozo** [comment]
BR tag must work. (I tested: http://prntscr.com/go8q9g) Can you provide live example for the problem?

**Comment by webprogramozo** [comment]
BR tag must work. (I tested: http://prntscr.com/go8qjx) Can you provide live example for the problem?

**Comment by ShrutikaAgrawal** [comment]
now its working, Actually My mistake I didn't write BR tag under the quotes("").
