### ISSUE TITLE
How to make the customer validation?

### ISSUE THREAD

**Issue by Naren-hybreeder** [craftpip/jquery-confirm#333]
Hello, 
I am using this plugin. This is awesome!.
I am using a Prompt example. I have to use the email field instated of text field so I set type="email".
Now, How do I set the validation on it?
I tried in action function but it's not working. Would you help me in this?
action: function () {
                var name = this.$content.find('.name').val();
                if(!name){
                    $.alert('Email field is empty');
                    return false;
                }
        elseif(!preg_match("/^[_\.0-9a-zA-Z-]+@([0-9a-zA-Z][0-9a-zA-Z-]+\.)+[a-zA-Z]{2,6}$/i",$name)) {
                  $.alert('Email format invalid');
                    return false; 
            }
            else{
                $.alert('The reset password email has been sent on ' + name);
              }
            }

**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by craftpip** [comment]
you'll have to use html5 validations, or do the validations yourself on submit.
