### ISSUE TITLE
Alert seemed corrupted and pixels are flickering

### ISSUE THREAD

**Issue by pda-code** [craftpip/jquery-confirm#337]
**jquery-confirm version:**
v3.3.2

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
In a simple alert dialog, the alert is corrupted. There is a white gap around the alert and there are pixels that flickers on the dark background

![image](https://user-images.githubusercontent.com/10973438/31373684-b5d7a344-ada3-11e7-94a3-980c89462fab.png)

When i remove display:table-cell and display:table-row, the alert is fixed but of course looses orientation

![image](https://user-images.githubusercontent.com/10973438/31373809-203406b0-ada4-11e7-9848-a8f52669e5e1.png)

Testes On Chrome

**Comment by craftpip** [comment]
That's weird, this must be because of the existing CSS interfering with jconfirm.
