### ISSUE TITLE
Uncaught TypeError: $.confirm is not a function - jQuery Version ?

### ISSUE THREAD

**Issue by mpiontek** [craftpip/jquery-confirm#338]
**jquery-confirm version:**
v3.3.2

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request

**Current behavior:**

On click the console logs an error: "Uncaught TypeError: $.confirm is not a function" and references to jquery.min.js

```
Uncaught TypeError: $.confirm is not a function
    at HTMLParagraphElement.<anonymous> (app.min.js?m=1507793745:1)
    at HTMLDivElement.dispatch (jquery.min.js?m=1507533634:1)
    at HTMLDivElement.v.handle (jquery.min.js?m=1507533634:1)
```

**Expected behavior:**

Open a confirmation window

**Steps to reproduce:**

**Related code:**
```
$.confirm({
                title: 'Artikel von Merkliste löschen?',
                content: 'Sie haben diesen Artikel auf Ihrer Merkliste - sind Sie sich sicher, dass Sie den Artikel entfernen möchten?',
                buttons: {
                    confirm: {
                        text: 'Artikel entfernen [ENTER]',
                        keys: ['enter'],
                        action: function(){
                            Cookies.remove('watchlist['+productId+']', { domain: 'dev.dieraumbegruener.de' });
                        $.alert('Der Artikel wurde entfernt. Sie können Ihn jederzeit wieder hinzufügen.');
                        }
                    },
                    cancel: {
                        text: 'Abbrechen [ESC]',
                        keys: ['esc'],
                        action: function(){
                            $.alert('Der Artikel wurde nicht entfernt.');
                        }
                    }
                }
            });
```

**Other information:**
I think that this is maybe a proble of the jQuery version? I did not find any information, which jquery version i have to use. I would prefer to use the jQuery Version i use now (v2.2.4) - so if i had to use another jquery-confirm version to do so - i would be very thankful for an advice.

By the way: I do include jquery before jquery-confirm.

**Comment by mpiontek** [comment]
I am SO sorry! I dont know why, but my jquery-confirm-file was empty! I am not able to delete this thread - but it can be deleted!

**Comment by GerardMetal** [comment]
You can close the issue :)
