### ISSUE TITLE
whether or not  support ie8?

### ISSUE THREAD

**Issue by mrlong** [craftpip/jquery-confirm#34]

**Comment by craftpip** [comment]
Hey, 
jquery-confirm is full of CSS3, 
so will not support for IE 8 & IE 9.

**Comment by mrlong** [comment]
think you! 
my project over use jquery-confirm , but project need support IE8.

my rewrite in yesterday 

1.  resolve 110 line trim() 
String.prototype.trim = function ()  
{  
    return this.replace(/(^\s*)|(\s*$)/g, "");  
}  

2. 
.jconfirm-bg{
  background-color:#000; 
  opacity:0.5;
  filter:alpha(opacity=50);
}
