### ISSUE TITLE
Feature request: Option to customize the position of the confirm modal

### ISSUE THREAD

**Issue by Sawon90** [craftpip/jquery-confirm#340]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Confirm modal always show in middle of the screen. 

**Reqested feature**
I will be good if we can customize the position of the confirm modal, like left of the screen, top of the screen or any custom location.

**Comment by craftpip** [comment]
This request is considered, https://github.com/craftpip/jquery-confirm/issues/362
