### ISSUE TITLE
if statement return alway true

### ISSUE THREAD

**Issue by veriuportal** [craftpip/jquery-confirm#342]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

if($.confirm('A message', 'Title is optional')){
//do something
}
this return always true

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
function conf_me(tit, msg){
var resp;
$.confirm({
    title: tit,
    content: msg,
    buttons: {
        confirm: function () {
           resp = true;
        },
        cancel: function () {
            resp = false;
        }
    }
});
return resp;
}
if(conf_me('title','mesage')){
alert('ok');
}
```

**Other information:**
I like to use shortest method for my code : $.confirm('A message', 'Title is optional') and try to make a function with that but with no success.

**Comment by GerardMetal** [comment]
The line code `return resp;` will run before press button of confirm method

```
var jqConfirm;
function conf_me(tit, msg){
    var resp;
    jqConfirm = $.confirm({
        title: tit,
        content: msg,
        buttons: {
            confirm: function () {
                // action code true
            },
            cancel: function () {
                // action code false
            }
        }
    });
}
if(jqConfirm.isOpen()){
     alert('ok');
}
```
I don't know what you want to do, sorry for my english...

**Comment by craftpip** [comment]
$.confirm() returns the jconfirm object.
you're looking for a script that blocks the execution until the user clicks the button on modal.

please refer to:
#366
