### ISSUE TITLE
Disturbance Around

### ISSUE THREAD

**Issue by LuigiMdg** [craftpip/jquery-confirm#343]
Hi..
In v3 I view a disturbance around the panel..
Why?
![senza-titolo-1](https://user-images.githubusercontent.com/18232125/31945787-7643d47c-b8d0-11e7-99e0-554aa5963910.jpg)

**Comment by LuigiMdg** [comment]
No developers?

**Comment by craftpip** [comment]
Sorry for the late reply, i am not sure what is causing this, something to do with the graphics capability of your PC ?

**Comment by LuigiMdg** [comment]
I don't believe.. My PC have a GeForce 840M

**Comment by webprogramozo** [comment]
This is probably a browser problem with shadows. Try to update your graphics driver. There is no effect which "do that" directly.
