### ISSUE TITLE
Help, I don't know whats happening with my code.

### ISSUE THREAD

**Issue by MattCorlleone** [craftpip/jquery-confirm#344]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request

**Current behavior:**

SyntaxError: Unexpected identifier
ResquestAcessOBV()Sys.Application.add_init(function() {

case 3:
                        //request access for the supervisor
                        ScriptManager.RegisterStartupScript(this.Page, Page.GetType(), "key", "ResquestAcessOBV()", true);
                        break;

    <script type="text/javascript">
        function ResquestAcessOBV() {
            $.confirm({
                title: 'Ingredient out of time',
                content: 'Request access!',
                type: 'red',
                backgroundDismiss: false,
                backgroundDismissAnimation: 'glow',
                buttons: {
                    login: {
                        text: 'Login',
                        btnClass: 'btn-blue',
                        keys: ['enter', 'space'],
                        action: function () {
                            //this function work, but don't show the message.
                            lauchModal = true;
                        }
                    },
                    cancel: {
                        text: 'Cancel',
                        btnClass: 'btn-default',
                        keys: ['esc'],
                        action: function () {
                            $.alert('Canceled!');
                        }
                    }
                }
            })
        };
    </script>

**Expected behavior:**

Without this jquery-confirm works with Response.Write, but I need another way to show the message, this jquery-confirm way.
The steps are:
-read a code
-validate a code
-show a message or use the function I have created

But in this case, the message don't shows and go directly to show the modal.

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by GerardMetal** [comment]
The confirm method is working, possibly the error arises in another side
