### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Elements01** [craftpip/jquery-confirm#345]
**jquery-confirm version:**
v3.x.x
**Related code:**
```
    $.confirm({
        title: 'Prompt!',
        content: '' +
        '<form action="" class="formName">' +
        '<div class="form-group">' +
        '<label>Enter something here</label>' +
        '<input type="text" placeholder="Your name" **name="username"** class="name form-control" required />' +
        '</div>' +
        '</form>',
        buttons: {
            formSubmit: {
                text: 'Submit',
                btnClass: 'btn-blue',
                action: function () {
                    var name = this.$content.find('.name').val();
                    if(!name){
                        $.alert('provide a valid name');
                        return false;
                    }
                    $.alert('Your name is ' + name);
                }
            },
            cancel: function () {
                //close
            },
        },
        onContentReady: function () {
            // bind to events
            var jc = this;
            this.$content.find('form').on('submit', function (e) {
                **// here is my php code**
                // if the user submits the form by pressing enter in the field.
                e.preventDefault();
                jc.$$formSubmit.trigger('click'); // reference the button and click it
            });
        }
    });
```

**Other information:**
I'm using the code from above and i want to write the name i enter to a text file with php.
I created a name="username" for the input field and in the php i wrote this.
<?php
                  $myfile = fopen("user.txt", "w") or die("Unable to open file!");
                  $namefromuser = $_POST['username'];
                  fwrite($myfile, $namefromuser);
                  fclose($myfile);           
 ?>
it creats the user.txt file but it's not writing anything into the file.
can someone help me?
i think $_POST needs the name from the input type and i can't name the button because it's not 
in the form tag. 
is there any way i can accomplish this?
thanks for any help in advance

**Comment by namnguyen2091** [comment]
please post your full code here

**Comment by craftpip** [comment]
Please reopen if required
