### ISSUE TITLE
<Input type='text'> not working when opened from Bootstrap Modal

### ISSUE THREAD

**Issue by shieldstromme** [craftpip/jquery-confirm#348]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I have a control on a bootstrap modal form that programmatically opens a jquery-confirm and loads content via ajax. The content includes an <input type='text'> tag in the html. The input is not receiving the focus properly, entering any text overwrites the placeholder text but doesn't actually enter any text.

**Expected behavior:**
Should be able to enter text into the input as normal

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

Bug is not present on Chrome Browser but is seen in Firefox and IE11.

The modal does not have a tabindex attribute. Problem still manifests if tabindex set to -1

**Comment by namnguyen2091** [comment]
What did you do? please put your code and image

**Comment by shieldstromme** [comment]
I've created a fiddle demonstrating the issue:
[https://jsfiddle.net/no584wwg/](url)

**Comment by namnguyen2091** [comment]
I think problem is in here var name = this.$content.find('.name').val();, let try other syntax. Maybe IE doesn't know .name is in which context. It doesn't work in IE10 too.
