### ISSUE TITLE
NOT WORKING WITH SUBMIT BUTTON

### ISSUE THREAD

**Issue by sourabhtiwari** [craftpip/jquery-confirm#35]
ON SUBMIT BUTTON CLICK IT DISAPPEARS AUTOMATICALLY WITHOUT CONFIRMATION.

**Comment by craftpip** [comment]
Hey @sourabhtiwari ,
Can you tell me steps to replicate the problem?

Thanks.

**Comment by sourabhtiwari** [comment]
I HAVE A SUBMIT BUTTON ON MY FORM.

AND ON SUBMIT BUTTON CLICK I HAVE CALLED A FUNCTION WHICH EXECUTES Confirm Box

function validate_save() {
        $.confirm({
            title: 'Confirm!',
            content: 'Are You Sure',
            confirm: function () {
                return true;
            },
            cancel: function () {
                return false;
            }
        });
    }

**Comment by craftpip** [comment]
Apparently, i can guess, you're doing something like this, where you need to prevent the form's submit action.
```js
$('#yourform').submit(function(e){
    e.preventDefault() // Will prevent the page from submit, all you need.
    validate_save(); // your function to show the modal.
})
```
I hope it helps.

**Comment by sourabhtiwari** [comment]
No I want to Submit form but after confirmation.
e.PreventDefault will prevent form submission and than i will be needed to submit data manually by ajax post.

I want to post data directly from form.but after confirmation...

**Comment by craftpip** [comment]
Alright, 
The problem here is, $.alert works asynchronously, so it wont wait until the user does any confirmation.
A work around would be, 
```js
var shouldPrevent = true;
$('#yourform').submit(function(e){
    if(shouldPrevent){
        e.preventDefault();
        $.confirm({
            confirm: function(){
                shouldPrevent = false; // if yes, set to false, 
                $('#yourform').submit(); // and submit the form again.
            }
        })
    }
})
```

**Comment by sourabhtiwari** [comment]
THANKS A TON @craftpip ...ITS working....

**Comment by craftpip** [comment]
Have a great day... 
do star jquery-confirm & share it.

**Comment by shamnex** [comment]
Having the same issues, it code above works but I still have to press submit again before it gets submitted :(

**Comment by craftpip** [comment]
@shamnex , please share your code

**Comment by Sinister87** [comment]
Hi,
please help me! It doesn't work to confirm a submit delete.
When I press "Elimina(delete)", the button close the dialog box but nothing happens.
My code is:

**file.php**
<form id="deletekit" name="deletekit" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
				<button type="submit" id="delete_kitid" name="delete_kitid" value=<?php echo($kit[$i]['kitid']); ?> class="btn btn-small btn-danger">Elimina</button>
			</form>

**file.js**
$("#delete_kitid").confirm({
        title: "Eliminazione Kit",
        content: "Sei sicuro di voler eliminare il kit?",
        buttons: {
            confirm: {
                text: "Elimina",
                btnClass: 'btn-danger',
                action: function(){
                    $('#deletekit').submit();
                }
            },
            cancel: {
                text: "Annulla",
                btnClass: 'btn-default'
            }
        }
    });

Thanks
