### ISSUE TITLE
initialize treeview inside confirm box - not working

### ISSUE THREAD

**Issue by iAmShorty** [craftpip/jquery-confirm#350]
**jquery-confirm version:**
v3.3.2

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
can not initialize treeview inside jquery confirm

**Expected behavior:**
loading treeview and intitialize inside jquery confirm

**Related code:**
```
  $.confirm({
    theme: 'own',
    content: function(data, status, xhr){
      var self = this;
      self.setContent('<div id="tree"></div>');
    },
    onContentReady: function(){
      $("#tree").fancytree({
        checkbox: true,
        source: [
          {title: "Node 1"},
          {title: "Node 2", key: "id2"},
          {title: "Folder 3", folder: true, children: [
            {title: "Node 3.1"},
            {title: "Node 3.2"}
          ]},
          {title: "Folder 2", folder: true}
        ],
      });
    }
  });
```

**Other information:**
i'm using https://github.com/mar10/fancytree to view a tree with related data. i'd like to display that tree in a confirm box. i load the tree via ajax and it's visible in the confirm box, but if i try to initialize the tree, the data is only text and not rendered as treeview.

intitialization is done using the embedded '< ul >' markup. html is rendered before loading into confirm box and after that it should be shown with the fancytree plugin. 

see html markup here -> http://wwwendt.de/tech/fancytree/demo/#sample-source.html

tried many ways to get the tree loaded, but none works. would be nice if someone can give me a hint on how to do this.

thank you

**Comment by allipierre** [comment]
Hi,
can you make a fiddle?

**Comment by iAmShorty** [comment]
It's done already, missed to close the issue. Sorry

You can see it here -> https://github.com/mar10/fancytree/issues/794
