### ISSUE TITLE
Pass a POST variable to external form?

### ISSUE THREAD

**Issue by itajackass** [craftpip/jquery-confirm#351]
Is there a way to send POST variables to external PHP form?
I'd like to pass, in this example, XXX and YYY using POST (not GET).

`<a id="btn" data-value1="XXX" data-value2="YYY">CLICK ME</a>`
```
<script>
$('#btn').on('click', function (e) {
e.preventDefault();
$.confirm({
	title: 'Title',
	content: 'url:form.php',
	buttons: {
          ......
       }       
});
});
</script>
```

form.php:

```
   $value1 = $_POST['value1'];
   $value2 = $_POST['value2'];

   <div class="form-group">
        <label class="control-label">Default values:</label>
        <input type="text" id="value1" class="form-control" value="<?php echo $value1; ?>">
        <input type="text" id="value2" class="form-control" value="<?php echo $value2; ?>">
    </div>
```

**Comment by dvmobley** [comment]
Look at AJAX.

[Signature]

**Comment by itajackass** [comment]
I've tried:
`content: function() { 
			var self = this;
				return $.ajax({
				  url: 'form.php',
				  dataType: 'json',
				  async: false,
				  method: 'post',
				  data: { 'value1': 'XXX', 'value2': 'YYY' }
				}).done(function (response) {
					self.setContent(response);
				});
	}`

but form.php is not loaded inside form....

**Comment by itajackass** [comment]
Fixed with dataType: "html"
