### ISSUE TITLE
Expand jquery.js to ajax loaded form.html inside dialog

### ISSUE THREAD

**Issue by itajackass** [craftpip/jquery-confirm#352]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When i load an external resource, like a form.html with ajax inside dialog content, i can't manage elements inside form.html with jquery. For example:

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
form.html:
 
<form>
<select name="x" id="select_inside_ajax">
<option value="1">ONE</option>
<option value="2">TWO</option>
</select>
</form>

parent_page.html:

<script src="jquery.js">
<script>
$(document).ready(function(){
   $("#select_inside_ajax").on("change",function(){ alert($(this).val()); });
});
</script>

```

**Other information:**

**Comment by GerardMetal** [comment]
In ContentReady callback you can use
```
```
