### ISSUE TITLE
HTML Close button

### ISSUE THREAD

**Issue by Deliator** [craftpip/jquery-confirm#355]
**jquery-confirm version:**
v3.2.3

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request

**Other information:**
I have an external html form file called in a JC dialog popup.
The submit button is in that file, but i need to add a close button in the form.
How can i do that ?

Thanks

**Comment by GerardMetal** [comment]
Try this
```
jd = $.alert({	title: 'JDialog',	content: '<div class="col-xs-12"><button id="close"><i class="fa fa-times fa-fw"></i> CLOSE</button></div>',
	onContentReady: function(){
		$(this.$content.find('#close')).on('click', function(event) {
			event.preventDefault();
			jd.close();
		});
	}
});
```

**Comment by Deliator** [comment]
it works, thanks a lot :-)
