### ISSUE TITLE
How to get value from data attribute

### ISSUE THREAD

**Issue by nubinter** [craftpip/jquery-confirm#356]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request

Hello there,
Thank you very much for making this wonderful plugin. But there is a thing I don't know how to do. I want to retrieve the value of a data attribute for example data-id="x" data-name="y". I have use this code this.data("id") or this.$target.data("id") but all of it giving me an error in my code.

**Comment by GerardMetal** [comment]
In onContentReady method, use this.$el.data("id") or this.$el.data("id","x")
if it does not work for you, you can use $( )
$(this.$el).data("id"), $(this.$el).data("id","x")

**Comment by nubinter** [comment]
Hello @GerardMetal thank you for replying, I know it kinda long for a reply but here is the error I got on console log using your answer above
Uncaught SyntaxError: Unexpected identifier

**Comment by GerardMetal** [comment]
you verify the order of the scripts, one is causing conflict, sorry for my english...
(if you open confirm?)

**Comment by craftpip** [comment]
Closing this issue, as @nubinter hasn't replied yet. please re-open this issue if required
