### ISSUE TITLE
Heed support. How can I change jconfirm-buttons style

### ISSUE THREAD

**Issue by vovamedinsky** [craftpip/jquery-confirm#357]
**jquery-confirm version:**
v3.x.x

jsfiddle for tests of my problem https://jsfiddle.net/bdtx2ub2/

**I'm submitting a ...**  (check one with "x")
[ x ] support request

**Related code:**
```
<div class="jconfirm-buttons">
<button type="button" class="btn btn-info btn-block">Update</button>
<button type="button" class="btn btn-danger btn-block">Delete</button>
<button type="button" class="btn btn-default btn-block">Cancel</button>
</div>
```

Can you help me... how can I add to div with class jconfirm-buttons my class? Is there are any solution like columnClass or btnClass for this div?

I want to justify my buttons in this div by adding bootstrap class btn-block to make div justified
```
<div class="jconfirm-buttons btn-block">
<button type="button" class="btn btn-info btn-block">Update</button>
<button type="button" class="btn btn-danger btn-block">Delete</button>
<button type="button" class="btn btn-default btn-block">Cancel</button>
</div>
```

Before
![image](https://user-images.githubusercontent.com/26840170/33419205-7e180e5a-d5ba-11e7-9a80-190c8017852d.png)

What I want to do
![image](https://user-images.githubusercontent.com/26840170/33419222-92bab876-d5ba-11e7-885f-119807faea2a.png)

How can I do this? Is there are any solution without javascript? Or how can I do it with js (thinking that I can justify them binding this javascript on event "onOpen")?

**Comment by allipierre** [comment]
Hi,

just add on onOpenBefore event like this


$('#showModal').click(function(){
 	showModalWithActionsForServiceCenter(1);
});

function showModalWithActionsForServiceCenter(serviceCenterId) {
        $.alert({
            title: '<span class="pr-4">' + serviceCenterId + '</span>',
            content: 'Actions:',
            type: 'dark',
            typeAnimated: true,
            closeIcon: true,
            onOpenBefore: function () {
                    $(".btn").addClass("btn-block");
                    $(".jconfirm-buttons").addClass("btn-block");
                },
            buttons: {
                update: {
                    text: 'Update', // text for button
                    btnClass: 'btn btn-info', // class for the button
                    action: function(upd){
                        // longhand method to define a button
                        // provides more features
                    }
                },
                delete: {
                    text: 'Delete', // text for button
                    btnClass: 'btn btn-danger', // class for the button
                    action: function(del){
                        // longhand method to define a button
                        // provides more features
                    }
                },
                close: {
                    text: 'Cancel',
                    btnClass: 'btn btn-default',
                    action: function () {

                    }
                }
            },
            columnClass: 'small'
        });
    }

here is the fiddle https://jsfiddle.net/bdtx2ub2/5/

**Comment by craftpip** [comment]
you can also add 'btn-block' in btnClass

```js
$.confirm({
    buttons: {
        hey: {
            btnClass: 'btn-red btn-block'
        }
    }
})
```
