### ISSUE TITLE
About excuting order

### ISSUE THREAD

**Issue by KnightHJ** [craftpip/jquery-confirm#36]
I used plugin in another function but it has worked after the function finished.
The code following is where the problem occured.
Alert always shows before the confirm shows and the value of ’canDelete‘ is always  false.

I have no ideal about where was wrong.
Can you give me some suggestion？
Thanks.

```javascript
function beforeRemove(treeId, treeNode) {
		
var canDelete = false;
			
$.confirm({
		confirm: function(){
			    	//do something
				canDelete = true;	      
			    },
		cancel: function(){	
			    	//do something		    
			        canDelete = false;
			      },		    			    		
		});		
						
		alert(canDelete);
		return canDelete;
}
```

**Comment by craftpip** [comment]
Hello @KnightHJ , 

The way native alert works is, it pauses the browser's JS execution, until it receives input from the user and later continues with the function. 
BUT.. 
Pausing execution is not possible otherwise,

So you will have to do it asynchronously, 
Here is a solution,
```js
function beforeRemove(treeId, treeNode){
    $.confirm({
        confirm: function(){
            delete(treeId, treeNode); // call another function asynchronously to delete.
        },
        cancel: function(){
            // do nothing.
        }
    })
}

```

**Comment by KnightHJ** [comment]
Eh.... 
Actually,this function is used by another plugin to delete node.
It must have the return value.
If you return true, the node will delete automatically.

According to what you said,
does it mean I may not use confirm in this situation ?

Thanks.

**Comment by craftpip** [comment]
Yes, if you have to return a value from the function only way is to use the native Confirm function, 
What plugin do you use to delete the node, I can help try to find a work around..

**Comment by KnightHJ** [comment]
I use this Tree Plugin.
https://github.com/zTree/zTree_v3 

I hope I didn’t trouble you too much.....

**Comment by KnightHJ** [comment]
Oh... I have figure out a way to solve this problem.
I use the Click function of button to confirm before deleting the node.
But beforeRemove function will excute twice  and  a global variable is needed to  save the result of confirm before....
May be it has a better solution...


Anyway， thanks for your time.
I really apperaite your helping me.

**Comment by craftpip** [comment]
Hello @KnightHJ , sorry I was out with work,
Glad you could find out a solution. :) 
You're very welcome
