### ISSUE TITLE
I am very impressed! You did a hell of work. Thank you!

### ISSUE THREAD

**Issue by FrankyBkk** [craftpip/jquery-confirm#360]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by craftpip** [comment]
Compliments keep me going, Thanks a lot for using it!
