### ISSUE TITLE
Disable button after click and add process gif or message

### ISSUE THREAD

**Issue by fabiortsf** [craftpip/jquery-confirm#363]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by GerardMetal** [comment]
U can use this:

> jc.showLoading(disableButtons: boolean)

> jc.hideLoading(enableButtons: boolean)
