### ISSUE TITLE
Pause the script until i'll click OK or CANCEL

### ISSUE THREAD

**Issue by itajackass** [craftpip/jquery-confirm#366]
I've a form with submit validation.
I'dd like to add more than 1 alerts on form submit with:

```
var proceed = true;

$.confirm({
	title: 'Confirm 1',
						content: 'No products added. Are you sure to proceed?',
						buttons: {
							ok: {
								text: "OK",
								btnClass: 'btn-success',
								action: function () {
										
									}
								},
							cancel: {
								text: "Cancel",
								action: function () {
									
									proceed = false;
									return false;
									
									}
								}
							}
						});

... some others checks ....

// IF ALL CHECKS PASSED

if ( !proceed ) { return false;}

$.confirm({
	title: 'Final confirm',
						content: 'All check's ok. Are you sure to insert?',
						buttons: {
							ok: {
								text: "OK",
								btnClass: 'btn-success',
								action: function () {
										form.submit();
									}
								},
							cancel: {
								text: "Cancel",
								action: function () {
									
									}
								}
							}
						});



```

but on form submit I get all of 2 $.cofirm opens! I'd like to pause second one until I click OK on the first one.

**Comment by craftpip** [comment]
The code is not blocking. it is impossible to have functionality like the native alert.
You'll have to use callbacks in this case.

have a look at this
http://stackoverflow.com/questions/13635297/emulate-javascript-alert-blocking-nature

Related to: 
https://github.com/craftpip/jquery-confirm/issues/250
https://github.com/craftpip/jquery-confirm/issues/251
https://github.com/craftpip/jquery-confirm/issues/146

**Comment by plasebo** [comment]
You can try using callback or use deferred like this: 
https://codepen.io/plasebo/pen/WmRxzz?editors=1010
