### ISSUE TITLE
How to post phplist

### ISSUE THREAD

**Issue by fikko2** [craftpip/jquery-confirm#38]
Hi,

Your product is awesome.

I am using jquery-confirm, and there is a pop up work nicely already.
But how to submit those 2 fields from form.txt into php list subscription?
https://www.shopthings.com/lists/?p=subscribe&id=1

Need your help.

Thanks
Fikko

**Comment by craftpip** [comment]
Hey @fikko2 ,
Thanks for using jquery-confirm. :)

I guess what you aim to do is, having the form in the popup and submit. 
You can do it like so, 
```js
$.confirm({
    content: '<form id="someid"> ... </form>' // the confirm content.
    confirmButton: 'subscribe',
    confirm: function(){
        // you can validate the form before and return false to prevent the popup from closing.
        this.$b.find('#someid').submit() // find the form and submit it.
    }
})
```

**Comment by fikko2** [comment]
Hi pereira,

Thank you for your reply. It can submit now, but however, the name and email doesn't pass correctly. The phplist needs email + attribute1, but it seems it is not go through.

http://www.shopthings.com/forex/

It is very awesome work. :)

Regards,

Fikko

**Comment by craftpip** [comment]
hey @fikko2 , 
I checked & you're missing out the name attributes on the input fields. 
the email field should have name="email", &
the name field should have name="attribute1".

Thanks.

**Comment by fikko2** [comment]
Thank you Pereira,
It works now. You just need a few second to find out what's wrong. I spend almost whole day with no clue.
Thank you. it is now perfect..:) 

thanks for your awesome work.

Fikko

**Comment by craftpip** [comment]
Awesome :) 
glad to help.
