### ISSUE TITLE
Thank you note

### ISSUE THREAD

**Issue by rSafari** [craftpip/jquery-confirm#39]
Hello,

We just wanted to thank you for this SUPER AMAZING plugin and making our life much more simpler.

You made us needless of any other plugin and headache of searching the confirm,alert,dialog... plugins. 

We wish you the best of lucks.
Keep this awesome job up.

Faratech Data Processing Inc.
Technical Department

**Comment by MehdiDehghani** [comment]
Hi, there !

Really big plugin and great documentation, keep it up !!

Thanks for sharing your codes with us :)
Cheers !

**Comment by craftpip** [comment]
Hello, 
I'm glad to read the awesome response from you guys, 
I appreciate it. Very few stop by to appreciate the work others do.

Thanks a ton. :)
