### ISSUE TITLE
How to trigger jquery-confirm via php if...else.... statements

### ISSUE THREAD

**Issue by evaliu9457** [craftpip/jquery-confirm#425]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x ] support request

How to trigger jquery-confirm via php if...else.... statements
like this~

```
<?php
    if($a=="text"){
        echo "<script>$.alert({
                         title: 'Alert alert!',
                         content: 'This is a simple alert.',
                   })</script>";
    }
?>
```

**Comment by CaptainKarma** [comment]
Hi its not clear what the problem is but I would split the php and JQuery to make it easier to code, like this;

https://pastebin.com/35t1uJWK

Cheers

**Comment by evaliu9457** [comment]
Hi, CaptainKarma,

my problem is when i post a form, like this
`
<form name="form" method="post" action="">
<input type="text" name="key" value="">
<input type="submit" value-"submit">
`
after form submit, i have to check the value of "key", and alert something,
`
if($_POST["key"]==""){
    echo "<script>alert.......</script>";
}
`
i want to using something looks better like jquery-confirm, replace pure javascript alert.

thanks.

**Comment by evaliu9457** [comment]
Hi, CaptainKarma, I try it, but still not work.....
```
<head>
//ignore something.....
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
</head>
<?php
        if($_POST["key"]!==null){
        //some php function script
        }else{ ?>
        <script> $.alert({ title: 'Alert!', content: 'Simple alert!', }); </script>    
<?php   
        }
?>
<bode>.........</body>
```

**Comment by CaptainKarma** [comment]
You haven't included the JQuery libraries in the head
`<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>`
`<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>`

**Comment by evaliu9457** [comment]
Hi, CaptainKarma, it works, thanks a lot !!!
