### ISSUE TITLE
Notify widget request

### ISSUE THREAD

**Issue by dehghani-mehdi** [craftpip/jquery-confirm#43]
Hey man, what's up?

Thanks again for your awesome plugin.
If is possible, add notification widget too, something like bootstrap's notification plugin.

Or even light-box widget !! then will be amazing :p

Cheers,
Mehdi

**Comment by craftpip** [comment]
Hello @MehdiDehghani ,

Yes, its a good idea. I had thought about it before but didn't do it as this plugin only focused on modals.
Surely i will try this out.

Thank you ! :+1:

**Comment by craftpip** [comment]
Notifications will come in soon.

**Comment by MehdiDehghani** [comment]
Will be great, can not wait for that, thanks !

**Comment by craftpip** [comment]
Its been a year, really sorry, adding a notify plugin will create a lot more options and will be confusing to set options. I will create this in a different plugin. Closing the issue.

**Comment by dehghani-mehdi** [comment]
@craftpip It's okay bro, don't worry. looking forward to your new plugin. good luck!
