### ISSUE TITLE
Autoheight property

### ISSUE THREAD

**Issue by pedrovegaonline** [craftpip/jquery-confirm#45]
First of all, thanks for this amazing, awesome plugin. Well done ;-).

Now, I've been working/playing for a few days with it, and now I have a situation where it might be cool if the height could be adjusted according to content. Have you thinking about it? A property to handle height, or a property to specify autoheight, or adjust height according to content, or something like that?

It would be great if such an option were available. It would be great, e.g., in wizards.

Thanks in advance.

**Comment by craftpip** [comment]
hello @pedrovegaonline ,
Sorry for the late reply,

You can adjust the height of the modal according to your content,
```js
var test = $.alert({
    content: "the initial content"
});
```

later i add multiple lines in the modal like so,
```js
test.setContent('A REALLY LONG TEXT');
```
doing `setContent` will set the content & adjust the height + center the modal on the screen.

If you want to manually set the content's height.
```js
test.contentDiv.css('height', '200px'); 
```
