### ISSUE TITLE
Call a server function while confirm button is pressed in asp.net project

### ISSUE THREAD

**Issue by swnasir** [craftpip/jquery-confirm#46]
Hello
I am trying to use your library in my asp.net webform page. I want to call a server function while confirm button will be pressed. so I have written the following code with help of your tutorial. But it's been seen that the calling of server function is not working. I am giving my code bellow. Can anyone please give me any suggestion.

<form id="form1" runat="server">
        <div>
            <asp:Button runat="server" CssClass="example4" ID="btnOk" OnClick="btnOk_OnClick" Text="Okey Button" />
        </div>
    </form>

script type="text/javascript">
        $('.example4').on('click', function (e) {
            confirmBox();
            e.preventDefault();
        });
        confirmBox = function() {
            $.confirm({
                keyboardEnabled: true,
                title: 'Confirm!',
                content: 'Are you sure to move to next page',
                confirmButton: "YES",
                cancelButton: "NO",
                confirm: function () {
                    alert('Confirmed!');
                    $("[id*=<%= btnOk.ClientID %>]").click();
                },
                cancel: function () {
                    alert('Canceled!');
                }
            });
        }
    </script>

**Comment by craftpip** [comment]
hello @swnasir ,

I assume you want to make a ajax call to your server function.
You can do this:

```js
confirmBox = function() {
    $.confirm({
        keyboardEnabled: true,
        title: 'Confirm!',
        content: 'Are you sure to move to next page',
        confirmButton: "YES",
        cancelButton: "NO",
        confirm: function () {
            alert('Confirmed!');
            // $("[id*=<%= btnOk.ClientID %>]").click();
            var jc = this; // copy a reference to jc
            $.get('yourserverpath/', function(){ // whatever ajax you'll use.
                alert('success');
                jc.close() // close modal when request has completed.
            });
            return false; // do not let the dialog close until the request is complete.
        },
        cancel: function () {
            alert('Canceled!');
        }
    });
}
```

**Comment by swnasir** [comment]
hello @craftpip 
thanks for your suggestion. I did go through as you said but it's not working. maybe i did wrong in somewhere which i could not understand. I am implementing the library in asp.net webform project. I am giving the code. Please let me know where i have done wrong.

ASPX Page
<form id="form1" runat="server">
        <asp:Label runat="server" ID="lblMsg"></asp:Label>
        <br />
        <asp:Button runat="server" ID="btnOk" Text="Redirect" CssClass="example4" OnClick="btnOk_OnClick" />
    </form>

protected void Page_Load(object sender, EventArgs e)
    {
        if (Request.Form["Name"] != null)
        {
            lblMsg.Text = Request.Form["Name"].ToString();
        }
    }

    protected void btnOk_OnClick(object sender, EventArgs e)
    {
        Response.Redirect("Default2.aspx");
    }
--------------------------------------
jQuery Code
<script type="text/javascript">
        $('.example4').on('click', function (e) {
            confirmBox();
            e.preventDefault();
        });

        confirmBox = function () {
            $.confirm({
                keyboardEnabled: true,
                title: 'Confirm!',
                content: 'Are you sure to move to next page',
                confirmButton: "YES",
                cancelButton: "NO",
                columnClass: 'col-md-4 col-md-offset-4',
                confirm: function () {
                    var jc = this;
                    $.post("FormGetPost.aspx", { Name: "Nasir Uddin" }, function (result) {
                        alert(result);
                        jc.close();
                    });
                },
                cancel: function () {
                    alert('Canceled!');
                }
            });
        }
    </script>

**Comment by craftpip** [comment]
Sorry for the late reply @swnasir 

You code seems right , 
please check your console for errors, and let me know.

I assume your problem has been solved after a long time. ;)
