### ISSUE TITLE
backgroundDismiss only works to left and right of the dialog with Firefox

### ISSUE THREAD

**Issue by Hizoka76** [craftpip/jquery-confirm#465]
**jquery-confirm version:**
v3.3.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[X] support request

**Current behavior:**
Hi :)
I use **backgroundDismiss: true** but that works only if I click to left and right of the dialog, not above or below of it... with Firefox 66.0b13, works with Falkon.
I use alert in a function.
Any idea why ?
Thank you !

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
function FenetreInfo(Titre, Message, Couleur = 'red', Largeur = '500px', Icone = 'fas fa-exclamation-triangle')
{
    $.alert(
    {
        title: Titre, 
        content: Message,
        icon: Icone,
        type: Couleur,
        typeAnimated: true, 
        backgroundDismiss: true, 
        escapeKey: true,
        boxWidth: Largeur,
        useBootstrap: false,
        buttons:
        {
            Exit:
            {
                text: "OK",
                btnClass: 'btn-' + Couleur,
                keys: ['enter']
            }
        }
    });
}

```

**Other information:**

**Comment by chris2039** [comment]
I was having this same problem on firefox.   I added the following style after importing the default jquery-confirm css file and it seems to take care of the issue for me.

.jconfirm .jconfirm-bg { z-index: -999; }

**Comment by Hizoka76** [comment]
Thank you :)
