### ISSUE TITLE
Add a tooltip on buttons

### ISSUE THREAD

**Issue by Hizoka76** [craftpip/jquery-confirm#466]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**
Is it possible to add a tooltip on the buttons ?
This allows you to specify the action of the button, for example...
Thank you !

**Comment by boily** [comment]
Just add
`.prop('title', that.buttons[key].title)`
after 
`.prop('disabled', that.buttons[key].isDisabled)`
at about line 697 of the code

and add a title property to the button:

`                                    buttons: {
                                        confirm: {
                                            title: "Click here to confirm",
                                            btnClass: "btn-blue",
                                            action: function(){
                                                $.alert("confirmed");
                                            }
                                        },
`

**Comment by Hizoka76** [comment]
Thank you ! :)
