### ISSUE TITLE
Using Confirm and scrollTop in action causes page to scroll up and then back down

### ISSUE THREAD

**Issue by dcdalton** [craftpip/jquery-confirm#468]
**jquery-confirm version:**
v3.3.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request

**Current behavior:**
Using the jQuery confirm to tell user there are issues within the submitted form, in the action on the button I have a scrollTop. When the button is clicked the page scrolls to the top and then back down to the bottom.

**Expected behavior:**
Expect page to scroll top and stay there, here is my code:

```
$.alert({
	boxWidth: '50%',
	useBootstrap: false,
	title: '<p>Questionnaire Errors Found</p>',
	titleClass: 'alert_title',
	content: "<p class='alert_body'>Errors were found in the submitted questionaire and are highlighted in red</p><p class='alert_body'>Please review and correct the missing information</p>",
	buttons:	{
		okay:	{
			text: 'Okay',
			btnClass: 'alert_button',
			action: function()	{
				$('html').stop().animate({
					scrollTop: $('#voters_guide_form').offset().top
					}, 500);
							
				}
			}
		}
	});
```

I should also note without using jQuery-confirm the behavior is correct. I have also played with using different element ids in the scrollTop and even added the .stop() before the animate call. Nothing changes

**Comment by Hizoka76** [comment]
Hi, I haved same problem, i solved it with :
```
setTimeout(function()
{
	$("#Special").animate({scrollTop: etop}, "slow");
}, 100)
```

**Comment by dcdalton** [comment]
HMM, that's not working for me either, here's the new code I am using:

```
okay:	{
	text: 'Okay',
	btnClass: 'alert_button',
	action: function()	{

		setTimeout(function()	{

			$('html').stop().animate({
			     scrollTop: $('#voters_guide_form').offset().top
				}, 500);

			}, 100);
							
		}
```
						}

**Comment by Hizoka76** [comment]
Did you try with bigger wait time ?

**Comment by dcdalton** [comment]
BINGO! I set the timeout to 600 and it now works perfectly ..THANKS!
