### ISSUE TITLE
Add keyboard navigation elements?

### ISSUE THREAD

**Issue by ptocheia** [craftpip/jquery-confirm#49]
Hello!

This is a really great plugin, but it is very hard to navigate without the use of a mouse, which is not good for accessibility.

Would you consider adding a focus() to dialogs right after they are launched, so users navigating by keyboard will be able to access the buttons within that alert? And, if you add role="dialog" to the wrapper div, this should restrict tabbing to within the alert, so the user can move between the clickable elements within the alert.

Relatedly - you can also consider adding ARIA support to the plugin. This will make it much more accessible to users that require screen readers.

Thanks!

**Comment by craftpip** [comment]
Thanks for the suggestion @ptocheia 
I've got my mind on accessibility now, I will be added these features soon.

**Comment by craftpip** [comment]
This has been added in v2.5
