### ISSUE TITLE
confirmbutton Position is incorrect use 'hololight' Theme

### ISSUE THREAD

**Issue by iamluodong** [craftpip/jquery-confirm#5]
![image](https://cloud.githubusercontent.com/assets/4755525/6861652/ad7ce73c-d474-11e4-9af2-1a282d17f631.png)

**Comment by iamluodong** [comment]
![image](https://cloud.githubusercontent.com/assets/4755525/6863743/a96ceeea-d491-11e4-8f63-a90bbcc8c8cd.png)
i found class 'pull-right' not define at css.

**Comment by craftpip** [comment]
@iamluodong , Can you please tell me the steps to reproduce this, what browser are you using, so i can get to my notice. The pull-right class is defined in the bootstrap library.
Thanks for pointing it out.

**Comment by iamluodong** [comment]
I am not use bootstrap,it depend Bootstrap?
why default theme no problem,My device is Nexus4 ,android 4.4,I have test on Chrome41.the same problem.

**Comment by craftpip** [comment]
Yes, Bootstrap and jQuery are a requirement for jquery-confirm to run. 
Please get the latest bootstrap CSS library [Homepage](http://getbootstrap.com/)
The plugin should work on your Nexus Device using Chrome.
***
Please let me know if the problem persist even after adding bootstrap library.

:)
