### ISSUE TITLE
Jquery live Confirm issue

### ISSUE THREAD

**Issue by uongnhathien84** [craftpip/jquery-confirm#50]
- Hi all. 
- I have: 

<button class="del">Confirmation1</button>
<button class="del">Confirmation2</button>
<button class="del">Confirmation3</button>

- I use ok code bottom but only run first button 'delete' : 
 $('.del').on('click', function () {
       $.confirm({
            title: 'A critical action',
            content: 'You can queue confirms, you\'ll be asked again for a confirmation.',
            confirmButton: 'Proceed',
             animation: 'scale',
             confirm: function () {                                       
               alert('A very critical action triggered!');                                  
             }
        });
 });
- But when I change code with my require ( because I have many 'delete' button) then jquery confirm don't run: 

$(".del").live('click', function() {
       $.confirm({
            title: 'A critical action',
            content: 'You can queue confirms, you\'ll be asked again for a confirmation.',
            confirmButton: 'Proceed',
             animation: 'scale',
             confirm: function () {                                       
               alert('A very critical action triggered!');                                  
            }
       });
 });

Please help me. Thanks

**Comment by craftpip** [comment]
Hello @uongnhathien84 

As far as i know the live event was removed from jquery in the later versions.
Use click instead.

I hope it helps

**Comment by uongnhathien84** [comment]
thanks
