### ISSUE TITLE
animation: none

### ISSUE THREAD

**Issue by foxicatko** [craftpip/jquery-confirm#52]
Hi,
I've noticed this in the latest version (around line 97).  You assign "anim-" + whatever to this.animation and then check if this.animation possibly equals "none" which should never happen.

```javascript
/*
 * Cleaning animations.
 */
this.animation = 'anim-' + this.animation.toLowerCase();
...
if (this.animation === 'none')
    this.animationSpeed = 0;
```

**Comment by craftpip** [comment]
@foxicatko , 
Thanks for pointing this out, this was a real silly mistake.
:+1:
