### ISSUE TITLE
autoClose in $.dialog

### ISSUE THREAD

**Issue by arifszn** [craftpip/jquery-confirm#520]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...** 
[ ] bug report
[ ] feature request
[x ] support request

**Current behavior:**
As $.dialog does not support buttons and autoClose takes button name in first parameter, how to auto close in $.dialog? 

When i add attached code, this error occurs: Invalid button key 'dummyButton' for autoClose

**Expected behavior:**
I want to autoclose in $.dialog method.

**Related code:**
```
$.dialog({
 title: 'Success',
 content: 'Form saved.',
 autoClose: 'dummyButton|8000',
  buttons: {
    dummyButton: {
      text: 'logout myself',
       action: function () {
         $.alert('The user was logged out');
       }
     }
  }
});

**Comment by georgebotley** [comment]
Could you not utilise a confirm here, with a single button. That is how I achieve this.
