### ISSUE TITLE
Position shake at v2.0.0

### ISSUE THREAD

**Issue by zangbianxuegu** [craftpip/jquery-confirm#53]
The jconfirm-box has a move down action before it's completely show

**Comment by craftpip** [comment]
Hello @zangbianxuegu, Please share the options you used.
i guess this may happen when loading content from remote resource.

**Comment by zangbianxuegu** [comment]
Thank you @craftpip I use it like this:

    $.dialog({
      theme: 'white'
      title: '分享到'
      content: '''
        <a class="wechat_conversation" data-channel="wechat_conversation" href="#"><i></i>微信好友</a>
        <a class="wechat_moments" data-channel="wechat_moments" href="#"><i></i>朋友圈</a>
        <a class="wechat_favorite" data-channel="wechat_favorite" href="#"><i></i>微信收藏</a>'''
    }).$el.addClass('wechat_share')

I think it's not loading content from remote resource. And I remember it's OK before change to v2.0.0.

Maybe you know what's wrong with this, thank you. Or I will continue to check for it.

**Comment by zangbianxuegu** [comment]
I found the problem, it's the css influence

Because my own .container has 'overflow: hidden', the container's height contain it's child's margin

Thank you again @craftpip

**Comment by zangbianxuegu** [comment]
I think it's better to change the css class 'container' to 'jconfirm-container' as 'container' is usually used

**Comment by craftpip** [comment]
@zangbianxuegu I'm glad you figured out the problem :) 
also, the container class used is from bootstrap, which cannot be changed.
