### ISSUE TITLE
To get an attribute of the element clicked

### ISSUE THREAD

**Issue by Sabe67** [craftpip/jquery-confirm#55]
Hi, 

Can we get an attribute of the element which is clicked ?

Thank your for your answer.

**Comment by alanheinz** [comment]
Hi, today I found a similar problem with a loop elements and assigning classes and attributes to them, and I found a way to do this with each of the jQuery.


$('.gRemoveItem').each(function(x) {
 var parItem = $(this).attr('idItem');
 $(this).confirm({ 
      title: 'Confirma Exclusão?',
      content: 'Você está excluindo um registro de ocorrência do Jogo!',
      confirmButton: 'Sim, confirmo!',
      cancelButton: 'Cancelar',
      confirm: function(){ 
		alert(parItem); 
	  }
    });
});

**Comment by craftpip** [comment]
Thanks @alanheinz for the answer.

I will soon add a reference to the element, that can be accessed by `this.target` which can be accessed from the plugin function scope. 

What do you say ?

**Comment by Sabe67** [comment]
Yeah it could be a very good idea :)

**Comment by alanheinz** [comment]
@craftpip is a good idea, the reference will give the opportunity to use in various system situations.

Thanks for the effort in improving jQuery Confirm

It's a great tool!

PS: I'm brazilian and my english is very bad :)

**Comment by alanheinz** [comment]
@Sabe67 Yeah! in Brazil they call it "Gambiarra"!

**Comment by craftpip** [comment]
Thats Awesome :+1: 
I will soon work on it .

**Comment by usb248** [comment]
Any updates ? ...

**Comment by craftpip** [comment]
I'm working on it, will get it online by 22nd.

**Comment by craftpip** [comment]
this.$target has been added in v2.5. Thanks for the suggestion !
