### ISSUE TITLE
adding buttons in confirm box

### ISSUE THREAD

**Issue by Sarfroz** [craftpip/jquery-confirm#56]
Hello sir i want to know that how can  add 2 or 3 buttons in place or confirm and cancel.

**Comment by craftpip** [comment]
Sorry, Currently only 2 buttons (confirm, cancel) are supported. I'm considering to update the plugin to accept an array of buttons.

**Comment by neylsongularte** [comment]
+1

**Comment by mcbmcb0** [comment]
+1

**Comment by craftpip** [comment]
This has now been added in v3. 
:)

**Comment by Sarfroz** [comment]
getting lots of problem sir


onloadwff.js:1573 TypeError: Cannot read property 'getElementsByTagName' of null(…)
onloadwff.js:1573 TypeError: Cannot read property 'getElementsByTagName' of null(…)
onloadwff.js:1573 TypeError: Cannot read property 'getElementsByTagName' of null(…)
onloadwff.js:1573 TypeError: Cannot read property 'getElementsByTagName' of null(…)
onloadwff.js:1573 TypeError: Cannot read property 'getElementsByTagName' of null(…)

**Comment by craftpip** [comment]
I looked into this, its caused while fetching animation-duration property,
