### ISSUE TITLE
Missing reference list Icons

### ISSUE THREAD

**Issue by SaoiBain** [craftpip/jquery-confirm#560]
The library is great, however it would be possible to list the group of icons available for use with the alert windows; since when trying to use other icons these are not shown possibly because they are not in the icon library.

**Comment by SanderVerkuil** [comment]
Icons are not provided by this library, and it depends on which icon library you use. The default configuration appears to be for font awesome, so take a look at [FontAwesome 5 Cheatsheet](https://fontawesome.com/v5/cheatsheet) if using their version 5.
