### ISSUE TITLE
trim issue

### ISSUE THREAD

**Issue by lh2587451** [craftpip/jquery-confirm#57]
it's a better way to replace this.confirmButton.trim() with $.trim(this.confirmButton) at lin 10,2080 in jquery-confirm.min.js and others

**Comment by craftpip** [comment]
Hey, $.trim seems to be faster than the native .trim
Will get it replaced soon , Thanks ! :+1:

**Comment by craftpip** [comment]
Has been fixed in v2.5 Thanks !
