### ISSUE TITLE
add image contentLoaded event

### ISSUE THREAD

**Issue by zero7u** [craftpip/jquery-confirm#59]
Is it possible to add a ````contentLoaded```` event for image elements, so when the image loaded, We can invoke ````setDialogCenter```` method to make the dialog centered.

Great plugin, many thanks!

**Comment by craftpip** [comment]
This is a good idea, will work on this. 
Thank you!

**Comment by craftpip** [comment]
Support has been added in v2.5 see http://craftpip.github.io/jquery-confirm/#quickfeatures the loading images button
