### ISSUE TITLE
this confirm can't block the function?

### ISSUE THREAD

**Issue by chenyq2012** [craftpip/jquery-confirm#60]
like the following code: "the second msg" first alert 
$.confirm({
	        icon: 'fa fa-warning',
	        title: 'title',
	        content: 'test',
	        confirmButton: 'sure',
	        cancelButton: 'cancel',	         
	        confirm: function () {
	            alert("the first msg");           
	        },
	        cancel:function() {
	            flag= false;
	        }
	    });
	    alert("the second msg");

**Comment by craftpip** [comment]
Only the browser native alert & confirm can block the execution. 
have a look at these issues. https://github.com/craftpip/jquery-confirm/issues/47 & https://github.com/craftpip/jquery-confirm/issues/36
