### ISSUE TITLE
when i select context from right to left, the open dialog auto closed,how to prevent this happen?

### ISSUE THREAD

**Issue by kavenblog** [craftpip/jquery-confirm#61]

**Comment by craftpip** [comment]
I could not understand, Can you please give me the options that you used ?

**Comment by kavenblog** [comment]
The problem is when i want to copy the text on the dialog, i must very carefully.
because if i release the hold mouse button outside the dialog box , the dialog will closed.

**Comment by craftpip** [comment]
You may consider to disable the background dismiss feature.
