### ISSUE TITLE
Option to override close button class

### ISSUE THREAD

**Issue by jaredatch** [craftpip/jquery-confirm#62]
I'm using this for a project that is not leveraging bootstrap.

It would be nice to be able to override the `glyphicon glyphicon-remove` with FontAwesome classes.

Instead I'm adding those classes and basically making them aliases for what I need, which is fine as it works, but swapping out the classes would be easier.

**Comment by jaredatch** [comment]
Reference for anyone else, here is what you need to do

```
.jconfirm .jconfirm-box .closeIcon .glyphicon-remove:before {
	font-family: 'FontAwesome';
	content: "\f00d";
}
```

**Comment by zangbianxuegu** [comment]
Yes, this need. closeIcon setting classes

**Comment by craftpip** [comment]
I'm working on the new release, and recently changed the close icon to html entities, using &times; which is not dependent on glyphicon nor font awesome, makes it independent.

However adding the option to define closeIcon class is a good idea.

**Comment by craftpip** [comment]
Option added in v2.5 see http://craftpip.github.io/jquery-confirm/#close-icon

**Comment by jaredatch** [comment]
Excellent, appreciate it. Great addition. :+1:
