### ISSUE TITLE
Is it possible to change the degree of shading when showing a model?

### ISSUE THREAD

**Issue by ewardjr** [craftpip/jquery-confirm#63]

**Comment by craftpip** [comment]
By shading do you mean the box-shadow property of the box?

You will need to make changes in the css file. 
https://github.com/craftpip/jquery-confirm/blob/master/css/jquery-confirm.css#L137 <- for the light theme
https://github.com/craftpip/jquery-confirm/blob/master/css/jquery-confirm.css#L165 <- for the dark theme
