### ISSUE TITLE
Bug loading image

### ISSUE THREAD

**Issue by usb248** [craftpip/jquery-confirm#65]
Hi,

New release = bug ^^.
On this image, on the left the result of the modal for the first loading and on the right the second loading (so with cache).

![screenshot](https://cloud.githubusercontent.com/assets/7659927/12496530/a3ee1da8-c096-11e5-85b7-bd135140a646.png)

The plugin set a wrong height ....

**Comment by craftpip** [comment]
This problem is on firefox, When the image is loaded it gives a false height value in firefox. Need to recheck this.
Thanks !

**Comment by usb248** [comment]
Any fix ?
