### ISSUE TITLE
Bug or .. ? Overflow problem ...

### ISSUE THREAD

**Issue by usb248** [craftpip/jquery-confirm#66]
Since your new release, i don't know why but when the height of the modal overflows the windows, it appears TWO scrollbar ... It's very ugly, it's a bug or this is normal ?
![capture](https://cloud.githubusercontent.com/assets/7659927/12496808/28fae854-c098-11e5-8ffc-9e799f48d92f.jpg)

**Comment by craftpip** [comment]
This was intended. I'm implementing to hide the browser scroll bar only when the modal content is over window height. that will give a constant page width.

**Comment by usb248** [comment]
When is the next release for change this behavior ? :)

**Comment by craftpip** [comment]
Very soon.
