### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by vit1251** [craftpip/jquery-confirm#69]
Hello,

I want to add this to some project but does not know where I can get CDN version of your plugin for using another hosting service without hosting your code,

It is possible?

Thanx.

**Comment by craftpip** [comment]
Sorry, CDN for jquery-confirm is not available at the moment. 
You can use https://rawgit.com/ but it doesn't give up time guarantee

**Comment by craftpip** [comment]
CDN added 👍
