### ISSUE TITLE
Bower 

### ISSUE THREAD

**Issue by yagop** [craftpip/jquery-confirm#7]
Register to bower package.

**Comment by craftpip** [comment]
@yagop , jquery-confirm will be added to bower soon, thanks for pointing it out.

**Comment by craftpip** [comment]
jquery-confirm can now be installed via Bower, 

The package name jquery-confirm is already taken by somebody else, Thus jquery-confirm2.
`bower install jquery-confirm2` OR
`bower install craftpip/jquery-confirm`

Big thanks to @yagop for letting me know.

**Comment by yagop** [comment]
Thanks to you for your time and work.

**Comment by craftpip** [comment]
:+1: Please do let me know about issues in jquery-confirm.
