### ISSUE TITLE
Change Opacity

### ISSUE THREAD

**Issue by juanreyesv** [craftpip/jquery-confirm#70]
Hi, great library! not sure if this is already part of it but couldn't find how to increase the opacity of the background. I would like to use it as a security measure to log off users after some idle time

**Comment by craftpip** [comment]
For the time being that option is not available. 
however you can change the background opacity by making changes in the CSS files.
https://github.com/craftpip/jquery-confirm/blob/master/css/jquery-confirm.css#L195
