### ISSUE TITLE
Broken page on https

### ISSUE THREAD

**Issue by kucix** [craftpip/jquery-confirm#72]
https://craftpip.github.io/jquery-confirm/
mixed content...

Example of error message in chrome console:

Mixed Content: The page at 'https://craftpip.github.io/jquery-confirm/' was loaded over HTTPS, but requested an insecure script 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by craftpip** [comment]
Thanks for noticing this, fixing this right away.
