### ISSUE TITLE
CSS not working with IOS

### ISSUE THREAD

**Issue by Mobiwoom** [craftpip/jquery-confirm#74]
I try to customize the content and it seems not working with IOS , and works on Android.
My code : 
 $.confirm({
            title: 'Saisissez les 8 chiffres',
            content: 'url:tpl/nfc.html',
            theme: 'black',
            cancelButton: 'ANNULER',
            confirmButton: 'OK',
            confirmButtonClass: 'btn-success',
            cancelButtonClass: 'btn-danger2',
            columnClass: 'col-md-4',

and in my content html I have :
a script on loading :    $('#NFCNumber').focus();
and an input field with id="NFCNumber" 

First : focus is not working in IOS , and is OK with Android
Second : I have defined a class like that : 
#NFCNumber {
    width:100%;
    height:40px;
    font-size: 25px;
}

the height and font-size are not working on IOS , and is OK on Android...

Could you help ?

**Comment by craftpip** [comment]
Can you please post screenshot of iOS and android ?

**Comment by Mobiwoom** [comment]
Android
![img_0019](https://cloud.githubusercontent.com/assets/7278017/12851543/c9cb236e-cc2a-11e5-8288-9ce97d3a1f71.JPG)

IOS
![20160205_170435](https://cloud.githubusercontent.com/assets/7278017/12851611/24484286-cc2b-11e5-8678-4568043e6c1b.jpg)

**Comment by craftpip** [comment]
I appologize for the late reply. 
If you've the input element inside jquery-confirm modal. it is to be rendered in future. 
Thus use the onOpen callback,

```js
$.confirm({
    content: ....
    onOpen: function(){
         this.$content.find('input.example').focus();
    }
})
```
