### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by huazx** [craftpip/jquery-confirm#75]
Sometimes,  IE11 and edge cannot close Dialog by closeIcon

**Comment by huazx** [comment]
There's something wrong with version 2.5.0.

**Comment by rajkumarpb** [comment]
Any error messages in Console?

**Comment by craftpip** [comment]
Yes, please give some information on how to redo the error. I tried it out on edge and it works fine.

**Comment by rajkumarpb** [comment]
I tried extensively in IE11 for more than 100 times over past 2 hours. But it worked all the time. May be he is using the plugin in app, which might have caused this? OP need to give some info to debug. Otherwise, I'm convinced that there is no issue with v2.5.0 with IE11.

**Comment by huazx** [comment]
When the mouse moves to closeIcon, the Dialog  shaking

**Comment by huazx** [comment]
When the parent window is the iframe in IE11, the chrome is OK

**Comment by huazx** [comment]
`<style type="text/css">
iframe {
	border: 0 none;
}

body {
	margin: 0;
	overflow-y: hidden;
}
/* Let's get this party started */
::-webkit-scrollbar {
	width: 8px;
}

::-webkit-scrollbar-track, ::-webkit-scrollbar-thumb {
	border-radius: 999px;
	border: 0px solid transparent;
}

::-webkit-scrollbar-track {
	box-shadow: 1px 1px 5px rgba(0, 0, 0, .2) inset;
}

::-webkit-scrollbar-thumb {
	min-height: 10px;
	background-clip: content-box;
	box-shadow: 0 0 0 5px rgba(0, 0, 0, .2) inset;
}

::-webkit-scrollbar-corner {
	background: transparent;
}
</style>
<script src="<c:url value='/plugins/jquery-1.12.1.min.js'/>" type="text/javascript"></script>
<script type="text/javascript">
	$(function() {
		$("#mIframe").height($(window).height() - $("#topIframe").height());

		$(window).on('resize',function() {
			if(window['console']) {
				console.log('$(window).height(): ' + $(window).height() + ' ,$("#topIframe").height(): ' + $("#topIframe").height());
			}
			$("#mIframe").height($(window).height() - $("#topIframe").height());
		});
	});
</script>
</head>
<body>
	<iframe id="topIframe" height="92" src="<c:url value='/top'/>" width="100%" scrolling="no" frameborder="no" border="0"></iframe>

	<iframe id="mIframe" width="100%" height="0" src="<c:url value='/index'/>" frameborder="no" border="0"></iframe>
</body>`

**Comment by huazx** [comment]
`<style type="text/css">
iframe {
	border: 0 none;
}

body {
	margin: 0;
	overflow-y: hidden;
}
/* Let's get this party started */
::-webkit-scrollbar {
	width: 8px;
}

::-webkit-scrollbar-track, ::-webkit-scrollbar-thumb {
	border-radius: 999px;
	border: 0px solid transparent;
}

::-webkit-scrollbar-track {
	box-shadow: 1px 1px 5px rgba(0, 0, 0, .2) inset;
}

::-webkit-scrollbar-thumb {
	min-height: 10px;
	background-clip: content-box;
	box-shadow: 0 0 0 5px rgba(0, 0, 0, .2) inset;
}

::-webkit-scrollbar-corner {
	background: transparent;
}
</style>
<script src="<c:url value='/plugins/jquery-1.12.1.min.js'/>" type="text/javascript"></script>
<script type="text/javascript">
	$(function() {
		$("#mIframe").height($(window).height() - $("#topIframe").height());

		$(window).on('resize',function() {
			if(window['console']) {
				console.log('$(window).height(): ' + $(window).height() + ' ,$("#topIframe").height(): ' + $("#topIframe").height());
			}
			$("#mIframe").height($(window).height() - $("#topIframe").height());
		});
	});
</script>
</head>
<body>
	<iframe id="topIframe" height="92" src="<c:url value='/top'/>" width="100%" scrolling="no" frameborder="no" border="0"></iframe>

	<iframe id="mIframe" width="100%" height="0" src="<c:url value='/index'/>" frameborder="no" border="0"></iframe>
</body>`

**Comment by huazx** [comment]
$(window).on('resize',function() {
			if(window['console']) {
				console.log('$(window).height(): ' + $(window).height() + ' ,$("#topIframe").height(): ' + $("#topIframe").height());
			}
			$("#mIframe").height($(window).height() - $("#topIframe").height());
		});

**Comment by rajkumarpb** [comment]
Can you create a gist with the code which will replicate this issue? So we can have better understanding of why it is happening?
