### ISSUE TITLE
how to change content of div element inside alert box

### ISSUE THREAD

**Issue by hsynls** [craftpip/jquery-confirm#76]
Is it possible to change content of div element inside of alert box. 

 $('#divName').html('it is changed');
 console.log($('#divName').html());

this code writes the console 'it is changed' however there is no change on alert popup window.

**Comment by hsynls** [comment]
i have solved my problem with 
 jc.$content.find('#divName').html('it is changed');

**Comment by rajkumarpb** [comment]
First of all, why you want to change the content of alert box dynamically? Anyways, instead of that, why not initialize the alert again so it will reflect with change?

    $.alert({
    title: 'Alert!',
    content: 'it is changed?',
    confirm: function(){
        $.alert('Confirmed!'); // shorthand.
    }
    });

**Comment by hsynls** [comment]
Thats a good solution but I've used alertbox its out of purpose. What i am trying to say, jc.setContent('it is changed') this code only changes inside of alert popup however there is multiple div elements in my alert popup and also these div elements generated dynamically on real time. 

The problem was jquery selector didn't select div elements that is inside of alert popup window.
