### ISSUE TITLE
How to close all window

### ISSUE THREAD

**Issue by chan15** [craftpip/jquery-confirm#77]
I know there is an api, but you need to var it which means you have to know what did you done, but sometimes you just don't know, for example, if I have a routing ajax work, and someone maybe open alert or confirm window, and after ajax function finish start I need to bring up a loading modal to the page, but I don't know to to close all possible opened  window

**Comment by craftpip** [comment]
You can do it this way, put the reference object in an array and loop thru the array to check if the modal is open. with isClosed() method. Sorry for the late reply.

**Comment by craftpip** [comment]
I will keep a track of opened modals in an array in the future version, that can be looped
