### ISSUE TITLE
Issue with iOS dialog height on open 

### ISSUE THREAD

**Issue by dvmobley** [craftpip/jquery-confirm#78]
I have a dynamic form that I'm loading in to a confirm dialog using the url method. It works great except for the opening event in mobile based browsers. It only opens to half the height of the first input then stops; however if you rotate the device the dialog opens the rest of the way. I have been trying it in Chrome and Safari on iPad and iPhone. What's even more interesting is when I use the Puffin browser on either device it also works as designed. 

![image](https://cloud.githubusercontent.com/assets/17579464/13442671/650c9e58-dfcb-11e5-8562-31d0dccf3f8c.png)

----HTML Caller----
`<button style="float:right; clear:right;" href="RDOC_Report_Event_new.php?ID=737&logonuser=gsx587&complex=Stophel" class="btn btn-warning edit"><span class="glyphicon glyphicon-pencil"></span></button>`

-----JS----
`$(document).on('click', '.edit', function(e){
    e.preventDefault();
    $('div.popover').hide();
    var dest = $(this).attr('href');
    var diagEdit = $.confirm({
        title: 'Edit Report',
        content: 'url: ' + dest,
        columnClass: 'col-xs-12',
        animation: 'zoom',
        closeAnimation: 'scale',
        cancel: function(){
            window.open('RDOC_calendar_new.php', '_self');
        },
        confirm: function(){
            this.$content.find('form').submit();
        }
    });
});`

**Comment by craftpip** [comment]
This is a bug for the browser, i will get it fixed. Thank you :+1:

**Comment by dvmobley** [comment]
## You're awesome! ##
Unbelievable product by the way. Even though it's got the bug I'm leaving it in production because users like it so much better than having to go to another page. I've not found anything else as easy to use or with as much options and documentation. Keep up the good work.

**Comment by lxcn** [comment]
fixed?

**Comment by lxcn** [comment]
Js code:

> $.confirm({content:url})

Add a style fix this bug, style code:

>.content{height:auto !important;}

And, it looks like normal. 

@dvmobley 
@craftpip

**Comment by dvmobley** [comment]
So I can add this to line 165 of the jquery-confirm.css file?

Dale

Sent from my iPhone

On Apr 8, 2016, at 11:51 PM, lxcn <notifications@github.com<mailto:notifications@github.com>> wrote:


Js code:

$.confirm({content:url})

Add a style fix this bug, style code:

.content{height:auto !important;}

And, it looks like normal.

@dvmobley<https://github.com/dvmobley>
@craftpip<https://github.com/craftpip>

**Comment by dvmobley** [comment]
Sorry, didn't make a difference on my project.

Dale

Sent from my iPhone

On Apr 8, 2016, at 11:51 PM, lxcn <notifications@github.com<mailto:notifications@github.com>> wrote:


Js code:

$.confirm({content:url})

Add a style fix this bug, style code:

.content{height:auto !important;}

And, it looks like normal.

@dvmobley<https://github.com/dvmobley>
@craftpip<https://github.com/craftpip>

**Comment by lxcn** [comment]
I was add it in page file.
head link css, and add this after css link by \<style\>. maybe you can try change other elements style or push that to other place.
@dvmobley

**Comment by lxcn** [comment]
@dvmobley 
that's this?
>div.popover

**Comment by dvmobley** [comment]
Here's a valid solution
Add the following at line 453 in your js file.

`var containerHeight = this.$content.find('.container-fluid').height();
                if (containerHeight > paneHeight){
					contentHeight = containerHeight;
				}`

**Comment by dvmobley** [comment]
May have spoke too soon. That Element is a standard in my project. It doesn't exist in the confirm dialog.

**Comment by craftpip** [comment]
Thank you guys for moving this forward, i'm lacking an apple product thus could not make a move on this. :+1:

**Comment by dvmobley** [comment]
After 3 long days of working on this I've got a working solution. First off I've tested it with mainly ajax content on these browsers/platforms:
-iPad
  -Safari
  -Chrome
-Windows
  -IE 11
  -Firefox 45.0.2
  -Chrome 50.0.2661.75 m
-Mac
  -Safari 9.0.3
  -Firefox 45.0.2

I've attached the changed files, but here's a summary of the changes

`css changes: `
`----------------------------------------`
`add new class`
`.innerContainer{`
`	height: auto !important;`
`}`
``
`++++++++++++++++++++++++++++++++++++++++`
`js changes`
`----------------------------------------`
`Defaults:`
`Increase: watchInterval to 500 //content needs more time to load`
``
`Line: 200 `
`	From: that.setDialogCenter(); //immediately called`
`	To: setTimeout(that.setDialogCenter(), this.watchInterval); //need to give content a chance to load`
``
`Line: 386`
`	From: that.setDialogCenter(); //this is a repeat call in stack`
`	To: this.$content.wrapInner("<div class='innerContainer'></div>"); //wrap inner content with a known div and a height of auto`
``
`//The setDialogCenter function was changed too much to try to list each change.`
`setDialogCenter: function () {`
`	//define these once and use as defaults instead of alternates`
`	var contentHeight = 0;`
`	var paneHeight = 0;`
`	var style = '';`
`	`
`	//all of this applies when the content is visible`
`	if (this.$contentPane.css('display') != 'none') {`
`		contentHeight = this.$content.outerHeight();`
`		paneHeight = this.$contentPane.height();`
`		var innerContainer = $('innerContainer').height(); //get innerContainer height`
`		if (contentHeight < innerContainer){`
`			contentHeight = innerContainer; //content set at 40 on init`
`		}`
`		if (paneHeight == 0){`
`			paneHeight = contentHeight;`
`		}`
`		`
`		//lets see where we are interestingly the innerContainer comes back as null but it doesn't work without the innerContainer height above`
`		console.log('Content: ' + contentHeight + ' Inner: ' + innerContainer + ' Pane: ' + paneHeight); `
`		`
`		`
`		var off = 100;`
`		var w = this.$content.outerWidth();`
``
`		//var s = '-clip-path: inset(0px 0px '+contentHeight+'px 0px);' +`
`		//    'clip-path: inset(0px 0px '+contentHeight+'px 0px)';`
``
`		this.$content.css({`
`			'clip': 'rect(0px ' + (off + w) + 'px ' + contentHeight + 'px -' + off + 'px)'`
`		});`
``
`		this.$contentPane.css({`
`			'height': contentHeight`
`		});`
``
`		var windowHeight = $(window).height();`
`		var boxHeight = (this.$b.outerHeight() - this.$b.innerHeight()) + paneHeight; //get margin and padding of box then add content pane height`
`		`
`		//lets see where we are interestingly the innerContainer comes back as null`
`		console.log('Content: ' + contentHeight + ' Inner: ' + innerContainer + ' Pane: ' + paneHeight + ' Box: ' + boxHeight + ' Window: ' + windowHeight);`
`		`
`		`
`		var topMargin = (windowHeight - boxHeight) / 2;`
`		var minMargin = 100;`
`		if (boxHeight > (windowHeight - minMargin)) {`
`			style = {`
`				'margin-top': minMargin / 2,`
`				'margin-bottom': minMargin / 2`
`			};`
`			$('body').addClass('jconfirm-noscroll');`
`		} else {`
`			style = {`
`				'margin-top': topMargin`
`			};`
`			$('body').removeClass('jconfirm-noscroll');`
`		}`
`	}`
`	this.$b.css(style);`
`}`
[jquery-confirm.zip](https://github.com/craftpip/jquery-confirm/files/230096/jquery-confirm.zip)

**Comment by dionmes** [comment]
Hi,
great work on this plugin. 

With regards to this bug, it comes from line 451 (2.5.1)                
`var contentHeight = this.$content.outerHeight();`
The value is not correct in Safari. I have tried to implement an easy fix, but that seems to mess up other stuff. So currently I use a contant value for contentHeight, which works for me now.

Hope it helps.
Regards.

**Comment by noraheuer** [comment]
@dvmobley 
I had this issue occurring intermittently when loading content with images via ajax (latest desktop Firefox and Safari on OSX) and while your code provided above fixed this for me (likely due to the increased timeout/watchInterval - I'm guessing), the dialog itself is now positioned at the top of the window (onOpen) before settling down somewhat below the center - no matter what content I load. Still better than half loaded content, but dizzying for some.

**Comment by dvmobley** [comment]
I agree. That is because until the content is loaded the size of the content is unknown. Once the content size is known (or in this case after the extended wait period) the centering function is fired off.
An easy solution would be to change the default functionality of opening at the top of the screen and center it on open. I think it would be easy to change this, but I don’t have any time right now to work on it.

________________________________
Dale Mobley
IT Administrator
O – 423.425.5908

From: Nora
Reply-To: craftpip/jquery-confirm
Date: Saturday, May 21, 2016 at 2:42 AM
To: craftpip/jquery-confirm
Cc: Dale Mobley, Mention
Subject: Re: [craftpip/jquery-confirm] Issue with iOS dialog height on open (#78)


@dvmobley<https://github.com/dvmobley>
I had this issue occurring intermittently when loading content with images via ajax (latest desktop Firefox and Safari on OSX) and while your code provided above fixed this for me (likely due to the increased timeout/watchInterval - I'm guessing), the dialog itself is now positioned at the top of the window (onOpen) before settling down somewhat below the center - no matter what content I load. Still better than half loaded content, but dizzying for some.

**Comment by craftpip** [comment]
https://github.com/craftpip/jquery-confirm/blob/32fe2585bbdaf2ef47a5e0b450cf606d11acf3e9/js/jquery-confirm.js#L871

I found the issue, please confirm that the latest version has it fixed.
The issue was that if the content's first child has margin-top, that was not counted in the parents outerHeight.

**Comment by craftpip** [comment]
#133

**Comment by dvmobley** [comment]
Yes, it appears to have fixed the height issue. I'm investigating a width issue, but I have an IFrame in that component. It may be related to the source document. I will open a new ticket for it if necessary.

**Comment by Tallon1252** [comment]
I still have this issue with Safari on macOS… The height gets right when i have the modal open and then opening the Dev Tools. Is there any fix available?

**Comment by Ridder90** [comment]
I have the same problem on safari and chrome on ios and only on iPhone 6. 

When rotating screen everything look great, but on initial load the jconfirm-content-pane has an height of 0px, while the content is correctly loaded in the DOM. Also when using the remote webinspector for ios i see there is an empty style tag on jconfirm-content. When i remove the empty style tag the confirm box shows nicely!?!

```
 jq.confirm({
        title: psps.buttons[psps.button_id].text,
        backgroundDismiss: true,
        boxWidth: '96%',
        useBootstrap: false,
        closeIcon: true,

        content: function() {
            var self = this;
            return jq.ajax({
                type: "POST",
                url: psps.ajax_url,
                data: postdata
            }).done(function(response) {
                if (response.success){
                        self.buttons.formSubmit.setText(response.data.text);
                        menu = some_html(response.data);
                        self.setContent(menu);
                        jq(window).trigger('resize');
                        self.setDialogCenter();
                 }
            }).fail(function() {
                self.setContent('<br>Can\'t establish a connection to the server.' );
            });
        },
        buttons: {
            formSubmit: {
                text: 'save',
                btnClass: 'btn-blue',
                action: function() {
                   do_stuff();
                }
            }
        }
    });
```

**Comment by konovalovk** [comment]
I have the issue at ios and 3.3.1 version - that.$content.outerHeight() was giving 0.
Force to use jquery method and it helped - "var contentHeight = that.**$($content)**.outerHeight() || 0;"
