### ISSUE TITLE
Scripts after $.alert({...}) can still be executed when the alert dialog poped

### ISSUE THREAD

**Issue by JackandRoses** [craftpip/jquery-confirm#79]
When original js's alert() function is executed, scripts after 'alert(...)' will suspended,but this plugin can not do that ...

**Comment by craftpip** [comment]
Hello
The native alert and confirm functions pause the execution, but this is not possible via external code. 
There is no way to stop the execution for code, This is why callbacks are used.

You can see this 
http://stackoverflow.com/questions/6807799/stop-page-execution-like-the-alert-function

**Comment by JackandRoses** [comment]
OK,TY!
