### ISSUE TITLE
Closing all alerts

### ISSUE THREAD

**Issue by Pecka40** [craftpip/jquery-confirm#8]
Would be really nice if it would be possible to close all alert boxes with only pressing once confirm on the first alert.

**Comment by craftpip** [comment]
@Pecka40 
Hello, thanks for your interest :)
I don't get the point in closing all the alert boxes, when only one will be visible to the user,
are you talking about when the alerts are stacked one above other ?

**Comment by Pecka40** [comment]
@craftpip 
Yes, thats exactly what I meant!
Sorry for not explaining it properly :)
Thanks for your hard work! I really appreciate it. :)

**Comment by craftpip** [comment]
@Pecka40 
Thank you for the kind words :) 

closing all directly through the plugin isn't possible because all the confirm dialogs are independent objects carrying their own close methods, 
Instead you can gather all the opened confirms and close them ?

like so:
```javascript
var refobj= [];
refobj.push($.alert(object));
refobj.push($.alert(object));
refobj.push($.alert(object));

// in the final confirm you close the previous ones.
$.alert({
    confirm: function(){
        $.each(refobj, function(i, a){
            a.close(); // you fire close method of all confirms.
        })
    }
});
```

Was this helpful ?

**Comment by Pecka40** [comment]
Thank you! That will probably do the trick!
But will it be bad if i add the close function to all of them? I don't really know in what order will they be called so i really don't know which is going to be the last.

**Comment by craftpip** [comment]
@Pecka40 

```javascript
var refobj = [];
function aliasConfirm(option){
     refobj.push($.confirm(option));
}
function closeAll(){
     $.each(refobj, function(i, a){ 
          a.close(); 
          // you can pop the closed ones from refobj array here.
     })
}

// and use it 
aliasConfirm({
     confirm: function(){
           closeAll();
     }
})
```

all dialogues opened with `aliasConfirm` will be closed with `closeAll` :+1: 
Fire the closeAll function on all, won't be a problem.
if the close method is fired on dialogue that is already closed, it ignores it. no harm.

**Comment by craftpip** [comment]
@Pecka40 Welcome! :)
