### ISSUE TITLE
multiple alerts popping on mobile ! 

### ISSUE THREAD

**Issue by jasan-s** [craftpip/jquery-confirm#80]
I have a button that once clicked launches an alert! however on mobile devices after the alert pops up the button is still visible thus allowed to be clicked again, and if i click on it more time while the alert is till up , more alert windows pop up.  THis is not the case on desktop.

**Comment by craftpip** [comment]
Hello @jasan-s , can you please post a screenshot of the issue, this may be a problem with z-index of your button that causes it to overlap on the modal.

**Comment by jasan-s** [comment]
I think you may be right. I'm using backstretch js for an image for the header, when i click the login button in the nav header, it seems as though the launched pop is placed above the top header DIV but under all the elemnts down the page. see the pics. I tried changing the z-index of the modal popup to 9999 and it doesnt seem to have any effect. 
![pop up z-index error](https://cloud.githubusercontent.com/assets/13863953/13780214/bea112d6-ea7b-11e5-9531-1e4696119e31.png)

**Comment by jasan-s** [comment]
@craftpip is it possible to stop the ability to scroll when the modal window is active?

**Comment by jasan-s** [comment]
So found a workaround, on modal popup i added class modal-open and removed it when closes with keyup and close button

**Comment by craftpip** [comment]
You can try a more larger number, maybe 999999999, Sure the scroll can be removed when the modal is open, that option is coming up in the next version of this plugin.

**Comment by craftpip** [comment]
you also have onOpen and onClose callbacks, to add and remove the classes.

**Comment by jasan-s** [comment]
weird but the scrolling is still enabled on apple touch devices.

**Comment by jasan-s** [comment]
it works fine on android touch  and desktop

**Comment by jasan-s** [comment]
have any idea how to disable scrolling on Apple touch devices

**Comment by craftpip** [comment]
If you're using Safari , i found this, 
http://stackoverflow.com/questions/7768269/ipad-safari-disable-scrolling-and-bounce-effect

**Comment by craftpip** [comment]
I will try and add this in the new release as well. thanks :)
