### ISSUE TITLE
Destroy dialog after being initialized

### ISSUE THREAD

**Issue by sideris** [craftpip/jquery-confirm#81]
Hello

Is there any utility that allows me to reinitialize a dialog without creating multiple instances? 

e.g. 

`$('.dialog').confirm({someparamshere});`
and then clicking the same button
`$('.dialog').confirm({someotherparams})`

Currently in the second case I get two windows open.

Thanks

**Comment by craftpip** [comment]
Hey @sideris, sorry i didn't understand the question. can you please add more details to what you are trying to achieve?

**Comment by sideris** [comment]
Hello. 

I have a trigger whose data can change. Everytime the data change I am calling something like 
```
initializeConfirm(data){
  $('somebutton').confirm({
       content: "data is " + data
       ......
  })
}
```

So first time I click the button all is well. Second time I click the button (with the new data) I am getting the desired dialog, but when I close it then I can see the first one as well.

**Comment by sideris** [comment]
Here

http://jsfiddle.net/pgsideris/93h0zd38/

**Comment by sideris** [comment]
I think setting the click listener separately  works for what I needed.
```
$('.confirm').unbind('click').click(function(){
  	$.confirm({
    	title: 'Confirming ' + n,
    	content: 'This is the number ' + n
  	});
  })
```

**Comment by craftpip** [comment]
Yes, glad you found the solution, :) I should probably add a re-initialize function if already initialized items. Thanks man.
