### ISSUE TITLE
IE9 (yes I know!) Console Issues

### ISSUE THREAD

**Issue by leesimple** [craftpip/jquery-confirm#87]
As much as I would like to think that IE9 is dead, it's simply not dead in the corporate world.  Therefore, while we love this plugin, it has to be modified to work with IE9.  Three simple changes have done that - removal of all three "console.log" calls.  IE9 will cause an 'undefined' error and simply not function unless these are hidden or removed.  Have been able to duplicate this over and over again.  Once removed, the issues vanish.

Thought you should know.

**Comment by craftpip** [comment]
Thank you, i will get this done

**Comment by leesimple** [comment]
Thanks..  keep up the great work!
