### ISSUE TITLE
Unobtrusive alert

### ISSUE THREAD

**Issue by gladwintech** [craftpip/jquery-confirm#89]
Hello,
Love this - however I'd like to see an unobtrusive popup that appeared in the top right or something similar, and that went away on a timer. I'm thinking a bit like:
https://sciactive.github.io/pnotify/#demos-modules

But without all the unnecessary extras, just pick a corner and write the contents and it disappears on a timer

**Comment by craftpip** [comment]
Hello @gladwintech , im already working on this, the plugin will use the same code, but different styles for notifications. :+1:
