### ISSUE TITLE
required input not show error message

### ISSUE THREAD

**Issue by SoullessL** [craftpip/jquery-confirm#93]
There are some required input in the page, and i want to submit the form after confirm,but after confirm and click the button it will not show error message "These is a required field" in chrome.
$.confirm({
                title: 'Confirmation',
                content: str,
                columnClass: 'col-md-6 col-md-offset-3',
                confirmButtonClass: 'btn-warning',
                cancelButtonClass: 'btn-primary',
                confirm: function () {
                        $('#hiddenBtn').attr("value", value);
                        $('#hiddenBtn').click();
                }
            });

**Comment by dvmobley** [comment]
You need to check the required fields in your confirm: function. Return false if they do not meet your conditions.

Dale

Sent from my iPhone

On Apr 27, 2016, at 5:33 AM, SoullessL <notifications@github.com<mailto:notifications@github.com>> wrote:


There are some required input in the page, and i want to submit the form after confirm,but after confirm and click the button it will not show error message "These is a required field" in chrome.
$.confirm({
title: 'Confirmation',
content: str,
columnClass: 'col-md-6 col-md-offset-3',
confirmButtonClass: 'btn-warning',
cancelButtonClass: 'btn-primary',
confirm: function () {
$('#hiddenBtn').attr("value", value);
$('#hiddenBtn').click();
}
});

**Comment by SoullessL** [comment]
<input type="text" name="usr_name" required="required" />,i just use required.

**Comment by SoullessL** [comment]
`<input type="text" name="usr_name" required="required" />`,i just use required

**Comment by dvmobley** [comment]
That an easy way to do it, but isn’t fully supported by Safari or Opera.

[cid:image001.png@01D1A05F.2C704EB0]

**Comment by SoullessL** [comment]
i know i can check the required fields in the confirm function but can i just use the html5 required/email properties?

**Comment by SoullessL** [comment]
`var isConfirm = false;
            $.confirm({
                title: $("#" + id).text() + ' Confirmation',
                content: str,
                columnClass: 'col-md-6 col-md-offset-3',
                confirmButtonClass: 'btn-warning',
                cancelButtonClass: 'btn-primary',
                confirm: function () {
                        $('#hiddenBtn').attr("value", value);
                        isConfirm = true;
                },
                onClose: function () {
                    if (isConfirm) {
                        this._lastFocused = $('#hiddenBtn');
                        $('#hiddenBtn').click();
                    }
                }
            });  `

when i add 'this._lastFocused = $('#hiddenBtn');' ,required property can work well on chrome

**Comment by SoullessL** [comment]
var isConfirm = false; $.confirm({ title: $("#" + id).text() + ' Confirmation', content: str, columnClass: 'col-md-6 col-md-offset-3', confirmButtonClass: 'btn-warning', cancelButtonClass: 'btn-primary', confirm: function () { $('#hiddenBtn').attr("value", value); isConfirm = true; }, onClose: function () { if (isConfirm) { this._lastFocused = $('#hiddenBtn'); $('#hiddenBtn').click(); } } });

when i add 'this._lastFocused = $('#hiddenBtn');' ,required property can work well on chrome

**Comment by SoullessL** [comment]
var isConfirm = false;
            $.confirm({
                title: ' Confirmation',
                content: str,
                columnClass: 'col-md-6 col-md-offset-3',
                confirmButtonClass: 'btn-warning',
                cancelButtonClass: 'btn-primary',
                confirm: function () {
                        $('#hiddenBtn').attr("value", value);
                        isConfirm = true;
                },
                onClose: function () {
                    if (isConfirm) {
                        this._lastFocused = $('#hiddenBtn');
                        $('#hiddenBtn').click();
                    }
                }
            });  

It is resolved, 
just add 'this._lastFocused = $('#hiddenBtn');' 
required property can work well on chrome.
