### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by vj-aasif** [craftpip/jquery-confirm#94]
hi..........................................................................................................................................

**Comment by vj-aasif** [comment]
hi

**Comment by vj-aasif** [comment]
How can I use this when I want to delete something?

**Comment by lxcn** [comment]
@vj-aasif 
maybe this can help you.
in my project, i use onclick(js:url) & function to do that.
active code:
`
<button onclick="del_something('delete.php')">delete</button>
`
and script code:
`
function del_something(url) {
			$.confirm({
				title: 'Confirm Delete',
				content: 'warning information here!',
				confirmButton: 'Delete',
				confirmButtonClass: 'btn-danger',
				cancelButton:'Cancel',
				confirm: function() {
					window.location.href = url;
				}
			});
		};
`

you can also use binding ClassName without onclick&function.

**Comment by vj-aasif** [comment]
Thank you so much :)

**Comment by vj-aasif** [comment]
I am working on a project and since I m very new to Javascript, probably you can help me?

**Comment by lxcn** [comment]
@vj-aasif 
yeah? what do you need?

**Comment by vj-aasif** [comment]
I am doing a project in codeigniter and would need some help. if you could give me your email then I can send some screenshots of my work and then if you don't get my work I can skype with you and share screen. Thanks in advance

**Comment by vj-aasif** [comment]
![screenshot 34](https://cloud.githubusercontent.com/assets/17564722/14937858/aee36270-0f35-11e6-97c6-4bfd06784613.png)
![screenshot 35](https://cloud.githubusercontent.com/assets/17564722/14937863/cb417d3a-0f35-11e6-9b81-526813c12860.png)
![screenshot 36](https://cloud.githubusercontent.com/assets/17564722/14937864/ceba6af8-0f35-11e6-9474-b39859aa49a1.png)
![screenshot 37](https://cloud.githubusercontent.com/assets/17564722/14937865/cfd5c644-0f35-11e6-8960-80856f4bf208.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/17564722/14937867/d825b8fe-0f35-11e6-9f21-44763930d665.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/17564722/14937868/d8344f4a-0f35-11e6-8850-0277428ac288.png)
![screenshot 42](https://cloud.githubusercontent.com/assets/17564722/14937869/d8a63d08-0f35-11e6-9ba4-3ae37ecba535.png)
![screenshot 43](https://cloud.githubusercontent.com/assets/17564722/14937871/d902311c-0f35-11e6-9c15-bb68d772c14b.png)
![screenshot 44](https://cloud.githubusercontent.com/assets/17564722/14937876/da09f892-0f35-11e6-9962-30743788e7f0.png)
![screenshot 45](https://cloud.githubusercontent.com/assets/17564722/14937877/da237894-0f35-11e6-826e-cee7ed8695da.png)
![screenshot 46](https://cloud.githubusercontent.com/assets/17564722/14937872/d90883c8-0f35-11e6-9709-20f4d2ca9f5a.png)
![screenshot 47](https://cloud.githubusercontent.com/assets/17564722/14937870/d8aa8200-0f35-11e6-9e9d-8d373f8410d7.png)
![screenshot 48](https://cloud.githubusercontent.com/assets/17564722/14937873/d91614a2-0f35-11e6-9b57-9bc68addd784.png)
![screenshot 49](https://cloud.githubusercontent.com/assets/17564722/14937874/d923b9cc-0f35-11e6-87bb-ccefc9cc399d.png)
![Uploading Screenshot (50).png…]()
![screenshot 38](https://cloud.githubusercontent.com/assets/17564722/14937875/d93286b4-0f35-11e6-8adc-95dd56e681fa.png)


I wrote javascript but it's not working. Hope the javascript is right. What I want if if I select an option then in the next select option will be related to first option. Like if I select United Kingdom then in the second option City will show from UK's only, then in the third option the area will show up from that city only.

**Comment by vj-aasif** [comment]
![localhost_2016-05-01_00-39-56](https://cloud.githubusercontent.com/assets/17564722/14937904/90b55adc-0f36-11e6-835a-95f5a40099c1.jpg)
 
this is what I want. You can see there are three selection option but I can see from the category only and if I click on another they are not showing up though they also have data.

**Comment by vj-aasif** [comment]
Choose Category - Category table in database and in codeigniter it's allCat
Choose Category First - Sub Category table in database and in codeigniter it's allScat
Choose Sub Category First - Child Category table in database and in codeigniter it's allChildcat

**Comment by lxcn** [comment]
@vj-aasif 
hi,
i using ajax to change next select. 
code like this:
`
<select id="firstselect" name="firstselect" onchange="func(this.value)">
<option value="1">test option</option>
</select>

<select id="secondselect" name="secondselect" onchange="func_sec(this.value)">
</select>

<select id="thirdselect" name="thirdselect">
</select>
`
js code lke this:
`
function func(tid){
if(tid!=0){
$.ajax({
url:url,
type: post,
data: data,
dataType: dataType;
success: function(data){
$("#secondselect").html(data);//if datatype is html, then this can be write; if datatype is other, then make it can be write to there.
}
});
}
};
`

maybe you can use the same function.
maybe you can use onblur or bind on select.

**Comment by dvmobley** [comment]
The url would point to a php page that returns your data in html. The input is not included in that statement.

Dale

Sent from my iPhone

On May 2, 2016, at 9:24 PM, lxcn <notifications@github.com<mailto:notifications@github.com>> wrote:


@vj-aasif<https://github.com/vj-aasif>
hi,
i using ajax to change next select.
code like this:
`
test option


js code lke this:

function func(tid){
if(tid!=0){
$.ajax({
url:url,
type: post,
data: data,
dataType: dataType;
success: function(data){
$("#secondselect").html(data);//if datatype is html, then this can be write; if datatype is other, then make it can be write to there.
}
});
}
};
`

maybe you can use the same function.
maybe you can use onblur or bind on select.
