### ISSUE TITLE
make it work like a normal confirm

### ISSUE THREAD

**Issue by anggakharisma** [craftpip/jquery-confirm#97]
Hello i try to make delete confirmation on my anchor tag, in normal jquery confirm if you click yes you will redirect to the href of the anchor tag, how you can do this with jquery-confirm ? here's my code.i already try the #47 & #36 issue .

```
function DeleteConfirm(callback) {
		$.confirm({
		    title: 'CONFIRMATION',
		    content: '<h4>Are you sure want to delete this ?</h4>',
		    confirm: function(){
		    	callback(true)
		    },
		    cancel: function(){
		    	callback(false);
		    }
		});
	}
```
```
$("#confirm").click(function(event) {
		console.log(id);
		event.preventDefault();
		DeleteConfirm(function(c){
			if(c == true) {
				//redirect to anchor tag href
				return true;
			}
		});
	});
```

**Comment by dvmobley** [comment]
Grab href from <a> tag and do a window.open in confirm: function .

Dale

Sent from my iPhone

On May 3, 2016, at 2:24 PM, anggakharisma <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello i try to make delete confirmation on my anchor tag, in normal jquery confirm if you click yes you will redirect to the href of the anchor tag, how you can do this with jquery-confirm ? here's my code.i already try the #47<https://github.com/craftpip/jquery-confirm/issues/47> & #36<https://github.com/craftpip/jquery-confirm/issues/36> issue .

function DeleteConfirm(callback) {
        $.confirm({
            title: 'CONFIRMATION',
            content: '<h4>Are you sure want to delete this ?</h4>',
            confirm: function(){
                callback(true)
            },
            cancel: function(){
                callback(false);
            }
        });
    }


$("#confirm").click(function(event) {
        console.log(id);
        event.preventDefault();
        DeleteConfirm(function(c){
            if(c == true) {
                //redirect to anchor tag href
                return true;
            }
        });
    });

**Comment by anggakharisma** [comment]
Thanks !
