### ISSUE TITLE
How to get button value?

### ISSUE THREAD

**Issue by lyhongpon** [craftpip/jquery-confirm#99]
I have button that when I click on it, the dialog appears. However, I need button data for some uses. I have no idea how I can do it.

**Comment by osman-R** [comment]
you can uer $Target like belowe in confirm: 
`var id=thgis.$target.data("id");`
and your tag is look like : 
`<a class="confirm" data-id="i" />`
hope to help you .

**Comment by lyhongpon** [comment]
I forgot how I solved this. But in similar way. 
Thanks.
